// GENERATED by generate-events.ts from events.json and runtime-script.base.d.ts. DO NOT EDIT.
// The Host supplies Entity Handles and gameplay operations for one Invocation.
// Scripts do not import modules. The builder lowers a static Event Binding to one Invocation.

// Entity fields are snapshots. A level-up event carries the attained level in newLevel.
interface Entity {
  readonly name: string;
  readonly is_player: boolean;
  readonly level: number;
  readonly health: number;
  readonly max_health: number;
  readonly map_id: number;
  readonly x: number;
  readonly y: number;
  readonly z: number;
}

interface PlayerEntity extends Entity {
  readonly is_player: true;
}

interface ScriptEvent {
  readonly name: string;
  readonly actor?: Entity;
  readonly target?: Entity;
}

interface PackageEvent extends ScriptEvent {}

interface EventRegistrationOptions {
  readonly priority?: number;
  readonly enabled?: boolean;
}

// Kept for sources that declare the legacy script() entry point.
declare const event: ScriptEvent;

declare function heal(entity: Entity, amount: number): void;
declare function send_chat(player: Entity, text: string): void;
declare function grant_xp(player: Entity, amount: number): void;

interface DamageTakenEvent extends ScriptEvent {
  readonly name: "on_damage_taken";
  readonly periodic: boolean;
}

interface CreatureDeathPreventedEvent extends ScriptEvent {
  readonly name: "on_death_prevented";
}

interface CreatureSpawnEvent extends ScriptEvent {
  readonly name: "on_creature_spawn";
  readonly entry: number;
  readonly x: number;
  readonly y: number;
  readonly z: number;
}

interface PlayerLevelUpEvent extends ScriptEvent {
  readonly name: "on_levelup";
  readonly player: PlayerEntity;
  readonly newLevel: number;
}

interface GroupInviteEvent extends ScriptEvent {
  readonly name: "on_group_invite";
}

interface DeathEvent extends ScriptEvent {
  readonly name: "on_death";
  readonly victimIsPlayer: boolean;
}

interface KillEvent extends ScriptEvent {
  readonly name: "on_kill";
  readonly victimEntry: number;
  readonly victimLevel: number;
}

interface CreatureAggroEvent extends ScriptEvent {
  readonly name: "on_aggro";
  readonly assist: boolean;
}

interface SpellCastResolvedEvent extends ScriptEvent {
  readonly name: "on_cast_resolved";
  readonly spellId: number;
}

interface SpellCastFinishedEvent extends ScriptEvent {
  readonly name: "on_cast_finished";
  readonly scheduledId: string;
  readonly outcome: string;
}

interface PlayerLootEvent extends ScriptEvent {
  readonly name: "on_loot";
  readonly itemEntry: number;
  readonly count: number;
}

interface PlayerQuestAcceptEvent extends ScriptEvent {
  readonly name: "on_quest_accept";
  readonly questEntry: number;
}

interface PlayerQuestTurnInEvent extends ScriptEvent {
  readonly name: "on_quest_turnin";
  readonly questEntry: number;
}

interface PlayerLoginEvent extends ScriptEvent {
  readonly name: "on_login";
  readonly player: PlayerEntity;
}

interface PlayerRelocatedEvent extends ScriptEvent {
  readonly name: "on_character_relocated";
}

interface PlayerLogoutEvent extends ScriptEvent {
  readonly name: "on_logout";
}

interface PlayerGossipSelectEvent extends ScriptEvent {
  readonly name: "on_gossip_select";
  readonly optionId: number;
  readonly optionRowId: number;
}

interface CreatureDeathEvent extends ScriptEvent {
  readonly name: "on_creature_death";
  readonly entry: number;
  readonly instanceId: string;
}

interface CreatureHpThresholdEvent extends ScriptEvent {
  readonly name: "on_hp_threshold";
  readonly entry: number;
  readonly instanceId: string;
  readonly pct: number;
}

interface GameobjectUsedEvent extends ScriptEvent {
  readonly name: "on_go_used";
  readonly entry: number;
  readonly instanceId: string;
}

declare const events: {
  readonly combat: {
    onDamageTaken(this: void, handler: (this: void, event: DamageTakenEvent) => number | void, options?: EventRegistrationOptions): void;
    onDeath(this: void, handler: (this: void, event: DeathEvent) => number | void, options?: EventRegistrationOptions): void;
    onKill(this: void, handler: (this: void, event: KillEvent) => number | void, options?: EventRegistrationOptions): void;
  };
  readonly creature: {
    onDeathPrevented(this: void, handler: (this: void, event: CreatureDeathPreventedEvent) => number | void, options?: EventRegistrationOptions): void;
    onSpawn(this: void, handler: (this: void, event: CreatureSpawnEvent) => number | void, options?: EventRegistrationOptions): void;
    onAggro(this: void, handler: (this: void, event: CreatureAggroEvent) => number | void, options?: EventRegistrationOptions): void;
    onDeath(this: void, handler: (this: void, event: CreatureDeathEvent) => number | void, options?: EventRegistrationOptions): void;
    onHpThreshold(this: void, handler: (this: void, event: CreatureHpThresholdEvent) => number | void, options?: EventRegistrationOptions): void;
  };
  readonly player: {
    onLevelUp(this: void, handler: (this: void, event: PlayerLevelUpEvent) => number | void, options?: EventRegistrationOptions): void;
    onLoot(this: void, handler: (this: void, event: PlayerLootEvent) => number | void, options?: EventRegistrationOptions): void;
    onQuestAccept(this: void, handler: (this: void, event: PlayerQuestAcceptEvent) => number | void, options?: EventRegistrationOptions): void;
    onQuestTurnIn(this: void, handler: (this: void, event: PlayerQuestTurnInEvent) => number | void, options?: EventRegistrationOptions): void;
    onLogin(this: void, handler: (this: void, event: PlayerLoginEvent) => number | void, options?: EventRegistrationOptions): void;
    onRelocated(this: void, handler: (this: void, event: PlayerRelocatedEvent) => number | void, options?: EventRegistrationOptions): void;
    onLogout(this: void, handler: (this: void, event: PlayerLogoutEvent) => number | void, options?: EventRegistrationOptions): void;
    onGossipSelect(this: void, handler: (this: void, event: PlayerGossipSelectEvent) => number | void, options?: EventRegistrationOptions): void;
  };
  readonly group: {
    onInvite(this: void, handler: (this: void, event: GroupInviteEvent) => number | void, options?: EventRegistrationOptions): void;
  };
  readonly spell: {
    onCastResolved(this: void, handler: (this: void, event: SpellCastResolvedEvent) => number | void, options?: EventRegistrationOptions): void;
    onCastFinished(this: void, handler: (this: void, event: SpellCastFinishedEvent) => number | void, options?: EventRegistrationOptions): void;
  };
  readonly gameobject: {
    onUsed(this: void, handler: (this: void, event: GameobjectUsedEvent) => number | void, options?: EventRegistrationOptions): void;
  };
  readonly package: {
    on(this: void, localName: string, handler: (this: void, event: PackageEvent) => number | void, options?: EventRegistrationOptions): void;
  };
};
