// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AccountFence {
    pub account_id: u64,
    pub account_name: String,
    pub generation: u64,
    pub request_nonce: u128,
    pub character_guid: u64,
    pub expires_micros: i64,
    pub closed: bool,
}

impl __sdk::InModule for AccountFence {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AccountFence`.
///
/// Provides typed access to columns for query building.
pub struct AccountFenceCols {
    pub account_id: __sdk::__query_builder::Col<AccountFence, u64>,
    pub account_name: __sdk::__query_builder::Col<AccountFence, String>,
    pub generation: __sdk::__query_builder::Col<AccountFence, u64>,
    pub request_nonce: __sdk::__query_builder::Col<AccountFence, u128>,
    pub character_guid: __sdk::__query_builder::Col<AccountFence, u64>,
    pub expires_micros: __sdk::__query_builder::Col<AccountFence, i64>,
    pub closed: __sdk::__query_builder::Col<AccountFence, bool>,
}

impl __sdk::__query_builder::HasCols for AccountFence {
    type Cols = AccountFenceCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AccountFenceCols {
            account_id: __sdk::__query_builder::Col::new(table_name, "account_id"),
            account_name: __sdk::__query_builder::Col::new(table_name, "account_name"),
            generation: __sdk::__query_builder::Col::new(table_name, "generation"),
            request_nonce: __sdk::__query_builder::Col::new(table_name, "request_nonce"),
            character_guid: __sdk::__query_builder::Col::new(table_name, "character_guid"),
            expires_micros: __sdk::__query_builder::Col::new(table_name, "expires_micros"),
            closed: __sdk::__query_builder::Col::new(table_name, "closed"),
        }
    }
}

/// Indexed column accessor struct for the table `AccountFence`.
///
/// Provides typed access to indexed columns for query building.
pub struct AccountFenceIxCols {
    pub account_id: __sdk::__query_builder::IxCol<AccountFence, u64>,
    pub character_guid: __sdk::__query_builder::IxCol<AccountFence, u64>,
    pub closed: __sdk::__query_builder::IxCol<AccountFence, bool>,
}

impl __sdk::__query_builder::HasIxCols for AccountFence {
    type IxCols = AccountFenceIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AccountFenceIxCols {
            account_id: __sdk::__query_builder::IxCol::new(table_name, "account_id"),
            character_guid: __sdk::__query_builder::IxCol::new(table_name, "character_guid"),
            closed: __sdk::__query_builder::IxCol::new(table_name, "closed"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for AccountFence {}
