// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AddonMessage {
    pub id: u64,
    pub recipient_identity: __sdk::Identity,
    pub cmd: String,
    pub payload: String,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for AddonMessage {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AddonMessage`.
///
/// Provides typed access to columns for query building.
pub struct AddonMessageCols {
    pub id: __sdk::__query_builder::Col<AddonMessage, u64>,
    pub recipient_identity: __sdk::__query_builder::Col<AddonMessage, __sdk::Identity>,
    pub cmd: __sdk::__query_builder::Col<AddonMessage, String>,
    pub payload: __sdk::__query_builder::Col<AddonMessage, String>,
    pub created_at: __sdk::__query_builder::Col<AddonMessage, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for AddonMessage {
    type Cols = AddonMessageCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AddonMessageCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            recipient_identity: __sdk::__query_builder::Col::new(table_name, "recipient_identity"),
            cmd: __sdk::__query_builder::Col::new(table_name, "cmd"),
            payload: __sdk::__query_builder::Col::new(table_name, "payload"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `AddonMessage`.
///
/// Provides typed access to indexed columns for query building.
pub struct AddonMessageIxCols {
    pub id: __sdk::__query_builder::IxCol<AddonMessage, u64>,
}

impl __sdk::__query_builder::HasIxCols for AddonMessage {
    type IxCols = AddonMessageIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AddonMessageIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for AddonMessage {}
