// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AuctionHold {
    pub operation_id: u64,
    pub seller_guid: u64,
    pub item_guid: u64,
    pub item_entry: u32,
    pub item_stack_count: u32,
    pub item_durability: u32,
    pub item_enchant_id: u32,
    pub item_soulbound: bool,
    pub start_bid: u32,
    pub buyout: u32,
    pub duration_minutes: u32,
    pub deposit: u32,
    pub created_micros: i64,
    pub expires_micros: i64,
}

impl __sdk::InModule for AuctionHold {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AuctionHold`.
///
/// Provides typed access to columns for query building.
pub struct AuctionHoldCols {
    pub operation_id: __sdk::__query_builder::Col<AuctionHold, u64>,
    pub seller_guid: __sdk::__query_builder::Col<AuctionHold, u64>,
    pub item_guid: __sdk::__query_builder::Col<AuctionHold, u64>,
    pub item_entry: __sdk::__query_builder::Col<AuctionHold, u32>,
    pub item_stack_count: __sdk::__query_builder::Col<AuctionHold, u32>,
    pub item_durability: __sdk::__query_builder::Col<AuctionHold, u32>,
    pub item_enchant_id: __sdk::__query_builder::Col<AuctionHold, u32>,
    pub item_soulbound: __sdk::__query_builder::Col<AuctionHold, bool>,
    pub start_bid: __sdk::__query_builder::Col<AuctionHold, u32>,
    pub buyout: __sdk::__query_builder::Col<AuctionHold, u32>,
    pub duration_minutes: __sdk::__query_builder::Col<AuctionHold, u32>,
    pub deposit: __sdk::__query_builder::Col<AuctionHold, u32>,
    pub created_micros: __sdk::__query_builder::Col<AuctionHold, i64>,
    pub expires_micros: __sdk::__query_builder::Col<AuctionHold, i64>,
}

impl __sdk::__query_builder::HasCols for AuctionHold {
    type Cols = AuctionHoldCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AuctionHoldCols {
            operation_id: __sdk::__query_builder::Col::new(table_name, "operation_id"),
            seller_guid: __sdk::__query_builder::Col::new(table_name, "seller_guid"),
            item_guid: __sdk::__query_builder::Col::new(table_name, "item_guid"),
            item_entry: __sdk::__query_builder::Col::new(table_name, "item_entry"),
            item_stack_count: __sdk::__query_builder::Col::new(table_name, "item_stack_count"),
            item_durability: __sdk::__query_builder::Col::new(table_name, "item_durability"),
            item_enchant_id: __sdk::__query_builder::Col::new(table_name, "item_enchant_id"),
            item_soulbound: __sdk::__query_builder::Col::new(table_name, "item_soulbound"),
            start_bid: __sdk::__query_builder::Col::new(table_name, "start_bid"),
            buyout: __sdk::__query_builder::Col::new(table_name, "buyout"),
            duration_minutes: __sdk::__query_builder::Col::new(table_name, "duration_minutes"),
            deposit: __sdk::__query_builder::Col::new(table_name, "deposit"),
            created_micros: __sdk::__query_builder::Col::new(table_name, "created_micros"),
            expires_micros: __sdk::__query_builder::Col::new(table_name, "expires_micros"),
        }
    }
}

/// Indexed column accessor struct for the table `AuctionHold`.
///
/// Provides typed access to indexed columns for query building.
pub struct AuctionHoldIxCols {
    pub operation_id: __sdk::__query_builder::IxCol<AuctionHold, u64>,
    pub seller_guid: __sdk::__query_builder::IxCol<AuctionHold, u64>,
}

impl __sdk::__query_builder::HasIxCols for AuctionHold {
    type IxCols = AuctionHoldIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AuctionHoldIxCols {
            operation_id: __sdk::__query_builder::IxCol::new(table_name, "operation_id"),
            seller_guid: __sdk::__query_builder::IxCol::new(table_name, "seller_guid"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for AuctionHold {}
