// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AuctionNotice {
    pub id: u64,
    pub recipient_guid: u64,
    pub kind: u8,
    pub house: u32,
    pub auction_id: u32,
    pub item_entry: u32,
    pub random_property_id: u32,
    pub bid: u32,
    pub out_bid: u32,
    pub bidder_guid: u64,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for AuctionNotice {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AuctionNotice`.
///
/// Provides typed access to columns for query building.
pub struct AuctionNoticeCols {
    pub id: __sdk::__query_builder::Col<AuctionNotice, u64>,
    pub recipient_guid: __sdk::__query_builder::Col<AuctionNotice, u64>,
    pub kind: __sdk::__query_builder::Col<AuctionNotice, u8>,
    pub house: __sdk::__query_builder::Col<AuctionNotice, u32>,
    pub auction_id: __sdk::__query_builder::Col<AuctionNotice, u32>,
    pub item_entry: __sdk::__query_builder::Col<AuctionNotice, u32>,
    pub random_property_id: __sdk::__query_builder::Col<AuctionNotice, u32>,
    pub bid: __sdk::__query_builder::Col<AuctionNotice, u32>,
    pub out_bid: __sdk::__query_builder::Col<AuctionNotice, u32>,
    pub bidder_guid: __sdk::__query_builder::Col<AuctionNotice, u64>,
    pub created_at: __sdk::__query_builder::Col<AuctionNotice, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for AuctionNotice {
    type Cols = AuctionNoticeCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AuctionNoticeCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            recipient_guid: __sdk::__query_builder::Col::new(table_name, "recipient_guid"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            house: __sdk::__query_builder::Col::new(table_name, "house"),
            auction_id: __sdk::__query_builder::Col::new(table_name, "auction_id"),
            item_entry: __sdk::__query_builder::Col::new(table_name, "item_entry"),
            random_property_id: __sdk::__query_builder::Col::new(table_name, "random_property_id"),
            bid: __sdk::__query_builder::Col::new(table_name, "bid"),
            out_bid: __sdk::__query_builder::Col::new(table_name, "out_bid"),
            bidder_guid: __sdk::__query_builder::Col::new(table_name, "bidder_guid"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `AuctionNotice`.
///
/// Provides typed access to indexed columns for query building.
pub struct AuctionNoticeIxCols {
    pub id: __sdk::__query_builder::IxCol<AuctionNotice, u64>,
    pub recipient_guid: __sdk::__query_builder::IxCol<AuctionNotice, u64>,
}

impl __sdk::__query_builder::HasIxCols for AuctionNotice {
    type IxCols = AuctionNoticeIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AuctionNoticeIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            recipient_guid: __sdk::__query_builder::IxCol::new(table_name, "recipient_guid"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for AuctionNotice {}
