// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct BindBotTransferLocatorArgs {
    pub intent_id: u64,
    pub bot_guid: u64,
    pub controller_generation: u64,
    pub claim_token: u64,
    pub source_map: u32,
    pub source_instance: u64,
    pub source_locator_revision: u64,
}

impl From<BindBotTransferLocatorArgs> for super::Reducer {
    fn from(args: BindBotTransferLocatorArgs) -> Self {
        Self::BindBotTransferLocator {
            intent_id: args.intent_id,
            bot_guid: args.bot_guid,
            controller_generation: args.controller_generation,
            claim_token: args.claim_token,
            source_map: args.source_map,
            source_instance: args.source_instance,
            source_locator_revision: args.source_locator_revision,
        }
    }
}

impl __sdk::InModule for BindBotTransferLocatorArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `bind_bot_transfer_locator`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait bind_bot_transfer_locator {
    /// Request that the remote module invoke the reducer `bind_bot_transfer_locator` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`bind_bot_transfer_locator:bind_bot_transfer_locator_then`] to run a callback after the reducer completes.
    fn bind_bot_transfer_locator(
        &self,
        intent_id: u64,
        bot_guid: u64,
        controller_generation: u64,
        claim_token: u64,
        source_map: u32,
        source_instance: u64,
        source_locator_revision: u64,
    ) -> __sdk::Result<()> {
        self.bind_bot_transfer_locator_then(
            intent_id,
            bot_guid,
            controller_generation,
            claim_token,
            source_map,
            source_instance,
            source_locator_revision,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `bind_bot_transfer_locator` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn bind_bot_transfer_locator_then(
        &self,
        intent_id: u64,
        bot_guid: u64,
        controller_generation: u64,
        claim_token: u64,
        source_map: u32,
        source_instance: u64,
        source_locator_revision: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl bind_bot_transfer_locator for super::RemoteReducers {
    fn bind_bot_transfer_locator_then(
        &self,
        intent_id: u64,
        bot_guid: u64,
        controller_generation: u64,
        claim_token: u64,
        source_map: u32,
        source_instance: u64,
        source_locator_revision: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            BindBotTransferLocatorArgs {
                intent_id,
                bot_guid,
                controller_generation,
                claim_token,
                source_map,
                source_instance,
                source_locator_revision,
            },
            callback,
        )
    }
}
