// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct BuyItemArgs {
    pub vendor_guid: u64,
    pub item_entry: u32,
    pub count: u32,
}

impl From<BuyItemArgs> for super::Reducer {
    fn from(args: BuyItemArgs) -> Self {
        Self::BuyItem {
            vendor_guid: args.vendor_guid,
            item_entry: args.item_entry,
            count: args.count,
        }
    }
}

impl __sdk::InModule for BuyItemArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `buy_item`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait buy_item {
    /// Request that the remote module invoke the reducer `buy_item` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`buy_item:buy_item_then`] to run a callback after the reducer completes.
    fn buy_item(&self, vendor_guid: u64, item_entry: u32, count: u32) -> __sdk::Result<()> {
        self.buy_item_then(vendor_guid, item_entry, count, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `buy_item` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn buy_item_then(
        &self,
        vendor_guid: u64,
        item_entry: u32,
        count: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl buy_item for super::RemoteReducers {
    fn buy_item_then(
        &self,
        vendor_guid: u64,
        item_entry: u32,
        count: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            BuyItemArgs {
                vendor_guid,
                item_entry,
                count,
            },
            callback,
        )
    }
}
