// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CancelAuraArgs {
    pub spell_id: u32,
}

impl From<CancelAuraArgs> for super::Reducer {
    fn from(args: CancelAuraArgs) -> Self {
        Self::CancelAura {
            spell_id: args.spell_id,
        }
    }
}

impl __sdk::InModule for CancelAuraArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `cancel_aura`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait cancel_aura {
    /// Request that the remote module invoke the reducer `cancel_aura` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`cancel_aura:cancel_aura_then`] to run a callback after the reducer completes.
    fn cancel_aura(&self, spell_id: u32) -> __sdk::Result<()> {
        self.cancel_aura_then(spell_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `cancel_aura` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn cancel_aura_then(
        &self,
        spell_id: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl cancel_aura for super::RemoteReducers {
    fn cancel_aura_then(
        &self,
        spell_id: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(CancelAuraArgs { spell_id }, callback)
    }
}
