// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::instruction_target_type::InstructionTarget;
use super::spell_caster_role_type::SpellCasterRole;
use super::spell_start_mode_type::SpellStartMode;
use super::spell_target_role_type::SpellTargetRole;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CastInstruction {
    pub spell_id: u32,
    pub target: InstructionTarget,
    pub interrupt_previous: bool,
    pub start_mode: SpellStartMode,
    pub caster_role: SpellCasterRole,
    pub target_role: SpellTargetRole,
    pub aura_absent: bool,
    pub character_only: bool,
    pub target_must_be_casting: bool,
    pub main_spell: bool,
    pub distance_after_start: bool,
}

impl __sdk::InModule for CastInstruction {
    type Module = super::RemoteModule;
}
