// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::world_session_token_type::WorldSessionToken;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CloseAccountFenceArgs {
    pub token: WorldSessionToken,
}

impl From<CloseAccountFenceArgs> for super::Reducer {
    fn from(args: CloseAccountFenceArgs) -> Self {
        Self::CloseAccountFence { token: args.token }
    }
}

impl __sdk::InModule for CloseAccountFenceArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `close_account_fence`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait close_account_fence {
    /// Request that the remote module invoke the reducer `close_account_fence` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`close_account_fence:close_account_fence_then`] to run a callback after the reducer completes.
    fn close_account_fence(&self, token: WorldSessionToken) -> __sdk::Result<()> {
        self.close_account_fence_then(token, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `close_account_fence` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn close_account_fence_then(
        &self,
        token: WorldSessionToken,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl close_account_fence for super::RemoteReducers {
    fn close_account_fence_then(
        &self,
        token: WorldSessionToken,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(CloseAccountFenceArgs { token }, callback)
    }
}
