// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CreatureRelayTemporaryFaction {
    pub creature_guid: u64,
}

impl __sdk::InModule for CreatureRelayTemporaryFaction {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CreatureRelayTemporaryFaction`.
///
/// Provides typed access to columns for query building.
pub struct CreatureRelayTemporaryFactionCols {
    pub creature_guid: __sdk::__query_builder::Col<CreatureRelayTemporaryFaction, u64>,
}

impl __sdk::__query_builder::HasCols for CreatureRelayTemporaryFaction {
    type Cols = CreatureRelayTemporaryFactionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CreatureRelayTemporaryFactionCols {
            creature_guid: __sdk::__query_builder::Col::new(table_name, "creature_guid"),
        }
    }
}

/// Indexed column accessor struct for the table `CreatureRelayTemporaryFaction`.
///
/// Provides typed access to indexed columns for query building.
pub struct CreatureRelayTemporaryFactionIxCols {
    pub creature_guid: __sdk::__query_builder::IxCol<CreatureRelayTemporaryFaction, u64>,
}

impl __sdk::__query_builder::HasIxCols for CreatureRelayTemporaryFaction {
    type IxCols = CreatureRelayTemporaryFactionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CreatureRelayTemporaryFactionIxCols {
            creature_guid: __sdk::__query_builder::IxCol::new(table_name, "creature_guid"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CreatureRelayTemporaryFaction {}
