// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::event_ai_rule_type::EventAiRule;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CreatureAiDefinition {
    pub id: u64,
    pub creature_entry: u32,
    pub creature_guid: u64,
    pub definition_revision: u64,
    pub rules: Vec<EventAiRule>,
}

impl __sdk::InModule for CreatureAiDefinition {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CreatureAiDefinition`.
///
/// Provides typed access to columns for query building.
pub struct CreatureAiDefinitionCols {
    pub id: __sdk::__query_builder::Col<CreatureAiDefinition, u64>,
    pub creature_entry: __sdk::__query_builder::Col<CreatureAiDefinition, u32>,
    pub creature_guid: __sdk::__query_builder::Col<CreatureAiDefinition, u64>,
    pub definition_revision: __sdk::__query_builder::Col<CreatureAiDefinition, u64>,
    pub rules: __sdk::__query_builder::Col<CreatureAiDefinition, Vec<EventAiRule>>,
}

impl __sdk::__query_builder::HasCols for CreatureAiDefinition {
    type Cols = CreatureAiDefinitionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CreatureAiDefinitionCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            creature_entry: __sdk::__query_builder::Col::new(table_name, "creature_entry"),
            creature_guid: __sdk::__query_builder::Col::new(table_name, "creature_guid"),
            definition_revision: __sdk::__query_builder::Col::new(
                table_name,
                "definition_revision",
            ),
            rules: __sdk::__query_builder::Col::new(table_name, "rules"),
        }
    }
}

/// Indexed column accessor struct for the table `CreatureAiDefinition`.
///
/// Provides typed access to indexed columns for query building.
pub struct CreatureAiDefinitionIxCols {
    pub creature_entry: __sdk::__query_builder::IxCol<CreatureAiDefinition, u32>,
    pub creature_guid: __sdk::__query_builder::IxCol<CreatureAiDefinition, u64>,
    pub id: __sdk::__query_builder::IxCol<CreatureAiDefinition, u64>,
}

impl __sdk::__query_builder::HasIxCols for CreatureAiDefinition {
    type IxCols = CreatureAiDefinitionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CreatureAiDefinitionIxCols {
            creature_entry: __sdk::__query_builder::IxCol::new(table_name, "creature_entry"),
            creature_guid: __sdk::__query_builder::IxCol::new(table_name, "creature_guid"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CreatureAiDefinition {}
