// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CreatureAiSummonOrigin {
    pub creature_guid: u64,
    pub summoner_guid: u64,
}

impl __sdk::InModule for CreatureAiSummonOrigin {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CreatureAiSummonOrigin`.
///
/// Provides typed access to columns for query building.
pub struct CreatureAiSummonOriginCols {
    pub creature_guid: __sdk::__query_builder::Col<CreatureAiSummonOrigin, u64>,
    pub summoner_guid: __sdk::__query_builder::Col<CreatureAiSummonOrigin, u64>,
}

impl __sdk::__query_builder::HasCols for CreatureAiSummonOrigin {
    type Cols = CreatureAiSummonOriginCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CreatureAiSummonOriginCols {
            creature_guid: __sdk::__query_builder::Col::new(table_name, "creature_guid"),
            summoner_guid: __sdk::__query_builder::Col::new(table_name, "summoner_guid"),
        }
    }
}

/// Indexed column accessor struct for the table `CreatureAiSummonOrigin`.
///
/// Provides typed access to indexed columns for query building.
pub struct CreatureAiSummonOriginIxCols {
    pub creature_guid: __sdk::__query_builder::IxCol<CreatureAiSummonOrigin, u64>,
}

impl __sdk::__query_builder::HasIxCols for CreatureAiSummonOrigin {
    type IxCols = CreatureAiSummonOriginIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CreatureAiSummonOriginIxCols {
            creature_guid: __sdk::__query_builder::IxCol::new(table_name, "creature_guid"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CreatureAiSummonOrigin {}
