// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CreatureLootTagGroup {
    pub creature_guid: u64,
    pub group_id: u64,
}

impl __sdk::InModule for CreatureLootTagGroup {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CreatureLootTagGroup`.
///
/// Provides typed access to columns for query building.
pub struct CreatureLootTagGroupCols {
    pub creature_guid: __sdk::__query_builder::Col<CreatureLootTagGroup, u64>,
    pub group_id: __sdk::__query_builder::Col<CreatureLootTagGroup, u64>,
}

impl __sdk::__query_builder::HasCols for CreatureLootTagGroup {
    type Cols = CreatureLootTagGroupCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CreatureLootTagGroupCols {
            creature_guid: __sdk::__query_builder::Col::new(table_name, "creature_guid"),
            group_id: __sdk::__query_builder::Col::new(table_name, "group_id"),
        }
    }
}

/// Indexed column accessor struct for the table `CreatureLootTagGroup`.
///
/// Provides typed access to indexed columns for query building.
pub struct CreatureLootTagGroupIxCols {
    pub creature_guid: __sdk::__query_builder::IxCol<CreatureLootTagGroup, u64>,
}

impl __sdk::__query_builder::HasIxCols for CreatureLootTagGroup {
    type IxCols = CreatureLootTagGroupIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CreatureLootTagGroupIxCols {
            creature_guid: __sdk::__query_builder::IxCol::new(table_name, "creature_guid"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CreatureLootTagGroup {}
