// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::authored_idle_movement_type::AuthoredIdleMovement;
use super::authored_walking_mode_type::AuthoredWalkingMode;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CreatureAiMovementIntent {
    pub creature_guid: u64,
    pub definition_revision: u64,
    pub creature_entry: u32,
    pub map_id: u32,
    pub instance_id: u64,
    pub idle: AuthoredIdleMovement,
    pub idle_active: bool,
    pub anchor_x: f32,
    pub anchor_y: f32,
    pub anchor_z: f32,
    pub random_radius_yd: f32,
    pub path_id: u32,
    pub patrol_paused: bool,
    pub combat_movement_active: bool,
    pub combat_movement_enabled: bool,
    pub follow_movement_active: bool,
    pub follow_movement_enabled: bool,
    pub walking: AuthoredWalkingMode,
    pub immobilized: bool,
    pub immobilized_combat_only: bool,
    pub facing_pending: bool,
    pub facing_reset: bool,
    pub facing_target_guid: u64,
}

impl __sdk::InModule for CreatureAiMovementIntent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CreatureAiMovementIntent`.
///
/// Provides typed access to columns for query building.
pub struct CreatureAiMovementIntentCols {
    pub creature_guid: __sdk::__query_builder::Col<CreatureAiMovementIntent, u64>,
    pub definition_revision: __sdk::__query_builder::Col<CreatureAiMovementIntent, u64>,
    pub creature_entry: __sdk::__query_builder::Col<CreatureAiMovementIntent, u32>,
    pub map_id: __sdk::__query_builder::Col<CreatureAiMovementIntent, u32>,
    pub instance_id: __sdk::__query_builder::Col<CreatureAiMovementIntent, u64>,
    pub idle: __sdk::__query_builder::Col<CreatureAiMovementIntent, AuthoredIdleMovement>,
    pub idle_active: __sdk::__query_builder::Col<CreatureAiMovementIntent, bool>,
    pub anchor_x: __sdk::__query_builder::Col<CreatureAiMovementIntent, f32>,
    pub anchor_y: __sdk::__query_builder::Col<CreatureAiMovementIntent, f32>,
    pub anchor_z: __sdk::__query_builder::Col<CreatureAiMovementIntent, f32>,
    pub random_radius_yd: __sdk::__query_builder::Col<CreatureAiMovementIntent, f32>,
    pub path_id: __sdk::__query_builder::Col<CreatureAiMovementIntent, u32>,
    pub patrol_paused: __sdk::__query_builder::Col<CreatureAiMovementIntent, bool>,
    pub combat_movement_active: __sdk::__query_builder::Col<CreatureAiMovementIntent, bool>,
    pub combat_movement_enabled: __sdk::__query_builder::Col<CreatureAiMovementIntent, bool>,
    pub follow_movement_active: __sdk::__query_builder::Col<CreatureAiMovementIntent, bool>,
    pub follow_movement_enabled: __sdk::__query_builder::Col<CreatureAiMovementIntent, bool>,
    pub walking: __sdk::__query_builder::Col<CreatureAiMovementIntent, AuthoredWalkingMode>,
    pub immobilized: __sdk::__query_builder::Col<CreatureAiMovementIntent, bool>,
    pub immobilized_combat_only: __sdk::__query_builder::Col<CreatureAiMovementIntent, bool>,
    pub facing_pending: __sdk::__query_builder::Col<CreatureAiMovementIntent, bool>,
    pub facing_reset: __sdk::__query_builder::Col<CreatureAiMovementIntent, bool>,
    pub facing_target_guid: __sdk::__query_builder::Col<CreatureAiMovementIntent, u64>,
}

impl __sdk::__query_builder::HasCols for CreatureAiMovementIntent {
    type Cols = CreatureAiMovementIntentCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CreatureAiMovementIntentCols {
            creature_guid: __sdk::__query_builder::Col::new(table_name, "creature_guid"),
            definition_revision: __sdk::__query_builder::Col::new(
                table_name,
                "definition_revision",
            ),
            creature_entry: __sdk::__query_builder::Col::new(table_name, "creature_entry"),
            map_id: __sdk::__query_builder::Col::new(table_name, "map_id"),
            instance_id: __sdk::__query_builder::Col::new(table_name, "instance_id"),
            idle: __sdk::__query_builder::Col::new(table_name, "idle"),
            idle_active: __sdk::__query_builder::Col::new(table_name, "idle_active"),
            anchor_x: __sdk::__query_builder::Col::new(table_name, "anchor_x"),
            anchor_y: __sdk::__query_builder::Col::new(table_name, "anchor_y"),
            anchor_z: __sdk::__query_builder::Col::new(table_name, "anchor_z"),
            random_radius_yd: __sdk::__query_builder::Col::new(table_name, "random_radius_yd"),
            path_id: __sdk::__query_builder::Col::new(table_name, "path_id"),
            patrol_paused: __sdk::__query_builder::Col::new(table_name, "patrol_paused"),
            combat_movement_active: __sdk::__query_builder::Col::new(
                table_name,
                "combat_movement_active",
            ),
            combat_movement_enabled: __sdk::__query_builder::Col::new(
                table_name,
                "combat_movement_enabled",
            ),
            follow_movement_active: __sdk::__query_builder::Col::new(
                table_name,
                "follow_movement_active",
            ),
            follow_movement_enabled: __sdk::__query_builder::Col::new(
                table_name,
                "follow_movement_enabled",
            ),
            walking: __sdk::__query_builder::Col::new(table_name, "walking"),
            immobilized: __sdk::__query_builder::Col::new(table_name, "immobilized"),
            immobilized_combat_only: __sdk::__query_builder::Col::new(
                table_name,
                "immobilized_combat_only",
            ),
            facing_pending: __sdk::__query_builder::Col::new(table_name, "facing_pending"),
            facing_reset: __sdk::__query_builder::Col::new(table_name, "facing_reset"),
            facing_target_guid: __sdk::__query_builder::Col::new(table_name, "facing_target_guid"),
        }
    }
}

/// Indexed column accessor struct for the table `CreatureAiMovementIntent`.
///
/// Provides typed access to indexed columns for query building.
pub struct CreatureAiMovementIntentIxCols {
    pub creature_guid: __sdk::__query_builder::IxCol<CreatureAiMovementIntent, u64>,
}

impl __sdk::__query_builder::HasIxCols for CreatureAiMovementIntent {
    type IxCols = CreatureAiMovementIntentIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CreatureAiMovementIntentIxCols {
            creature_guid: __sdk::__query_builder::IxCol::new(table_name, "creature_guid"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CreatureAiMovementIntent {}
