// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DebugReplaySessionlessAreatriggerArgs {
    pub character_guid: u64,
    pub trigger_id: u32,
    pub expected_map: u32,
    pub expected_instance: u64,
    pub controller_generation: u64,
    pub expected_intent_id: u64,
}

impl From<DebugReplaySessionlessAreatriggerArgs> for super::Reducer {
    fn from(args: DebugReplaySessionlessAreatriggerArgs) -> Self {
        Self::DebugReplaySessionlessAreatrigger {
            character_guid: args.character_guid,
            trigger_id: args.trigger_id,
            expected_map: args.expected_map,
            expected_instance: args.expected_instance,
            controller_generation: args.controller_generation,
            expected_intent_id: args.expected_intent_id,
        }
    }
}

impl __sdk::InModule for DebugReplaySessionlessAreatriggerArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `debug_replay_sessionless_areatrigger`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait debug_replay_sessionless_areatrigger {
    /// Request that the remote module invoke the reducer `debug_replay_sessionless_areatrigger` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`debug_replay_sessionless_areatrigger:debug_replay_sessionless_areatrigger_then`] to run a callback after the reducer completes.
    fn debug_replay_sessionless_areatrigger(
        &self,
        character_guid: u64,
        trigger_id: u32,
        expected_map: u32,
        expected_instance: u64,
        controller_generation: u64,
        expected_intent_id: u64,
    ) -> __sdk::Result<()> {
        self.debug_replay_sessionless_areatrigger_then(
            character_guid,
            trigger_id,
            expected_map,
            expected_instance,
            controller_generation,
            expected_intent_id,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `debug_replay_sessionless_areatrigger` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn debug_replay_sessionless_areatrigger_then(
        &self,
        character_guid: u64,
        trigger_id: u32,
        expected_map: u32,
        expected_instance: u64,
        controller_generation: u64,
        expected_intent_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl debug_replay_sessionless_areatrigger for super::RemoteReducers {
    fn debug_replay_sessionless_areatrigger_then(
        &self,
        character_guid: u64,
        trigger_id: u32,
        expected_map: u32,
        expected_instance: u64,
        controller_generation: u64,
        expected_intent_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            DebugReplaySessionlessAreatriggerArgs {
                character_guid,
                trigger_id,
                expected_map,
                expected_instance,
                controller_generation,
                expected_intent_id,
            },
            callback,
        )
    }
}
