// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DebugVmapAreaInfoArgs {
    pub map: u32,
    pub x: f32,
    pub y: f32,
    pub z: f32,
}

impl From<DebugVmapAreaInfoArgs> for super::Reducer {
    fn from(args: DebugVmapAreaInfoArgs) -> Self {
        Self::DebugVmapAreaInfo {
            map: args.map,
            x: args.x,
            y: args.y,
            z: args.z,
        }
    }
}

impl __sdk::InModule for DebugVmapAreaInfoArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `debug_vmap_area_info`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait debug_vmap_area_info {
    /// Request that the remote module invoke the reducer `debug_vmap_area_info` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`debug_vmap_area_info:debug_vmap_area_info_then`] to run a callback after the reducer completes.
    fn debug_vmap_area_info(&self, map: u32, x: f32, y: f32, z: f32) -> __sdk::Result<()> {
        self.debug_vmap_area_info_then(map, x, y, z, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `debug_vmap_area_info` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn debug_vmap_area_info_then(
        &self,
        map: u32,
        x: f32,
        y: f32,
        z: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl debug_vmap_area_info for super::RemoteReducers {
    fn debug_vmap_area_info_then(
        &self,
        map: u32,
        x: f32,
        y: f32,
        z: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(DebugVmapAreaInfoArgs { map, x, y, z }, callback)
    }
}
