// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DebugUnequipItemArgs {
    pub character_guid: u64,
    pub from_slot: u8,
}

impl From<DebugUnequipItemArgs> for super::Reducer {
    fn from(args: DebugUnequipItemArgs) -> Self {
        Self::DebugUnequipItem {
            character_guid: args.character_guid,
            from_slot: args.from_slot,
        }
    }
}

impl __sdk::InModule for DebugUnequipItemArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `debug_unequip_item`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait debug_unequip_item {
    /// Request that the remote module invoke the reducer `debug_unequip_item` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`debug_unequip_item:debug_unequip_item_then`] to run a callback after the reducer completes.
    fn debug_unequip_item(&self, character_guid: u64, from_slot: u8) -> __sdk::Result<()> {
        self.debug_unequip_item_then(character_guid, from_slot, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `debug_unequip_item` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn debug_unequip_item_then(
        &self,
        character_guid: u64,
        from_slot: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl debug_unequip_item for super::RemoteReducers {
    fn debug_unequip_item_then(
        &self,
        character_guid: u64,
        from_slot: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            DebugUnequipItemArgs {
                character_guid,
                from_slot,
            },
            callback,
        )
    }
}
