// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DebugEncounterEquipArgs {
    pub creature_guid: u64,
    pub main_hand: u32,
    pub off_hand: u32,
    pub ranged: u32,
}

impl From<DebugEncounterEquipArgs> for super::Reducer {
    fn from(args: DebugEncounterEquipArgs) -> Self {
        Self::DebugEncounterEquip {
            creature_guid: args.creature_guid,
            main_hand: args.main_hand,
            off_hand: args.off_hand,
            ranged: args.ranged,
        }
    }
}

impl __sdk::InModule for DebugEncounterEquipArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `debug_encounter_equip`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait debug_encounter_equip {
    /// Request that the remote module invoke the reducer `debug_encounter_equip` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`debug_encounter_equip:debug_encounter_equip_then`] to run a callback after the reducer completes.
    fn debug_encounter_equip(
        &self,
        creature_guid: u64,
        main_hand: u32,
        off_hand: u32,
        ranged: u32,
    ) -> __sdk::Result<()> {
        self.debug_encounter_equip_then(creature_guid, main_hand, off_hand, ranged, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `debug_encounter_equip` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn debug_encounter_equip_then(
        &self,
        creature_guid: u64,
        main_hand: u32,
        off_hand: u32,
        ranged: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl debug_encounter_equip for super::RemoteReducers {
    fn debug_encounter_equip_then(
        &self,
        creature_guid: u64,
        main_hand: u32,
        off_hand: u32,
        ranged: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            DebugEncounterEquipArgs {
                creature_guid,
                main_hand,
                off_hand,
                ranged,
            },
            callback,
        )
    }
}
