// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DebugSeedMailArgs {
    pub recipient_guid: u64,
    pub sender_guid: u64,
    pub subject: String,
    pub body: String,
    pub money: u32,
}

impl From<DebugSeedMailArgs> for super::Reducer {
    fn from(args: DebugSeedMailArgs) -> Self {
        Self::DebugSeedMail {
            recipient_guid: args.recipient_guid,
            sender_guid: args.sender_guid,
            subject: args.subject,
            body: args.body,
            money: args.money,
        }
    }
}

impl __sdk::InModule for DebugSeedMailArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `debug_seed_mail`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait debug_seed_mail {
    /// Request that the remote module invoke the reducer `debug_seed_mail` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`debug_seed_mail:debug_seed_mail_then`] to run a callback after the reducer completes.
    fn debug_seed_mail(
        &self,
        recipient_guid: u64,
        sender_guid: u64,
        subject: String,
        body: String,
        money: u32,
    ) -> __sdk::Result<()> {
        self.debug_seed_mail_then(recipient_guid, sender_guid, subject, body, money, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `debug_seed_mail` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn debug_seed_mail_then(
        &self,
        recipient_guid: u64,
        sender_guid: u64,
        subject: String,
        body: String,
        money: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl debug_seed_mail for super::RemoteReducers {
    fn debug_seed_mail_then(
        &self,
        recipient_guid: u64,
        sender_guid: u64,
        subject: String,
        body: String,
        money: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            DebugSeedMailArgs {
                recipient_guid,
                sender_guid,
                subject,
                body,
                money,
            },
            callback,
        )
    }
}
