// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DebugForcePoolRerollArgs {
    pub pool_id: u32,
    pub gathered_guid: u64,
}

impl From<DebugForcePoolRerollArgs> for super::Reducer {
    fn from(args: DebugForcePoolRerollArgs) -> Self {
        Self::DebugForcePoolReroll {
            pool_id: args.pool_id,
            gathered_guid: args.gathered_guid,
        }
    }
}

impl __sdk::InModule for DebugForcePoolRerollArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `debug_force_pool_reroll`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait debug_force_pool_reroll {
    /// Request that the remote module invoke the reducer `debug_force_pool_reroll` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`debug_force_pool_reroll:debug_force_pool_reroll_then`] to run a callback after the reducer completes.
    fn debug_force_pool_reroll(&self, pool_id: u32, gathered_guid: u64) -> __sdk::Result<()> {
        self.debug_force_pool_reroll_then(pool_id, gathered_guid, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `debug_force_pool_reroll` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn debug_force_pool_reroll_then(
        &self,
        pool_id: u32,
        gathered_guid: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl debug_force_pool_reroll for super::RemoteReducers {
    fn debug_force_pool_reroll_then(
        &self,
        pool_id: u32,
        gathered_guid: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            DebugForcePoolRerollArgs {
                pool_id,
                gathered_guid,
            },
            callback,
        )
    }
}
