// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DebugVmapRayArgs {
    pub map: u32,
    pub x_0: f32,
    pub y_0: f32,
    pub z_0: f32,
    pub x_1: f32,
    pub y_1: f32,
    pub z_1: f32,
}

impl From<DebugVmapRayArgs> for super::Reducer {
    fn from(args: DebugVmapRayArgs) -> Self {
        Self::DebugVmapRay {
            map: args.map,
            x_0: args.x_0,
            y_0: args.y_0,
            z_0: args.z_0,
            x_1: args.x_1,
            y_1: args.y_1,
            z_1: args.z_1,
        }
    }
}

impl __sdk::InModule for DebugVmapRayArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `debug_vmap_ray`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait debug_vmap_ray {
    /// Request that the remote module invoke the reducer `debug_vmap_ray` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`debug_vmap_ray:debug_vmap_ray_then`] to run a callback after the reducer completes.
    fn debug_vmap_ray(
        &self,
        map: u32,
        x_0: f32,
        y_0: f32,
        z_0: f32,
        x_1: f32,
        y_1: f32,
        z_1: f32,
    ) -> __sdk::Result<()> {
        self.debug_vmap_ray_then(map, x_0, y_0, z_0, x_1, y_1, z_1, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `debug_vmap_ray` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn debug_vmap_ray_then(
        &self,
        map: u32,
        x_0: f32,
        y_0: f32,
        z_0: f32,
        x_1: f32,
        y_1: f32,
        z_1: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl debug_vmap_ray for super::RemoteReducers {
    fn debug_vmap_ray_then(
        &self,
        map: u32,
        x_0: f32,
        y_0: f32,
        z_0: f32,
        x_1: f32,
        y_1: f32,
        z_1: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            DebugVmapRayArgs {
                map,
                x_0,
                y_0,
                z_0,
                x_1,
                y_1,
                z_1,
            },
            callback,
        )
    }
}
