// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DebugSeedManaBurnFixtureArgs {}

impl From<DebugSeedManaBurnFixtureArgs> for super::Reducer {
    fn from(args: DebugSeedManaBurnFixtureArgs) -> Self {
        Self::DebugSeedManaBurnFixture
    }
}

impl __sdk::InModule for DebugSeedManaBurnFixtureArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `debug_seed_mana_burn_fixture`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait debug_seed_mana_burn_fixture {
    /// Request that the remote module invoke the reducer `debug_seed_mana_burn_fixture` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`debug_seed_mana_burn_fixture:debug_seed_mana_burn_fixture_then`] to run a callback after the reducer completes.
    fn debug_seed_mana_burn_fixture(&self) -> __sdk::Result<()> {
        self.debug_seed_mana_burn_fixture_then(|_, _| {})
    }

    /// Request that the remote module invoke the reducer `debug_seed_mana_burn_fixture` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn debug_seed_mana_burn_fixture_then(
        &self,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl debug_seed_mana_burn_fixture for super::RemoteReducers {
    fn debug_seed_mana_burn_fixture_then(
        &self,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(DebugSeedManaBurnFixtureArgs {}, callback)
    }
}
