// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DebugSpawnGameobjectArgs {
    pub template_entry: u32,
    pub type_id: u8,
    pub display_id: u32,
    pub data_0: u32,
    pub map_id: u32,
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub data_1: u32,
    pub gather_skill_line: u32,
    pub respawn_secs: u32,
    pub gather_gray: u32,
}

impl From<DebugSpawnGameobjectArgs> for super::Reducer {
    fn from(args: DebugSpawnGameobjectArgs) -> Self {
        Self::DebugSpawnGameobject {
            template_entry: args.template_entry,
            type_id: args.type_id,
            display_id: args.display_id,
            data_0: args.data_0,
            map_id: args.map_id,
            x: args.x,
            y: args.y,
            z: args.z,
            data_1: args.data_1,
            gather_skill_line: args.gather_skill_line,
            respawn_secs: args.respawn_secs,
            gather_gray: args.gather_gray,
        }
    }
}

impl __sdk::InModule for DebugSpawnGameobjectArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `debug_spawn_gameobject`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait debug_spawn_gameobject {
    /// Request that the remote module invoke the reducer `debug_spawn_gameobject` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`debug_spawn_gameobject:debug_spawn_gameobject_then`] to run a callback after the reducer completes.
    fn debug_spawn_gameobject(
        &self,
        template_entry: u32,
        type_id: u8,
        display_id: u32,
        data_0: u32,
        map_id: u32,
        x: f32,
        y: f32,
        z: f32,
        data_1: u32,
        gather_skill_line: u32,
        respawn_secs: u32,
        gather_gray: u32,
    ) -> __sdk::Result<()> {
        self.debug_spawn_gameobject_then(
            template_entry,
            type_id,
            display_id,
            data_0,
            map_id,
            x,
            y,
            z,
            data_1,
            gather_skill_line,
            respawn_secs,
            gather_gray,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `debug_spawn_gameobject` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn debug_spawn_gameobject_then(
        &self,
        template_entry: u32,
        type_id: u8,
        display_id: u32,
        data_0: u32,
        map_id: u32,
        x: f32,
        y: f32,
        z: f32,
        data_1: u32,
        gather_skill_line: u32,
        respawn_secs: u32,
        gather_gray: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl debug_spawn_gameobject for super::RemoteReducers {
    fn debug_spawn_gameobject_then(
        &self,
        template_entry: u32,
        type_id: u8,
        display_id: u32,
        data_0: u32,
        map_id: u32,
        x: f32,
        y: f32,
        z: f32,
        data_1: u32,
        gather_skill_line: u32,
        respawn_secs: u32,
        gather_gray: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            DebugSpawnGameobjectArgs {
                template_entry,
                type_id,
                display_id,
                data_0,
                map_id,
                x,
                y,
                z,
                data_1,
                gather_skill_line,
                respawn_secs,
                gather_gray,
            },
            callback,
        )
    }
}
