// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DebugApplyLethalDamageFloorFixtureArgs {
    pub attacker_guid: u64,
    pub target_guid: u64,
    pub rolled: u32,
}

impl From<DebugApplyLethalDamageFloorFixtureArgs> for super::Reducer {
    fn from(args: DebugApplyLethalDamageFloorFixtureArgs) -> Self {
        Self::DebugApplyLethalDamageFloorFixture {
            attacker_guid: args.attacker_guid,
            target_guid: args.target_guid,
            rolled: args.rolled,
        }
    }
}

impl __sdk::InModule for DebugApplyLethalDamageFloorFixtureArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `debug_apply_lethal_damage_floor_fixture`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait debug_apply_lethal_damage_floor_fixture {
    /// Request that the remote module invoke the reducer `debug_apply_lethal_damage_floor_fixture` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`debug_apply_lethal_damage_floor_fixture:debug_apply_lethal_damage_floor_fixture_then`] to run a callback after the reducer completes.
    fn debug_apply_lethal_damage_floor_fixture(
        &self,
        attacker_guid: u64,
        target_guid: u64,
        rolled: u32,
    ) -> __sdk::Result<()> {
        self.debug_apply_lethal_damage_floor_fixture_then(
            attacker_guid,
            target_guid,
            rolled,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `debug_apply_lethal_damage_floor_fixture` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn debug_apply_lethal_damage_floor_fixture_then(
        &self,
        attacker_guid: u64,
        target_guid: u64,
        rolled: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl debug_apply_lethal_damage_floor_fixture for super::RemoteReducers {
    fn debug_apply_lethal_damage_floor_fixture_then(
        &self,
        attacker_guid: u64,
        target_guid: u64,
        rolled: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            DebugApplyLethalDamageFloorFixtureArgs {
                attacker_guid,
                target_guid,
                rolled,
            },
            callback,
        )
    }
}
