// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DebugEquipWeaponArgs {
    pub character_guid: u64,
    pub item_entry: u32,
}

impl From<DebugEquipWeaponArgs> for super::Reducer {
    fn from(args: DebugEquipWeaponArgs) -> Self {
        Self::DebugEquipWeapon {
            character_guid: args.character_guid,
            item_entry: args.item_entry,
        }
    }
}

impl __sdk::InModule for DebugEquipWeaponArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `debug_equip_weapon`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait debug_equip_weapon {
    /// Request that the remote module invoke the reducer `debug_equip_weapon` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`debug_equip_weapon:debug_equip_weapon_then`] to run a callback after the reducer completes.
    fn debug_equip_weapon(&self, character_guid: u64, item_entry: u32) -> __sdk::Result<()> {
        self.debug_equip_weapon_then(character_guid, item_entry, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `debug_equip_weapon` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn debug_equip_weapon_then(
        &self,
        character_guid: u64,
        item_entry: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl debug_equip_weapon for super::RemoteReducers {
    fn debug_equip_weapon_then(
        &self,
        character_guid: u64,
        item_entry: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            DebugEquipWeaponArgs {
                character_guid,
                item_entry,
            },
            callback,
        )
    }
}
