// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DiscardVmapGenerationArgs {
    pub generation_id: u64,
}

impl From<DiscardVmapGenerationArgs> for super::Reducer {
    fn from(args: DiscardVmapGenerationArgs) -> Self {
        Self::DiscardVmapGeneration {
            generation_id: args.generation_id,
        }
    }
}

impl __sdk::InModule for DiscardVmapGenerationArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `discard_vmap_generation`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait discard_vmap_generation {
    /// Request that the remote module invoke the reducer `discard_vmap_generation` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`discard_vmap_generation:discard_vmap_generation_then`] to run a callback after the reducer completes.
    fn discard_vmap_generation(&self, generation_id: u64) -> __sdk::Result<()> {
        self.discard_vmap_generation_then(generation_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `discard_vmap_generation` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn discard_vmap_generation_then(
        &self,
        generation_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl discard_vmap_generation for super::RemoteReducers {
    fn discard_vmap_generation_then(
        &self,
        generation_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(DiscardVmapGenerationArgs { generation_id }, callback)
    }
}
