// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::taxi_flight_schedule_type::TaxiFlightSchedule;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `game_taxi_flight_schedule`.
///
/// Obtain a handle from the [`GameTaxiFlightScheduleTableAccess::game_taxi_flight_schedule`] method on [`super::RemoteTables`],
/// like `ctx.db.game_taxi_flight_schedule()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_taxi_flight_schedule().on_insert(...)`.
pub struct GameTaxiFlightScheduleTableHandle<'ctx> {
    imp: __sdk::TableHandle<TaxiFlightSchedule>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `game_taxi_flight_schedule`.
pub struct GameTaxiFlightScheduleTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for GameTaxiFlightScheduleTableAccessor {
    type Row = TaxiFlightSchedule;
    type Handle<'db> = GameTaxiFlightScheduleTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.game_taxi_flight_schedule()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `game_taxi_flight_schedule`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GameTaxiFlightScheduleTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GameTaxiFlightScheduleTableHandle`], which mediates access to the table `game_taxi_flight_schedule`.
    fn game_taxi_flight_schedule(&self) -> GameTaxiFlightScheduleTableHandle<'_>;
}

impl GameTaxiFlightScheduleTableAccess for super::RemoteTables {
    fn game_taxi_flight_schedule(&self) -> GameTaxiFlightScheduleTableHandle<'_> {
        GameTaxiFlightScheduleTableHandle {
            imp: self
                .imp
                .get_table::<TaxiFlightSchedule>("game_taxi_flight_schedule"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GameTaxiFlightScheduleInsertCallbackId(__sdk::CallbackId);
pub struct GameTaxiFlightScheduleDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for GameTaxiFlightScheduleTableHandle<'ctx> {
    type Row = TaxiFlightSchedule;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TaxiFlightSchedule> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for GameTaxiFlightScheduleTableHandle<'ctx> {
    type Row = TaxiFlightSchedule;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TaxiFlightSchedule> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GameTaxiFlightScheduleInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameTaxiFlightScheduleInsertCallbackId {
        GameTaxiFlightScheduleInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameTaxiFlightScheduleInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GameTaxiFlightScheduleDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameTaxiFlightScheduleDeleteCallbackId {
        GameTaxiFlightScheduleDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameTaxiFlightScheduleDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for GameTaxiFlightScheduleTableHandle<'ctx> {
    type InsertCallbackId = GameTaxiFlightScheduleInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameTaxiFlightScheduleInsertCallbackId {
        GameTaxiFlightScheduleInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameTaxiFlightScheduleInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for GameTaxiFlightScheduleTableHandle<'ctx> {
    type DeleteCallbackId = GameTaxiFlightScheduleDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameTaxiFlightScheduleDeleteCallbackId {
        GameTaxiFlightScheduleDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameTaxiFlightScheduleDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GameTaxiFlightScheduleUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GameTaxiFlightScheduleTableHandle<'ctx> {
    type UpdateCallbackId = GameTaxiFlightScheduleUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameTaxiFlightScheduleUpdateCallbackId {
        GameTaxiFlightScheduleUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameTaxiFlightScheduleUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for GameTaxiFlightScheduleTableHandle<'ctx> {
    type UpdateCallbackId = GameTaxiFlightScheduleUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameTaxiFlightScheduleUpdateCallbackId {
        GameTaxiFlightScheduleUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameTaxiFlightScheduleUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `scheduled_id` unique index on the table `game_taxi_flight_schedule`,
/// which allows point queries on the field of the same name
/// via the [`GameTaxiFlightScheduleScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_taxi_flight_schedule().scheduled_id().find(...)`.
pub struct GameTaxiFlightScheduleScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TaxiFlightSchedule, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GameTaxiFlightScheduleTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `game_taxi_flight_schedule`.
    pub fn scheduled_id(&self) -> GameTaxiFlightScheduleScheduledIdUnique<'ctx> {
        GameTaxiFlightScheduleScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GameTaxiFlightScheduleScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<TaxiFlightSchedule> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TaxiFlightSchedule>("game_taxi_flight_schedule");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TaxiFlightSchedule>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TaxiFlightSchedule>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TaxiFlightSchedule`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait game_taxi_flight_scheduleQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TaxiFlightSchedule`.
    fn game_taxi_flight_schedule(&self) -> __sdk::__query_builder::Table<TaxiFlightSchedule>;
}

impl game_taxi_flight_scheduleQueryTableAccess for __sdk::QueryTableAccessor {
    fn game_taxi_flight_schedule(&self) -> __sdk::__query_builder::Table<TaxiFlightSchedule> {
        __sdk::__query_builder::Table::new("game_taxi_flight_schedule")
    }
}
