// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::relay_continuation_type::RelayContinuation;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `game_creature_ai_relay_continuation`.
///
/// Obtain a handle from the [`GameCreatureAiRelayContinuationTableAccess::game_creature_ai_relay_continuation`] method on [`super::RemoteTables`],
/// like `ctx.db.game_creature_ai_relay_continuation()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_creature_ai_relay_continuation().on_insert(...)`.
pub struct GameCreatureAiRelayContinuationTableHandle<'ctx> {
    imp: __sdk::TableHandle<RelayContinuation>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `game_creature_ai_relay_continuation`.
pub struct GameCreatureAiRelayContinuationTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for GameCreatureAiRelayContinuationTableAccessor {
    type Row = RelayContinuation;
    type Handle<'db> = GameCreatureAiRelayContinuationTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.game_creature_ai_relay_continuation()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `game_creature_ai_relay_continuation`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GameCreatureAiRelayContinuationTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GameCreatureAiRelayContinuationTableHandle`], which mediates access to the table `game_creature_ai_relay_continuation`.
    fn game_creature_ai_relay_continuation(&self)
        -> GameCreatureAiRelayContinuationTableHandle<'_>;
}

impl GameCreatureAiRelayContinuationTableAccess for super::RemoteTables {
    fn game_creature_ai_relay_continuation(
        &self,
    ) -> GameCreatureAiRelayContinuationTableHandle<'_> {
        GameCreatureAiRelayContinuationTableHandle {
            imp: self
                .imp
                .get_table::<RelayContinuation>("game_creature_ai_relay_continuation"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GameCreatureAiRelayContinuationInsertCallbackId(__sdk::CallbackId);
pub struct GameCreatureAiRelayContinuationDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for GameCreatureAiRelayContinuationTableHandle<'ctx> {
    type Row = RelayContinuation;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RelayContinuation> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for GameCreatureAiRelayContinuationTableHandle<'ctx> {
    type Row = RelayContinuation;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RelayContinuation> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GameCreatureAiRelayContinuationInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameCreatureAiRelayContinuationInsertCallbackId {
        GameCreatureAiRelayContinuationInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameCreatureAiRelayContinuationInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GameCreatureAiRelayContinuationDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameCreatureAiRelayContinuationDeleteCallbackId {
        GameCreatureAiRelayContinuationDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameCreatureAiRelayContinuationDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for GameCreatureAiRelayContinuationTableHandle<'ctx> {
    type InsertCallbackId = GameCreatureAiRelayContinuationInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameCreatureAiRelayContinuationInsertCallbackId {
        GameCreatureAiRelayContinuationInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameCreatureAiRelayContinuationInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for GameCreatureAiRelayContinuationTableHandle<'ctx> {
    type DeleteCallbackId = GameCreatureAiRelayContinuationDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameCreatureAiRelayContinuationDeleteCallbackId {
        GameCreatureAiRelayContinuationDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameCreatureAiRelayContinuationDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GameCreatureAiRelayContinuationUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GameCreatureAiRelayContinuationTableHandle<'ctx> {
    type UpdateCallbackId = GameCreatureAiRelayContinuationUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameCreatureAiRelayContinuationUpdateCallbackId {
        GameCreatureAiRelayContinuationUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameCreatureAiRelayContinuationUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for GameCreatureAiRelayContinuationTableHandle<'ctx> {
    type UpdateCallbackId = GameCreatureAiRelayContinuationUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameCreatureAiRelayContinuationUpdateCallbackId {
        GameCreatureAiRelayContinuationUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameCreatureAiRelayContinuationUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `scheduled_id` unique index on the table `game_creature_ai_relay_continuation`,
/// which allows point queries on the field of the same name
/// via the [`GameCreatureAiRelayContinuationScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_creature_ai_relay_continuation().scheduled_id().find(...)`.
pub struct GameCreatureAiRelayContinuationScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<RelayContinuation, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GameCreatureAiRelayContinuationTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `game_creature_ai_relay_continuation`.
    pub fn scheduled_id(&self) -> GameCreatureAiRelayContinuationScheduledIdUnique<'ctx> {
        GameCreatureAiRelayContinuationScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GameCreatureAiRelayContinuationScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<RelayContinuation> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<RelayContinuation>("game_creature_ai_relay_continuation");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<RelayContinuation>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RelayContinuation>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `RelayContinuation`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait game_creature_ai_relay_continuationQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `RelayContinuation`.
    fn game_creature_ai_relay_continuation(
        &self,
    ) -> __sdk::__query_builder::Table<RelayContinuation>;
}

impl game_creature_ai_relay_continuationQueryTableAccess for __sdk::QueryTableAccessor {
    fn game_creature_ai_relay_continuation(
        &self,
    ) -> __sdk::__query_builder::Table<RelayContinuation> {
        __sdk::__query_builder::Table::new("game_creature_ai_relay_continuation")
    }
}
