// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GamePickpocketLoot {
    pub id: u64,
    pub creature_entry: u32,
    pub item_entry: u32,
    pub chance_bp: u32,
    pub count: u32,
    pub group_id: u32,
    pub quest_only: bool,
}

impl __sdk::InModule for GamePickpocketLoot {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `GamePickpocketLoot`.
///
/// Provides typed access to columns for query building.
pub struct GamePickpocketLootCols {
    pub id: __sdk::__query_builder::Col<GamePickpocketLoot, u64>,
    pub creature_entry: __sdk::__query_builder::Col<GamePickpocketLoot, u32>,
    pub item_entry: __sdk::__query_builder::Col<GamePickpocketLoot, u32>,
    pub chance_bp: __sdk::__query_builder::Col<GamePickpocketLoot, u32>,
    pub count: __sdk::__query_builder::Col<GamePickpocketLoot, u32>,
    pub group_id: __sdk::__query_builder::Col<GamePickpocketLoot, u32>,
    pub quest_only: __sdk::__query_builder::Col<GamePickpocketLoot, bool>,
}

impl __sdk::__query_builder::HasCols for GamePickpocketLoot {
    type Cols = GamePickpocketLootCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GamePickpocketLootCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            creature_entry: __sdk::__query_builder::Col::new(table_name, "creature_entry"),
            item_entry: __sdk::__query_builder::Col::new(table_name, "item_entry"),
            chance_bp: __sdk::__query_builder::Col::new(table_name, "chance_bp"),
            count: __sdk::__query_builder::Col::new(table_name, "count"),
            group_id: __sdk::__query_builder::Col::new(table_name, "group_id"),
            quest_only: __sdk::__query_builder::Col::new(table_name, "quest_only"),
        }
    }
}

/// Indexed column accessor struct for the table `GamePickpocketLoot`.
///
/// Provides typed access to indexed columns for query building.
pub struct GamePickpocketLootIxCols {
    pub creature_entry: __sdk::__query_builder::IxCol<GamePickpocketLoot, u32>,
    pub id: __sdk::__query_builder::IxCol<GamePickpocketLoot, u64>,
}

impl __sdk::__query_builder::HasIxCols for GamePickpocketLoot {
    type IxCols = GamePickpocketLootIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        GamePickpocketLootIxCols {
            creature_entry: __sdk::__query_builder::IxCol::new(table_name, "creature_entry"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for GamePickpocketLoot {}
