// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::gateway_lease_type::GatewayLease;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `game_gateway_lease`.
///
/// Obtain a handle from the [`GameGatewayLeaseTableAccess::game_gateway_lease`] method on [`super::RemoteTables`],
/// like `ctx.db.game_gateway_lease()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_gateway_lease().on_insert(...)`.
pub struct GameGatewayLeaseTableHandle<'ctx> {
    imp: __sdk::TableHandle<GatewayLease>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `game_gateway_lease`.
pub struct GameGatewayLeaseTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for GameGatewayLeaseTableAccessor {
    type Row = GatewayLease;
    type Handle<'db> = GameGatewayLeaseTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.game_gateway_lease()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `game_gateway_lease`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GameGatewayLeaseTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GameGatewayLeaseTableHandle`], which mediates access to the table `game_gateway_lease`.
    fn game_gateway_lease(&self) -> GameGatewayLeaseTableHandle<'_>;
}

impl GameGatewayLeaseTableAccess for super::RemoteTables {
    fn game_gateway_lease(&self) -> GameGatewayLeaseTableHandle<'_> {
        GameGatewayLeaseTableHandle {
            imp: self.imp.get_table::<GatewayLease>("game_gateway_lease"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GameGatewayLeaseInsertCallbackId(__sdk::CallbackId);
pub struct GameGatewayLeaseDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for GameGatewayLeaseTableHandle<'ctx> {
    type Row = GatewayLease;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GatewayLease> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for GameGatewayLeaseTableHandle<'ctx> {
    type Row = GatewayLease;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GatewayLease> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GameGatewayLeaseInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameGatewayLeaseInsertCallbackId {
        GameGatewayLeaseInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameGatewayLeaseInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GameGatewayLeaseDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameGatewayLeaseDeleteCallbackId {
        GameGatewayLeaseDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameGatewayLeaseDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for GameGatewayLeaseTableHandle<'ctx> {
    type InsertCallbackId = GameGatewayLeaseInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameGatewayLeaseInsertCallbackId {
        GameGatewayLeaseInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameGatewayLeaseInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for GameGatewayLeaseTableHandle<'ctx> {
    type DeleteCallbackId = GameGatewayLeaseDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameGatewayLeaseDeleteCallbackId {
        GameGatewayLeaseDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameGatewayLeaseDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GameGatewayLeaseUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GameGatewayLeaseTableHandle<'ctx> {
    type UpdateCallbackId = GameGatewayLeaseUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameGatewayLeaseUpdateCallbackId {
        GameGatewayLeaseUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameGatewayLeaseUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for GameGatewayLeaseTableHandle<'ctx> {
    type UpdateCallbackId = GameGatewayLeaseUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameGatewayLeaseUpdateCallbackId {
        GameGatewayLeaseUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameGatewayLeaseUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `game_gateway_lease`,
/// which allows point queries on the field of the same name
/// via the [`GameGatewayLeaseIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_gateway_lease().id().find(...)`.
pub struct GameGatewayLeaseIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<GatewayLease, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GameGatewayLeaseTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `game_gateway_lease`.
    pub fn id(&self) -> GameGatewayLeaseIdUnique<'ctx> {
        GameGatewayLeaseIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GameGatewayLeaseIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<GatewayLease> {
        self.imp.find(col_val)
    }
}

/// Access to the `identity` unique index on the table `game_gateway_lease`,
/// which allows point queries on the field of the same name
/// via the [`GameGatewayLeaseIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_gateway_lease().identity().find(...)`.
pub struct GameGatewayLeaseIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<GatewayLease, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GameGatewayLeaseTableHandle<'ctx> {
    /// Get a handle on the `identity` unique index on the table `game_gateway_lease`.
    pub fn identity(&self) -> GameGatewayLeaseIdentityUnique<'ctx> {
        GameGatewayLeaseIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GameGatewayLeaseIdentityUnique<'ctx> {
    /// Find the subscribed row whose `identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<GatewayLease> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<GatewayLease>("game_gateway_lease");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
    _table.add_unique_constraint::<__sdk::Identity>("identity", |row| &row.identity);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<GatewayLease>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<GatewayLease>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `GatewayLease`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait game_gateway_leaseQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `GatewayLease`.
    fn game_gateway_lease(&self) -> __sdk::__query_builder::Table<GatewayLease>;
}

impl game_gateway_leaseQueryTableAccess for __sdk::QueryTableAccessor {
    fn game_gateway_lease(&self) -> __sdk::__query_builder::Table<GatewayLease> {
        __sdk::__query_builder::Table::new("game_gateway_lease")
    }
}
