// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::map_region_type::MapRegion;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `game_map_region`.
///
/// Obtain a handle from the [`GameMapRegionTableAccess::game_map_region`] method on [`super::RemoteTables`],
/// like `ctx.db.game_map_region()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_map_region().on_insert(...)`.
pub struct GameMapRegionTableHandle<'ctx> {
    imp: __sdk::TableHandle<MapRegion>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `game_map_region`.
pub struct GameMapRegionTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for GameMapRegionTableAccessor {
    type Row = MapRegion;
    type Handle<'db> = GameMapRegionTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.game_map_region()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `game_map_region`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GameMapRegionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GameMapRegionTableHandle`], which mediates access to the table `game_map_region`.
    fn game_map_region(&self) -> GameMapRegionTableHandle<'_>;
}

impl GameMapRegionTableAccess for super::RemoteTables {
    fn game_map_region(&self) -> GameMapRegionTableHandle<'_> {
        GameMapRegionTableHandle {
            imp: self.imp.get_table::<MapRegion>("game_map_region"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GameMapRegionInsertCallbackId(__sdk::CallbackId);
pub struct GameMapRegionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for GameMapRegionTableHandle<'ctx> {
    type Row = MapRegion;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MapRegion> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for GameMapRegionTableHandle<'ctx> {
    type Row = MapRegion;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MapRegion> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GameMapRegionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameMapRegionInsertCallbackId {
        GameMapRegionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameMapRegionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GameMapRegionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameMapRegionDeleteCallbackId {
        GameMapRegionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameMapRegionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for GameMapRegionTableHandle<'ctx> {
    type InsertCallbackId = GameMapRegionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameMapRegionInsertCallbackId {
        GameMapRegionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameMapRegionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for GameMapRegionTableHandle<'ctx> {
    type DeleteCallbackId = GameMapRegionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameMapRegionDeleteCallbackId {
        GameMapRegionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameMapRegionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GameMapRegionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GameMapRegionTableHandle<'ctx> {
    type UpdateCallbackId = GameMapRegionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameMapRegionUpdateCallbackId {
        GameMapRegionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameMapRegionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for GameMapRegionTableHandle<'ctx> {
    type UpdateCallbackId = GameMapRegionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameMapRegionUpdateCallbackId {
        GameMapRegionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameMapRegionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `key` unique index on the table `game_map_region`,
/// which allows point queries on the field of the same name
/// via the [`GameMapRegionKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_map_region().key().find(...)`.
pub struct GameMapRegionKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MapRegion, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GameMapRegionTableHandle<'ctx> {
    /// Get a handle on the `key` unique index on the table `game_map_region`.
    pub fn key(&self) -> GameMapRegionKeyUnique<'ctx> {
        GameMapRegionKeyUnique {
            imp: self.imp.get_unique_constraint::<u64>("key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GameMapRegionKeyUnique<'ctx> {
    /// Find the subscribed row whose `key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<MapRegion> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MapRegion>("game_map_region");
    _table.add_unique_constraint::<u64>("key", |row| &row.key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MapRegion>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MapRegion>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MapRegion`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait game_map_regionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MapRegion`.
    fn game_map_region(&self) -> __sdk::__query_builder::Table<MapRegion>;
}

impl game_map_regionQueryTableAccess for __sdk::QueryTableAccessor {
    fn game_map_region(&self) -> __sdk::__query_builder::Table<MapRegion> {
        __sdk::__query_builder::Table::new("game_map_region")
    }
}
