// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::npc_text_type::NpcText;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `game_npc_text`.
///
/// Obtain a handle from the [`GameNpcTextTableAccess::game_npc_text`] method on [`super::RemoteTables`],
/// like `ctx.db.game_npc_text()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_npc_text().on_insert(...)`.
pub struct GameNpcTextTableHandle<'ctx> {
    imp: __sdk::TableHandle<NpcText>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `game_npc_text`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GameNpcTextTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GameNpcTextTableHandle`], which mediates access to the table `game_npc_text`.
    fn game_npc_text(&self) -> GameNpcTextTableHandle<'_>;
}

impl GameNpcTextTableAccess for super::RemoteTables {
    fn game_npc_text(&self) -> GameNpcTextTableHandle<'_> {
        GameNpcTextTableHandle {
            imp: self.imp.get_table::<NpcText>("game_npc_text"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GameNpcTextInsertCallbackId(__sdk::CallbackId);
pub struct GameNpcTextDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for GameNpcTextTableHandle<'ctx> {
    type Row = NpcText;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = NpcText> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GameNpcTextInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameNpcTextInsertCallbackId {
        GameNpcTextInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameNpcTextInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GameNpcTextDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameNpcTextDeleteCallbackId {
        GameNpcTextDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameNpcTextDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GameNpcTextUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GameNpcTextTableHandle<'ctx> {
    type UpdateCallbackId = GameNpcTextUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameNpcTextUpdateCallbackId {
        GameNpcTextUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameNpcTextUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `text_id` unique index on the table `game_npc_text`,
/// which allows point queries on the field of the same name
/// via the [`GameNpcTextTextIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_npc_text().text_id().find(...)`.
pub struct GameNpcTextTextIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<NpcText, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GameNpcTextTableHandle<'ctx> {
    /// Get a handle on the `text_id` unique index on the table `game_npc_text`.
    pub fn text_id(&self) -> GameNpcTextTextIdUnique<'ctx> {
        GameNpcTextTextIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("text_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GameNpcTextTextIdUnique<'ctx> {
    /// Find the subscribed row whose `text_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<NpcText> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<NpcText>("game_npc_text");
    _table.add_unique_constraint::<u32>("text_id", |row| &row.text_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<NpcText>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<NpcText>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `NpcText`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait game_npc_textQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `NpcText`.
    fn game_npc_text(&self) -> __sdk::__query_builder::Table<NpcText>;
}

impl game_npc_textQueryTableAccess for __sdk::QueryTableAccessor {
    fn game_npc_text(&self) -> __sdk::__query_builder::Table<NpcText> {
        __sdk::__query_builder::Table::new("game_npc_text")
    }
}
