// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::taunt_lock_type::TauntLock;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `game_taunt_lock`.
///
/// Obtain a handle from the [`GameTauntLockTableAccess::game_taunt_lock`] method on [`super::RemoteTables`],
/// like `ctx.db.game_taunt_lock()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_taunt_lock().on_insert(...)`.
pub struct GameTauntLockTableHandle<'ctx> {
    imp: __sdk::TableHandle<TauntLock>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `game_taunt_lock`.
pub struct GameTauntLockTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for GameTauntLockTableAccessor {
    type Row = TauntLock;
    type Handle<'db> = GameTauntLockTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.game_taunt_lock()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `game_taunt_lock`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GameTauntLockTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GameTauntLockTableHandle`], which mediates access to the table `game_taunt_lock`.
    fn game_taunt_lock(&self) -> GameTauntLockTableHandle<'_>;
}

impl GameTauntLockTableAccess for super::RemoteTables {
    fn game_taunt_lock(&self) -> GameTauntLockTableHandle<'_> {
        GameTauntLockTableHandle {
            imp: self.imp.get_table::<TauntLock>("game_taunt_lock"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GameTauntLockInsertCallbackId(__sdk::CallbackId);
pub struct GameTauntLockDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for GameTauntLockTableHandle<'ctx> {
    type Row = TauntLock;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TauntLock> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for GameTauntLockTableHandle<'ctx> {
    type Row = TauntLock;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TauntLock> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GameTauntLockInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameTauntLockInsertCallbackId {
        GameTauntLockInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameTauntLockInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GameTauntLockDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameTauntLockDeleteCallbackId {
        GameTauntLockDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameTauntLockDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for GameTauntLockTableHandle<'ctx> {
    type InsertCallbackId = GameTauntLockInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameTauntLockInsertCallbackId {
        GameTauntLockInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameTauntLockInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for GameTauntLockTableHandle<'ctx> {
    type DeleteCallbackId = GameTauntLockDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameTauntLockDeleteCallbackId {
        GameTauntLockDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameTauntLockDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GameTauntLockUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GameTauntLockTableHandle<'ctx> {
    type UpdateCallbackId = GameTauntLockUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameTauntLockUpdateCallbackId {
        GameTauntLockUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameTauntLockUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for GameTauntLockTableHandle<'ctx> {
    type UpdateCallbackId = GameTauntLockUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameTauntLockUpdateCallbackId {
        GameTauntLockUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameTauntLockUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `creature_guid` unique index on the table `game_taunt_lock`,
/// which allows point queries on the field of the same name
/// via the [`GameTauntLockCreatureGuidUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_taunt_lock().creature_guid().find(...)`.
pub struct GameTauntLockCreatureGuidUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TauntLock, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GameTauntLockTableHandle<'ctx> {
    /// Get a handle on the `creature_guid` unique index on the table `game_taunt_lock`.
    pub fn creature_guid(&self) -> GameTauntLockCreatureGuidUnique<'ctx> {
        GameTauntLockCreatureGuidUnique {
            imp: self.imp.get_unique_constraint::<u64>("creature_guid"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GameTauntLockCreatureGuidUnique<'ctx> {
    /// Find the subscribed row whose `creature_guid` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<TauntLock> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TauntLock>("game_taunt_lock");
    _table.add_unique_constraint::<u64>("creature_guid", |row| &row.creature_guid);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TauntLock>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TauntLock>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TauntLock`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait game_taunt_lockQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TauntLock`.
    fn game_taunt_lock(&self) -> __sdk::__query_builder::Table<TauntLock>;
}

impl game_taunt_lockQueryTableAccess for __sdk::QueryTableAccessor {
    fn game_taunt_lock(&self) -> __sdk::__query_builder::Table<TauntLock> {
        __sdk::__query_builder::Table::new("game_taunt_lock")
    }
}
