// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::guild_fee_hold_type::GuildFeeHold;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `game_guild_fee_hold`.
///
/// Obtain a handle from the [`GameGuildFeeHoldTableAccess::game_guild_fee_hold`] method on [`super::RemoteTables`],
/// like `ctx.db.game_guild_fee_hold()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_guild_fee_hold().on_insert(...)`.
pub struct GameGuildFeeHoldTableHandle<'ctx> {
    imp: __sdk::TableHandle<GuildFeeHold>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `game_guild_fee_hold`.
pub struct GameGuildFeeHoldTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for GameGuildFeeHoldTableAccessor {
    type Row = GuildFeeHold;
    type Handle<'db> = GameGuildFeeHoldTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.game_guild_fee_hold()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `game_guild_fee_hold`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GameGuildFeeHoldTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GameGuildFeeHoldTableHandle`], which mediates access to the table `game_guild_fee_hold`.
    fn game_guild_fee_hold(&self) -> GameGuildFeeHoldTableHandle<'_>;
}

impl GameGuildFeeHoldTableAccess for super::RemoteTables {
    fn game_guild_fee_hold(&self) -> GameGuildFeeHoldTableHandle<'_> {
        GameGuildFeeHoldTableHandle {
            imp: self.imp.get_table::<GuildFeeHold>("game_guild_fee_hold"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GameGuildFeeHoldInsertCallbackId(__sdk::CallbackId);
pub struct GameGuildFeeHoldDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for GameGuildFeeHoldTableHandle<'ctx> {
    type Row = GuildFeeHold;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GuildFeeHold> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for GameGuildFeeHoldTableHandle<'ctx> {
    type Row = GuildFeeHold;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GuildFeeHold> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GameGuildFeeHoldInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameGuildFeeHoldInsertCallbackId {
        GameGuildFeeHoldInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameGuildFeeHoldInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GameGuildFeeHoldDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameGuildFeeHoldDeleteCallbackId {
        GameGuildFeeHoldDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameGuildFeeHoldDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for GameGuildFeeHoldTableHandle<'ctx> {
    type InsertCallbackId = GameGuildFeeHoldInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameGuildFeeHoldInsertCallbackId {
        GameGuildFeeHoldInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameGuildFeeHoldInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for GameGuildFeeHoldTableHandle<'ctx> {
    type DeleteCallbackId = GameGuildFeeHoldDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameGuildFeeHoldDeleteCallbackId {
        GameGuildFeeHoldDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameGuildFeeHoldDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GameGuildFeeHoldUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GameGuildFeeHoldTableHandle<'ctx> {
    type UpdateCallbackId = GameGuildFeeHoldUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameGuildFeeHoldUpdateCallbackId {
        GameGuildFeeHoldUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameGuildFeeHoldUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for GameGuildFeeHoldTableHandle<'ctx> {
    type UpdateCallbackId = GameGuildFeeHoldUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameGuildFeeHoldUpdateCallbackId {
        GameGuildFeeHoldUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameGuildFeeHoldUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `payer_guid` unique index on the table `game_guild_fee_hold`,
/// which allows point queries on the field of the same name
/// via the [`GameGuildFeeHoldPayerGuidUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_guild_fee_hold().payer_guid().find(...)`.
pub struct GameGuildFeeHoldPayerGuidUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<GuildFeeHold, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GameGuildFeeHoldTableHandle<'ctx> {
    /// Get a handle on the `payer_guid` unique index on the table `game_guild_fee_hold`.
    pub fn payer_guid(&self) -> GameGuildFeeHoldPayerGuidUnique<'ctx> {
        GameGuildFeeHoldPayerGuidUnique {
            imp: self.imp.get_unique_constraint::<u64>("payer_guid"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GameGuildFeeHoldPayerGuidUnique<'ctx> {
    /// Find the subscribed row whose `payer_guid` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<GuildFeeHold> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<GuildFeeHold>("game_guild_fee_hold");
    _table.add_unique_constraint::<u64>("payer_guid", |row| &row.payer_guid);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<GuildFeeHold>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<GuildFeeHold>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `GuildFeeHold`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait game_guild_fee_holdQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `GuildFeeHold`.
    fn game_guild_fee_hold(&self) -> __sdk::__query_builder::Table<GuildFeeHold>;
}

impl game_guild_fee_holdQueryTableAccess for __sdk::QueryTableAccessor {
    fn game_guild_fee_hold(&self) -> __sdk::__query_builder::Table<GuildFeeHold> {
        __sdk::__query_builder::Table::new("game_guild_fee_hold")
    }
}
