// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::faction_template_type::FactionTemplate;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `game_faction_template`.
///
/// Obtain a handle from the [`GameFactionTemplateTableAccess::game_faction_template`] method on [`super::RemoteTables`],
/// like `ctx.db.game_faction_template()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_faction_template().on_insert(...)`.
pub struct GameFactionTemplateTableHandle<'ctx> {
    imp: __sdk::TableHandle<FactionTemplate>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `game_faction_template`.
pub struct GameFactionTemplateTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for GameFactionTemplateTableAccessor {
    type Row = FactionTemplate;
    type Handle<'db> = GameFactionTemplateTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.game_faction_template()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `game_faction_template`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GameFactionTemplateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GameFactionTemplateTableHandle`], which mediates access to the table `game_faction_template`.
    fn game_faction_template(&self) -> GameFactionTemplateTableHandle<'_>;
}

impl GameFactionTemplateTableAccess for super::RemoteTables {
    fn game_faction_template(&self) -> GameFactionTemplateTableHandle<'_> {
        GameFactionTemplateTableHandle {
            imp: self
                .imp
                .get_table::<FactionTemplate>("game_faction_template"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GameFactionTemplateInsertCallbackId(__sdk::CallbackId);
pub struct GameFactionTemplateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for GameFactionTemplateTableHandle<'ctx> {
    type Row = FactionTemplate;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = FactionTemplate> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for GameFactionTemplateTableHandle<'ctx> {
    type Row = FactionTemplate;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = FactionTemplate> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GameFactionTemplateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameFactionTemplateInsertCallbackId {
        GameFactionTemplateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameFactionTemplateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GameFactionTemplateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameFactionTemplateDeleteCallbackId {
        GameFactionTemplateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameFactionTemplateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for GameFactionTemplateTableHandle<'ctx> {
    type InsertCallbackId = GameFactionTemplateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameFactionTemplateInsertCallbackId {
        GameFactionTemplateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameFactionTemplateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for GameFactionTemplateTableHandle<'ctx> {
    type DeleteCallbackId = GameFactionTemplateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameFactionTemplateDeleteCallbackId {
        GameFactionTemplateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameFactionTemplateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GameFactionTemplateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GameFactionTemplateTableHandle<'ctx> {
    type UpdateCallbackId = GameFactionTemplateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameFactionTemplateUpdateCallbackId {
        GameFactionTemplateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameFactionTemplateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for GameFactionTemplateTableHandle<'ctx> {
    type UpdateCallbackId = GameFactionTemplateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameFactionTemplateUpdateCallbackId {
        GameFactionTemplateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameFactionTemplateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `game_faction_template`,
/// which allows point queries on the field of the same name
/// via the [`GameFactionTemplateIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_faction_template().id().find(...)`.
pub struct GameFactionTemplateIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<FactionTemplate, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GameFactionTemplateTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `game_faction_template`.
    pub fn id(&self) -> GameFactionTemplateIdUnique<'ctx> {
        GameFactionTemplateIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GameFactionTemplateIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<FactionTemplate> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<FactionTemplate>("game_faction_template");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<FactionTemplate>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<FactionTemplate>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `FactionTemplate`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait game_faction_templateQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `FactionTemplate`.
    fn game_faction_template(&self) -> __sdk::__query_builder::Table<FactionTemplate>;
}

impl game_faction_templateQueryTableAccess for __sdk::QueryTableAccessor {
    fn game_faction_template(&self) -> __sdk::__query_builder::Table<FactionTemplate> {
        __sdk::__query_builder::Table::new("game_faction_template")
    }
}
