// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GameTaxiNode {
    pub id: u32,
    pub client_node_id: u32,
    pub map_id: u32,
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub name: String,
    pub mount_display_horde: u32,
    pub mount_display_alliance: u32,
}

impl __sdk::InModule for GameTaxiNode {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `GameTaxiNode`.
///
/// Provides typed access to columns for query building.
pub struct GameTaxiNodeCols {
    pub id: __sdk::__query_builder::Col<GameTaxiNode, u32>,
    pub client_node_id: __sdk::__query_builder::Col<GameTaxiNode, u32>,
    pub map_id: __sdk::__query_builder::Col<GameTaxiNode, u32>,
    pub x: __sdk::__query_builder::Col<GameTaxiNode, f32>,
    pub y: __sdk::__query_builder::Col<GameTaxiNode, f32>,
    pub z: __sdk::__query_builder::Col<GameTaxiNode, f32>,
    pub name: __sdk::__query_builder::Col<GameTaxiNode, String>,
    pub mount_display_horde: __sdk::__query_builder::Col<GameTaxiNode, u32>,
    pub mount_display_alliance: __sdk::__query_builder::Col<GameTaxiNode, u32>,
}

impl __sdk::__query_builder::HasCols for GameTaxiNode {
    type Cols = GameTaxiNodeCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GameTaxiNodeCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            client_node_id: __sdk::__query_builder::Col::new(table_name, "client_node_id"),
            map_id: __sdk::__query_builder::Col::new(table_name, "map_id"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            mount_display_horde: __sdk::__query_builder::Col::new(
                table_name,
                "mount_display_horde",
            ),
            mount_display_alliance: __sdk::__query_builder::Col::new(
                table_name,
                "mount_display_alliance",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `GameTaxiNode`.
///
/// Provides typed access to indexed columns for query building.
pub struct GameTaxiNodeIxCols {
    pub client_node_id: __sdk::__query_builder::IxCol<GameTaxiNode, u32>,
    pub id: __sdk::__query_builder::IxCol<GameTaxiNode, u32>,
}

impl __sdk::__query_builder::HasIxCols for GameTaxiNode {
    type IxCols = GameTaxiNodeIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        GameTaxiNodeIxCols {
            client_node_id: __sdk::__query_builder::IxCol::new(table_name, "client_node_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for GameTaxiNode {}
