// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::gossip_menu_profile_type::GossipMenuProfile;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `game_gossip_menu_profile`.
///
/// Obtain a handle from the [`GameGossipMenuProfileTableAccess::game_gossip_menu_profile`] method on [`super::RemoteTables`],
/// like `ctx.db.game_gossip_menu_profile()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_gossip_menu_profile().on_insert(...)`.
pub struct GameGossipMenuProfileTableHandle<'ctx> {
    imp: __sdk::TableHandle<GossipMenuProfile>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `game_gossip_menu_profile`.
pub struct GameGossipMenuProfileTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for GameGossipMenuProfileTableAccessor {
    type Row = GossipMenuProfile;
    type Handle<'db> = GameGossipMenuProfileTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.game_gossip_menu_profile()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `game_gossip_menu_profile`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GameGossipMenuProfileTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GameGossipMenuProfileTableHandle`], which mediates access to the table `game_gossip_menu_profile`.
    fn game_gossip_menu_profile(&self) -> GameGossipMenuProfileTableHandle<'_>;
}

impl GameGossipMenuProfileTableAccess for super::RemoteTables {
    fn game_gossip_menu_profile(&self) -> GameGossipMenuProfileTableHandle<'_> {
        GameGossipMenuProfileTableHandle {
            imp: self
                .imp
                .get_table::<GossipMenuProfile>("game_gossip_menu_profile"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GameGossipMenuProfileInsertCallbackId(__sdk::CallbackId);
pub struct GameGossipMenuProfileDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for GameGossipMenuProfileTableHandle<'ctx> {
    type Row = GossipMenuProfile;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GossipMenuProfile> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for GameGossipMenuProfileTableHandle<'ctx> {
    type Row = GossipMenuProfile;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GossipMenuProfile> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GameGossipMenuProfileInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameGossipMenuProfileInsertCallbackId {
        GameGossipMenuProfileInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameGossipMenuProfileInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GameGossipMenuProfileDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameGossipMenuProfileDeleteCallbackId {
        GameGossipMenuProfileDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameGossipMenuProfileDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for GameGossipMenuProfileTableHandle<'ctx> {
    type InsertCallbackId = GameGossipMenuProfileInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameGossipMenuProfileInsertCallbackId {
        GameGossipMenuProfileInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameGossipMenuProfileInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for GameGossipMenuProfileTableHandle<'ctx> {
    type DeleteCallbackId = GameGossipMenuProfileDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameGossipMenuProfileDeleteCallbackId {
        GameGossipMenuProfileDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameGossipMenuProfileDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GameGossipMenuProfileUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GameGossipMenuProfileTableHandle<'ctx> {
    type UpdateCallbackId = GameGossipMenuProfileUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameGossipMenuProfileUpdateCallbackId {
        GameGossipMenuProfileUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameGossipMenuProfileUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for GameGossipMenuProfileTableHandle<'ctx> {
    type UpdateCallbackId = GameGossipMenuProfileUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameGossipMenuProfileUpdateCallbackId {
        GameGossipMenuProfileUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameGossipMenuProfileUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `menu_id` unique index on the table `game_gossip_menu_profile`,
/// which allows point queries on the field of the same name
/// via the [`GameGossipMenuProfileMenuIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_gossip_menu_profile().menu_id().find(...)`.
pub struct GameGossipMenuProfileMenuIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<GossipMenuProfile, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GameGossipMenuProfileTableHandle<'ctx> {
    /// Get a handle on the `menu_id` unique index on the table `game_gossip_menu_profile`.
    pub fn menu_id(&self) -> GameGossipMenuProfileMenuIdUnique<'ctx> {
        GameGossipMenuProfileMenuIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("menu_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GameGossipMenuProfileMenuIdUnique<'ctx> {
    /// Find the subscribed row whose `menu_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<GossipMenuProfile> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<GossipMenuProfile>("game_gossip_menu_profile");
    _table.add_unique_constraint::<u32>("menu_id", |row| &row.menu_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<GossipMenuProfile>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<GossipMenuProfile>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `GossipMenuProfile`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait game_gossip_menu_profileQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `GossipMenuProfile`.
    fn game_gossip_menu_profile(&self) -> __sdk::__query_builder::Table<GossipMenuProfile>;
}

impl game_gossip_menu_profileQueryTableAccess for __sdk::QueryTableAccessor {
    fn game_gossip_menu_profile(&self) -> __sdk::__query_builder::Table<GossipMenuProfile> {
        __sdk::__query_builder::Table::new("game_gossip_menu_profile")
    }
}
