// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::gateway_lease_reaper_schedule_type::GatewayLeaseReaperSchedule;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `game_gateway_lease_reaper_schedule`.
///
/// Obtain a handle from the [`GameGatewayLeaseReaperScheduleTableAccess::game_gateway_lease_reaper_schedule`] method on [`super::RemoteTables`],
/// like `ctx.db.game_gateway_lease_reaper_schedule()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_gateway_lease_reaper_schedule().on_insert(...)`.
pub struct GameGatewayLeaseReaperScheduleTableHandle<'ctx> {
    imp: __sdk::TableHandle<GatewayLeaseReaperSchedule>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `game_gateway_lease_reaper_schedule`.
pub struct GameGatewayLeaseReaperScheduleTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for GameGatewayLeaseReaperScheduleTableAccessor {
    type Row = GatewayLeaseReaperSchedule;
    type Handle<'db> = GameGatewayLeaseReaperScheduleTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.game_gateway_lease_reaper_schedule()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `game_gateway_lease_reaper_schedule`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GameGatewayLeaseReaperScheduleTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GameGatewayLeaseReaperScheduleTableHandle`], which mediates access to the table `game_gateway_lease_reaper_schedule`.
    fn game_gateway_lease_reaper_schedule(&self) -> GameGatewayLeaseReaperScheduleTableHandle<'_>;
}

impl GameGatewayLeaseReaperScheduleTableAccess for super::RemoteTables {
    fn game_gateway_lease_reaper_schedule(&self) -> GameGatewayLeaseReaperScheduleTableHandle<'_> {
        GameGatewayLeaseReaperScheduleTableHandle {
            imp: self
                .imp
                .get_table::<GatewayLeaseReaperSchedule>("game_gateway_lease_reaper_schedule"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GameGatewayLeaseReaperScheduleInsertCallbackId(__sdk::CallbackId);
pub struct GameGatewayLeaseReaperScheduleDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for GameGatewayLeaseReaperScheduleTableHandle<'ctx> {
    type Row = GatewayLeaseReaperSchedule;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GatewayLeaseReaperSchedule> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for GameGatewayLeaseReaperScheduleTableHandle<'ctx> {
    type Row = GatewayLeaseReaperSchedule;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GatewayLeaseReaperSchedule> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GameGatewayLeaseReaperScheduleInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameGatewayLeaseReaperScheduleInsertCallbackId {
        GameGatewayLeaseReaperScheduleInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameGatewayLeaseReaperScheduleInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GameGatewayLeaseReaperScheduleDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameGatewayLeaseReaperScheduleDeleteCallbackId {
        GameGatewayLeaseReaperScheduleDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameGatewayLeaseReaperScheduleDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for GameGatewayLeaseReaperScheduleTableHandle<'ctx> {
    type InsertCallbackId = GameGatewayLeaseReaperScheduleInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameGatewayLeaseReaperScheduleInsertCallbackId {
        GameGatewayLeaseReaperScheduleInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameGatewayLeaseReaperScheduleInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for GameGatewayLeaseReaperScheduleTableHandle<'ctx> {
    type DeleteCallbackId = GameGatewayLeaseReaperScheduleDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameGatewayLeaseReaperScheduleDeleteCallbackId {
        GameGatewayLeaseReaperScheduleDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameGatewayLeaseReaperScheduleDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GameGatewayLeaseReaperScheduleUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GameGatewayLeaseReaperScheduleTableHandle<'ctx> {
    type UpdateCallbackId = GameGatewayLeaseReaperScheduleUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameGatewayLeaseReaperScheduleUpdateCallbackId {
        GameGatewayLeaseReaperScheduleUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameGatewayLeaseReaperScheduleUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for GameGatewayLeaseReaperScheduleTableHandle<'ctx> {
    type UpdateCallbackId = GameGatewayLeaseReaperScheduleUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameGatewayLeaseReaperScheduleUpdateCallbackId {
        GameGatewayLeaseReaperScheduleUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameGatewayLeaseReaperScheduleUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `scheduled_id` unique index on the table `game_gateway_lease_reaper_schedule`,
/// which allows point queries on the field of the same name
/// via the [`GameGatewayLeaseReaperScheduleScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_gateway_lease_reaper_schedule().scheduled_id().find(...)`.
pub struct GameGatewayLeaseReaperScheduleScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<GatewayLeaseReaperSchedule, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GameGatewayLeaseReaperScheduleTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `game_gateway_lease_reaper_schedule`.
    pub fn scheduled_id(&self) -> GameGatewayLeaseReaperScheduleScheduledIdUnique<'ctx> {
        GameGatewayLeaseReaperScheduleScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GameGatewayLeaseReaperScheduleScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<GatewayLeaseReaperSchedule> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache
        .get_or_make_table::<GatewayLeaseReaperSchedule>("game_gateway_lease_reaper_schedule");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<GatewayLeaseReaperSchedule>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<GatewayLeaseReaperSchedule>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `GatewayLeaseReaperSchedule`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait game_gateway_lease_reaper_scheduleQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `GatewayLeaseReaperSchedule`.
    fn game_gateway_lease_reaper_schedule(
        &self,
    ) -> __sdk::__query_builder::Table<GatewayLeaseReaperSchedule>;
}

impl game_gateway_lease_reaper_scheduleQueryTableAccess for __sdk::QueryTableAccessor {
    fn game_gateway_lease_reaper_schedule(
        &self,
    ) -> __sdk::__query_builder::Table<GatewayLeaseReaperSchedule> {
        __sdk::__query_builder::Table::new("game_gateway_lease_reaper_schedule")
    }
}
