// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::creature_cast_type::CreatureCast;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `game_creature_cast`.
///
/// Obtain a handle from the [`GameCreatureCastTableAccess::game_creature_cast`] method on [`super::RemoteTables`],
/// like `ctx.db.game_creature_cast()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_creature_cast().on_insert(...)`.
pub struct GameCreatureCastTableHandle<'ctx> {
    imp: __sdk::TableHandle<CreatureCast>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `game_creature_cast`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GameCreatureCastTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GameCreatureCastTableHandle`], which mediates access to the table `game_creature_cast`.
    fn game_creature_cast(&self) -> GameCreatureCastTableHandle<'_>;
}

impl GameCreatureCastTableAccess for super::RemoteTables {
    fn game_creature_cast(&self) -> GameCreatureCastTableHandle<'_> {
        GameCreatureCastTableHandle {
            imp: self.imp.get_table::<CreatureCast>("game_creature_cast"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GameCreatureCastInsertCallbackId(__sdk::CallbackId);
pub struct GameCreatureCastDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for GameCreatureCastTableHandle<'ctx> {
    type Row = CreatureCast;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CreatureCast> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GameCreatureCastInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameCreatureCastInsertCallbackId {
        GameCreatureCastInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameCreatureCastInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GameCreatureCastDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameCreatureCastDeleteCallbackId {
        GameCreatureCastDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameCreatureCastDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GameCreatureCastUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GameCreatureCastTableHandle<'ctx> {
    type UpdateCallbackId = GameCreatureCastUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameCreatureCastUpdateCallbackId {
        GameCreatureCastUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameCreatureCastUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `creature_entry` unique index on the table `game_creature_cast`,
/// which allows point queries on the field of the same name
/// via the [`GameCreatureCastCreatureEntryUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_creature_cast().creature_entry().find(...)`.
pub struct GameCreatureCastCreatureEntryUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CreatureCast, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GameCreatureCastTableHandle<'ctx> {
    /// Get a handle on the `creature_entry` unique index on the table `game_creature_cast`.
    pub fn creature_entry(&self) -> GameCreatureCastCreatureEntryUnique<'ctx> {
        GameCreatureCastCreatureEntryUnique {
            imp: self.imp.get_unique_constraint::<u32>("creature_entry"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GameCreatureCastCreatureEntryUnique<'ctx> {
    /// Find the subscribed row whose `creature_entry` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<CreatureCast> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CreatureCast>("game_creature_cast");
    _table.add_unique_constraint::<u32>("creature_entry", |row| &row.creature_entry);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CreatureCast>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CreatureCast>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CreatureCast`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait game_creature_castQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CreatureCast`.
    fn game_creature_cast(&self) -> __sdk::__query_builder::Table<CreatureCast>;
}

impl game_creature_castQueryTableAccess for __sdk::QueryTableAccessor {
    fn game_creature_cast(&self) -> __sdk::__query_builder::Table<CreatureCast> {
        __sdk::__query_builder::Table::new("game_creature_cast")
    }
}
