// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::group_event_type::GroupEvent;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `game_group_event`.
///
/// Obtain a handle from the [`GameGroupEventTableAccess::game_group_event`] method on [`super::RemoteTables`],
/// like `ctx.db.game_group_event()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_group_event().on_insert(...)`.
pub struct GameGroupEventTableHandle<'ctx> {
    imp: __sdk::TableHandle<GroupEvent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `game_group_event`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GameGroupEventTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GameGroupEventTableHandle`], which mediates access to the table `game_group_event`.
    fn game_group_event(&self) -> GameGroupEventTableHandle<'_>;
}

impl GameGroupEventTableAccess for super::RemoteTables {
    fn game_group_event(&self) -> GameGroupEventTableHandle<'_> {
        GameGroupEventTableHandle {
            imp: self.imp.get_table::<GroupEvent>("game_group_event"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GameGroupEventInsertCallbackId(__sdk::CallbackId);
pub struct GameGroupEventDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for GameGroupEventTableHandle<'ctx> {
    type Row = GroupEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GroupEvent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GameGroupEventInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameGroupEventInsertCallbackId {
        GameGroupEventInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameGroupEventInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GameGroupEventDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameGroupEventDeleteCallbackId {
        GameGroupEventDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameGroupEventDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GameGroupEventUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GameGroupEventTableHandle<'ctx> {
    type UpdateCallbackId = GameGroupEventUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameGroupEventUpdateCallbackId {
        GameGroupEventUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameGroupEventUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `game_group_event`,
/// which allows point queries on the field of the same name
/// via the [`GameGroupEventIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_group_event().id().find(...)`.
pub struct GameGroupEventIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<GroupEvent, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GameGroupEventTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `game_group_event`.
    pub fn id(&self) -> GameGroupEventIdUnique<'ctx> {
        GameGroupEventIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GameGroupEventIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<GroupEvent> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<GroupEvent>("game_group_event");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<GroupEvent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<GroupEvent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `GroupEvent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait game_group_eventQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `GroupEvent`.
    fn game_group_event(&self) -> __sdk::__query_builder::Table<GroupEvent>;
}

impl game_group_eventQueryTableAccess for __sdk::QueryTableAccessor {
    fn game_group_event(&self) -> __sdk::__query_builder::Table<GroupEvent> {
        __sdk::__query_builder::Table::new("game_group_event")
    }
}
