// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::createinfo_action_type::CreateinfoAction;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `game_createinfo_action`.
///
/// Obtain a handle from the [`GameCreateinfoActionTableAccess::game_createinfo_action`] method on [`super::RemoteTables`],
/// like `ctx.db.game_createinfo_action()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_createinfo_action().on_insert(...)`.
pub struct GameCreateinfoActionTableHandle<'ctx> {
    imp: __sdk::TableHandle<CreateinfoAction>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `game_createinfo_action`.
pub struct GameCreateinfoActionTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for GameCreateinfoActionTableAccessor {
    type Row = CreateinfoAction;
    type Handle<'db> = GameCreateinfoActionTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.game_createinfo_action()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `game_createinfo_action`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GameCreateinfoActionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GameCreateinfoActionTableHandle`], which mediates access to the table `game_createinfo_action`.
    fn game_createinfo_action(&self) -> GameCreateinfoActionTableHandle<'_>;
}

impl GameCreateinfoActionTableAccess for super::RemoteTables {
    fn game_createinfo_action(&self) -> GameCreateinfoActionTableHandle<'_> {
        GameCreateinfoActionTableHandle {
            imp: self
                .imp
                .get_table::<CreateinfoAction>("game_createinfo_action"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GameCreateinfoActionInsertCallbackId(__sdk::CallbackId);
pub struct GameCreateinfoActionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for GameCreateinfoActionTableHandle<'ctx> {
    type Row = CreateinfoAction;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CreateinfoAction> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for GameCreateinfoActionTableHandle<'ctx> {
    type Row = CreateinfoAction;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CreateinfoAction> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GameCreateinfoActionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameCreateinfoActionInsertCallbackId {
        GameCreateinfoActionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameCreateinfoActionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GameCreateinfoActionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameCreateinfoActionDeleteCallbackId {
        GameCreateinfoActionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameCreateinfoActionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for GameCreateinfoActionTableHandle<'ctx> {
    type InsertCallbackId = GameCreateinfoActionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameCreateinfoActionInsertCallbackId {
        GameCreateinfoActionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameCreateinfoActionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for GameCreateinfoActionTableHandle<'ctx> {
    type DeleteCallbackId = GameCreateinfoActionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameCreateinfoActionDeleteCallbackId {
        GameCreateinfoActionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameCreateinfoActionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GameCreateinfoActionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GameCreateinfoActionTableHandle<'ctx> {
    type UpdateCallbackId = GameCreateinfoActionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameCreateinfoActionUpdateCallbackId {
        GameCreateinfoActionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameCreateinfoActionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for GameCreateinfoActionTableHandle<'ctx> {
    type UpdateCallbackId = GameCreateinfoActionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameCreateinfoActionUpdateCallbackId {
        GameCreateinfoActionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameCreateinfoActionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `row_id` unique index on the table `game_createinfo_action`,
/// which allows point queries on the field of the same name
/// via the [`GameCreateinfoActionRowIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_createinfo_action().row_id().find(...)`.
pub struct GameCreateinfoActionRowIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CreateinfoAction, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GameCreateinfoActionTableHandle<'ctx> {
    /// Get a handle on the `row_id` unique index on the table `game_createinfo_action`.
    pub fn row_id(&self) -> GameCreateinfoActionRowIdUnique<'ctx> {
        GameCreateinfoActionRowIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("row_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GameCreateinfoActionRowIdUnique<'ctx> {
    /// Find the subscribed row whose `row_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<CreateinfoAction> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CreateinfoAction>("game_createinfo_action");
    _table.add_unique_constraint::<u64>("row_id", |row| &row.row_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CreateinfoAction>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CreateinfoAction>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CreateinfoAction`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait game_createinfo_actionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CreateinfoAction`.
    fn game_createinfo_action(&self) -> __sdk::__query_builder::Table<CreateinfoAction>;
}

impl game_createinfo_actionQueryTableAccess for __sdk::QueryTableAccessor {
    fn game_createinfo_action(&self) -> __sdk::__query_builder::Table<CreateinfoAction> {
        __sdk::__query_builder::Table::new("game_createinfo_action")
    }
}
