// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::authored_idle_movement_type::AuthoredIdleMovement;
use super::authored_walking_mode_type::AuthoredWalkingMode;
use super::creature_ai_movement_intent_type::CreatureAiMovementIntent;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `game_creature_ai_movement_intent`.
///
/// Obtain a handle from the [`GameCreatureAiMovementIntentTableAccess::game_creature_ai_movement_intent`] method on [`super::RemoteTables`],
/// like `ctx.db.game_creature_ai_movement_intent()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_creature_ai_movement_intent().on_insert(...)`.
pub struct GameCreatureAiMovementIntentTableHandle<'ctx> {
    imp: __sdk::TableHandle<CreatureAiMovementIntent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `game_creature_ai_movement_intent`.
pub struct GameCreatureAiMovementIntentTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for GameCreatureAiMovementIntentTableAccessor {
    type Row = CreatureAiMovementIntent;
    type Handle<'db> = GameCreatureAiMovementIntentTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.game_creature_ai_movement_intent()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `game_creature_ai_movement_intent`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GameCreatureAiMovementIntentTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GameCreatureAiMovementIntentTableHandle`], which mediates access to the table `game_creature_ai_movement_intent`.
    fn game_creature_ai_movement_intent(&self) -> GameCreatureAiMovementIntentTableHandle<'_>;
}

impl GameCreatureAiMovementIntentTableAccess for super::RemoteTables {
    fn game_creature_ai_movement_intent(&self) -> GameCreatureAiMovementIntentTableHandle<'_> {
        GameCreatureAiMovementIntentTableHandle {
            imp: self
                .imp
                .get_table::<CreatureAiMovementIntent>("game_creature_ai_movement_intent"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GameCreatureAiMovementIntentInsertCallbackId(__sdk::CallbackId);
pub struct GameCreatureAiMovementIntentDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for GameCreatureAiMovementIntentTableHandle<'ctx> {
    type Row = CreatureAiMovementIntent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CreatureAiMovementIntent> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for GameCreatureAiMovementIntentTableHandle<'ctx> {
    type Row = CreatureAiMovementIntent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CreatureAiMovementIntent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GameCreatureAiMovementIntentInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameCreatureAiMovementIntentInsertCallbackId {
        GameCreatureAiMovementIntentInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameCreatureAiMovementIntentInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GameCreatureAiMovementIntentDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameCreatureAiMovementIntentDeleteCallbackId {
        GameCreatureAiMovementIntentDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameCreatureAiMovementIntentDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for GameCreatureAiMovementIntentTableHandle<'ctx> {
    type InsertCallbackId = GameCreatureAiMovementIntentInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameCreatureAiMovementIntentInsertCallbackId {
        GameCreatureAiMovementIntentInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameCreatureAiMovementIntentInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for GameCreatureAiMovementIntentTableHandle<'ctx> {
    type DeleteCallbackId = GameCreatureAiMovementIntentDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameCreatureAiMovementIntentDeleteCallbackId {
        GameCreatureAiMovementIntentDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameCreatureAiMovementIntentDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GameCreatureAiMovementIntentUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GameCreatureAiMovementIntentTableHandle<'ctx> {
    type UpdateCallbackId = GameCreatureAiMovementIntentUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameCreatureAiMovementIntentUpdateCallbackId {
        GameCreatureAiMovementIntentUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameCreatureAiMovementIntentUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for GameCreatureAiMovementIntentTableHandle<'ctx> {
    type UpdateCallbackId = GameCreatureAiMovementIntentUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameCreatureAiMovementIntentUpdateCallbackId {
        GameCreatureAiMovementIntentUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameCreatureAiMovementIntentUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `creature_guid` unique index on the table `game_creature_ai_movement_intent`,
/// which allows point queries on the field of the same name
/// via the [`GameCreatureAiMovementIntentCreatureGuidUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_creature_ai_movement_intent().creature_guid().find(...)`.
pub struct GameCreatureAiMovementIntentCreatureGuidUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CreatureAiMovementIntent, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GameCreatureAiMovementIntentTableHandle<'ctx> {
    /// Get a handle on the `creature_guid` unique index on the table `game_creature_ai_movement_intent`.
    pub fn creature_guid(&self) -> GameCreatureAiMovementIntentCreatureGuidUnique<'ctx> {
        GameCreatureAiMovementIntentCreatureGuidUnique {
            imp: self.imp.get_unique_constraint::<u64>("creature_guid"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GameCreatureAiMovementIntentCreatureGuidUnique<'ctx> {
    /// Find the subscribed row whose `creature_guid` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<CreatureAiMovementIntent> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache
        .get_or_make_table::<CreatureAiMovementIntent>("game_creature_ai_movement_intent");
    _table.add_unique_constraint::<u64>("creature_guid", |row| &row.creature_guid);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CreatureAiMovementIntent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CreatureAiMovementIntent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CreatureAiMovementIntent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait game_creature_ai_movement_intentQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CreatureAiMovementIntent`.
    fn game_creature_ai_movement_intent(
        &self,
    ) -> __sdk::__query_builder::Table<CreatureAiMovementIntent>;
}

impl game_creature_ai_movement_intentQueryTableAccess for __sdk::QueryTableAccessor {
    fn game_creature_ai_movement_intent(
        &self,
    ) -> __sdk::__query_builder::Table<CreatureAiMovementIntent> {
        __sdk::__query_builder::Table::new("game_creature_ai_movement_intent")
    }
}
