// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::pet_command_type::PetCommand;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `game_pet_command`.
///
/// Obtain a handle from the [`GamePetCommandTableAccess::game_pet_command`] method on [`super::RemoteTables`],
/// like `ctx.db.game_pet_command()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_pet_command().on_insert(...)`.
pub struct GamePetCommandTableHandle<'ctx> {
    imp: __sdk::TableHandle<PetCommand>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `game_pet_command`.
pub struct GamePetCommandTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for GamePetCommandTableAccessor {
    type Row = PetCommand;
    type Handle<'db> = GamePetCommandTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.game_pet_command()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `game_pet_command`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GamePetCommandTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GamePetCommandTableHandle`], which mediates access to the table `game_pet_command`.
    fn game_pet_command(&self) -> GamePetCommandTableHandle<'_>;
}

impl GamePetCommandTableAccess for super::RemoteTables {
    fn game_pet_command(&self) -> GamePetCommandTableHandle<'_> {
        GamePetCommandTableHandle {
            imp: self.imp.get_table::<PetCommand>("game_pet_command"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GamePetCommandInsertCallbackId(__sdk::CallbackId);
pub struct GamePetCommandDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for GamePetCommandTableHandle<'ctx> {
    type Row = PetCommand;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PetCommand> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for GamePetCommandTableHandle<'ctx> {
    type Row = PetCommand;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PetCommand> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GamePetCommandInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GamePetCommandInsertCallbackId {
        GamePetCommandInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GamePetCommandInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GamePetCommandDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GamePetCommandDeleteCallbackId {
        GamePetCommandDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GamePetCommandDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for GamePetCommandTableHandle<'ctx> {
    type InsertCallbackId = GamePetCommandInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GamePetCommandInsertCallbackId {
        GamePetCommandInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GamePetCommandInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for GamePetCommandTableHandle<'ctx> {
    type DeleteCallbackId = GamePetCommandDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GamePetCommandDeleteCallbackId {
        GamePetCommandDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GamePetCommandDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GamePetCommandUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GamePetCommandTableHandle<'ctx> {
    type UpdateCallbackId = GamePetCommandUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GamePetCommandUpdateCallbackId {
        GamePetCommandUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GamePetCommandUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for GamePetCommandTableHandle<'ctx> {
    type UpdateCallbackId = GamePetCommandUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GamePetCommandUpdateCallbackId {
        GamePetCommandUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GamePetCommandUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `owner_guid` unique index on the table `game_pet_command`,
/// which allows point queries on the field of the same name
/// via the [`GamePetCommandOwnerGuidUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_pet_command().owner_guid().find(...)`.
pub struct GamePetCommandOwnerGuidUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PetCommand, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GamePetCommandTableHandle<'ctx> {
    /// Get a handle on the `owner_guid` unique index on the table `game_pet_command`.
    pub fn owner_guid(&self) -> GamePetCommandOwnerGuidUnique<'ctx> {
        GamePetCommandOwnerGuidUnique {
            imp: self.imp.get_unique_constraint::<u64>("owner_guid"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GamePetCommandOwnerGuidUnique<'ctx> {
    /// Find the subscribed row whose `owner_guid` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<PetCommand> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PetCommand>("game_pet_command");
    _table.add_unique_constraint::<u64>("owner_guid", |row| &row.owner_guid);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PetCommand>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PetCommand>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PetCommand`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait game_pet_commandQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PetCommand`.
    fn game_pet_command(&self) -> __sdk::__query_builder::Table<PetCommand>;
}

impl game_pet_commandQueryTableAccess for __sdk::QueryTableAccessor {
    fn game_pet_command(&self) -> __sdk::__query_builder::Table<PetCommand> {
        __sdk::__query_builder::Table::new("game_pet_command")
    }
}
