// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::creature_ai_state_type::CreatureAiState;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `game_creature_ai_state`.
///
/// Obtain a handle from the [`GameCreatureAiStateTableAccess::game_creature_ai_state`] method on [`super::RemoteTables`],
/// like `ctx.db.game_creature_ai_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_creature_ai_state().on_insert(...)`.
pub struct GameCreatureAiStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<CreatureAiState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `game_creature_ai_state`.
pub struct GameCreatureAiStateTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for GameCreatureAiStateTableAccessor {
    type Row = CreatureAiState;
    type Handle<'db> = GameCreatureAiStateTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.game_creature_ai_state()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `game_creature_ai_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GameCreatureAiStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GameCreatureAiStateTableHandle`], which mediates access to the table `game_creature_ai_state`.
    fn game_creature_ai_state(&self) -> GameCreatureAiStateTableHandle<'_>;
}

impl GameCreatureAiStateTableAccess for super::RemoteTables {
    fn game_creature_ai_state(&self) -> GameCreatureAiStateTableHandle<'_> {
        GameCreatureAiStateTableHandle {
            imp: self
                .imp
                .get_table::<CreatureAiState>("game_creature_ai_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GameCreatureAiStateInsertCallbackId(__sdk::CallbackId);
pub struct GameCreatureAiStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for GameCreatureAiStateTableHandle<'ctx> {
    type Row = CreatureAiState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CreatureAiState> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for GameCreatureAiStateTableHandle<'ctx> {
    type Row = CreatureAiState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CreatureAiState> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GameCreatureAiStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameCreatureAiStateInsertCallbackId {
        GameCreatureAiStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameCreatureAiStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GameCreatureAiStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameCreatureAiStateDeleteCallbackId {
        GameCreatureAiStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameCreatureAiStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for GameCreatureAiStateTableHandle<'ctx> {
    type InsertCallbackId = GameCreatureAiStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameCreatureAiStateInsertCallbackId {
        GameCreatureAiStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameCreatureAiStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for GameCreatureAiStateTableHandle<'ctx> {
    type DeleteCallbackId = GameCreatureAiStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameCreatureAiStateDeleteCallbackId {
        GameCreatureAiStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameCreatureAiStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GameCreatureAiStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GameCreatureAiStateTableHandle<'ctx> {
    type UpdateCallbackId = GameCreatureAiStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameCreatureAiStateUpdateCallbackId {
        GameCreatureAiStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameCreatureAiStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for GameCreatureAiStateTableHandle<'ctx> {
    type UpdateCallbackId = GameCreatureAiStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameCreatureAiStateUpdateCallbackId {
        GameCreatureAiStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameCreatureAiStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `creature_guid` unique index on the table `game_creature_ai_state`,
/// which allows point queries on the field of the same name
/// via the [`GameCreatureAiStateCreatureGuidUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_creature_ai_state().creature_guid().find(...)`.
pub struct GameCreatureAiStateCreatureGuidUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CreatureAiState, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GameCreatureAiStateTableHandle<'ctx> {
    /// Get a handle on the `creature_guid` unique index on the table `game_creature_ai_state`.
    pub fn creature_guid(&self) -> GameCreatureAiStateCreatureGuidUnique<'ctx> {
        GameCreatureAiStateCreatureGuidUnique {
            imp: self.imp.get_unique_constraint::<u64>("creature_guid"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GameCreatureAiStateCreatureGuidUnique<'ctx> {
    /// Find the subscribed row whose `creature_guid` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<CreatureAiState> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CreatureAiState>("game_creature_ai_state");
    _table.add_unique_constraint::<u64>("creature_guid", |row| &row.creature_guid);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CreatureAiState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CreatureAiState>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CreatureAiState`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait game_creature_ai_stateQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CreatureAiState`.
    fn game_creature_ai_state(&self) -> __sdk::__query_builder::Table<CreatureAiState>;
}

impl game_creature_ai_stateQueryTableAccess for __sdk::QueryTableAccessor {
    fn game_creature_ai_state(&self) -> __sdk::__query_builder::Table<CreatureAiState> {
        __sdk::__query_builder::Table::new("game_creature_ai_state")
    }
}
