// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::creature_ai_definition_type::CreatureAiDefinition;
use super::event_ai_rule_type::EventAiRule;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `game_creature_ai_definition`.
///
/// Obtain a handle from the [`GameCreatureAiDefinitionTableAccess::game_creature_ai_definition`] method on [`super::RemoteTables`],
/// like `ctx.db.game_creature_ai_definition()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_creature_ai_definition().on_insert(...)`.
pub struct GameCreatureAiDefinitionTableHandle<'ctx> {
    imp: __sdk::TableHandle<CreatureAiDefinition>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `game_creature_ai_definition`.
pub struct GameCreatureAiDefinitionTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for GameCreatureAiDefinitionTableAccessor {
    type Row = CreatureAiDefinition;
    type Handle<'db> = GameCreatureAiDefinitionTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.game_creature_ai_definition()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `game_creature_ai_definition`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GameCreatureAiDefinitionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GameCreatureAiDefinitionTableHandle`], which mediates access to the table `game_creature_ai_definition`.
    fn game_creature_ai_definition(&self) -> GameCreatureAiDefinitionTableHandle<'_>;
}

impl GameCreatureAiDefinitionTableAccess for super::RemoteTables {
    fn game_creature_ai_definition(&self) -> GameCreatureAiDefinitionTableHandle<'_> {
        GameCreatureAiDefinitionTableHandle {
            imp: self
                .imp
                .get_table::<CreatureAiDefinition>("game_creature_ai_definition"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GameCreatureAiDefinitionInsertCallbackId(__sdk::CallbackId);
pub struct GameCreatureAiDefinitionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for GameCreatureAiDefinitionTableHandle<'ctx> {
    type Row = CreatureAiDefinition;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CreatureAiDefinition> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for GameCreatureAiDefinitionTableHandle<'ctx> {
    type Row = CreatureAiDefinition;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CreatureAiDefinition> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GameCreatureAiDefinitionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameCreatureAiDefinitionInsertCallbackId {
        GameCreatureAiDefinitionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameCreatureAiDefinitionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GameCreatureAiDefinitionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameCreatureAiDefinitionDeleteCallbackId {
        GameCreatureAiDefinitionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameCreatureAiDefinitionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for GameCreatureAiDefinitionTableHandle<'ctx> {
    type InsertCallbackId = GameCreatureAiDefinitionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameCreatureAiDefinitionInsertCallbackId {
        GameCreatureAiDefinitionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameCreatureAiDefinitionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for GameCreatureAiDefinitionTableHandle<'ctx> {
    type DeleteCallbackId = GameCreatureAiDefinitionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameCreatureAiDefinitionDeleteCallbackId {
        GameCreatureAiDefinitionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameCreatureAiDefinitionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GameCreatureAiDefinitionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GameCreatureAiDefinitionTableHandle<'ctx> {
    type UpdateCallbackId = GameCreatureAiDefinitionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameCreatureAiDefinitionUpdateCallbackId {
        GameCreatureAiDefinitionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameCreatureAiDefinitionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for GameCreatureAiDefinitionTableHandle<'ctx> {
    type UpdateCallbackId = GameCreatureAiDefinitionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameCreatureAiDefinitionUpdateCallbackId {
        GameCreatureAiDefinitionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameCreatureAiDefinitionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `game_creature_ai_definition`,
/// which allows point queries on the field of the same name
/// via the [`GameCreatureAiDefinitionIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_creature_ai_definition().id().find(...)`.
pub struct GameCreatureAiDefinitionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CreatureAiDefinition, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GameCreatureAiDefinitionTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `game_creature_ai_definition`.
    pub fn id(&self) -> GameCreatureAiDefinitionIdUnique<'ctx> {
        GameCreatureAiDefinitionIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GameCreatureAiDefinitionIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<CreatureAiDefinition> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<CreatureAiDefinition>("game_creature_ai_definition");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CreatureAiDefinition>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CreatureAiDefinition>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CreatureAiDefinition`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait game_creature_ai_definitionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CreatureAiDefinition`.
    fn game_creature_ai_definition(&self) -> __sdk::__query_builder::Table<CreatureAiDefinition>;
}

impl game_creature_ai_definitionQueryTableAccess for __sdk::QueryTableAccessor {
    fn game_creature_ai_definition(&self) -> __sdk::__query_builder::Table<CreatureAiDefinition> {
        __sdk::__query_builder::Table::new("game_creature_ai_definition")
    }
}
