// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::aura_schedule_type::AuraSchedule;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `game_aura_schedule`.
///
/// Obtain a handle from the [`GameAuraScheduleTableAccess::game_aura_schedule`] method on [`super::RemoteTables`],
/// like `ctx.db.game_aura_schedule()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_aura_schedule().on_insert(...)`.
pub struct GameAuraScheduleTableHandle<'ctx> {
    imp: __sdk::TableHandle<AuraSchedule>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `game_aura_schedule`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GameAuraScheduleTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GameAuraScheduleTableHandle`], which mediates access to the table `game_aura_schedule`.
    fn game_aura_schedule(&self) -> GameAuraScheduleTableHandle<'_>;
}

impl GameAuraScheduleTableAccess for super::RemoteTables {
    fn game_aura_schedule(&self) -> GameAuraScheduleTableHandle<'_> {
        GameAuraScheduleTableHandle {
            imp: self.imp.get_table::<AuraSchedule>("game_aura_schedule"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GameAuraScheduleInsertCallbackId(__sdk::CallbackId);
pub struct GameAuraScheduleDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for GameAuraScheduleTableHandle<'ctx> {
    type Row = AuraSchedule;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AuraSchedule> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GameAuraScheduleInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameAuraScheduleInsertCallbackId {
        GameAuraScheduleInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameAuraScheduleInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GameAuraScheduleDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameAuraScheduleDeleteCallbackId {
        GameAuraScheduleDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameAuraScheduleDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GameAuraScheduleUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GameAuraScheduleTableHandle<'ctx> {
    type UpdateCallbackId = GameAuraScheduleUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameAuraScheduleUpdateCallbackId {
        GameAuraScheduleUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameAuraScheduleUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `scheduled_id` unique index on the table `game_aura_schedule`,
/// which allows point queries on the field of the same name
/// via the [`GameAuraScheduleScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_aura_schedule().scheduled_id().find(...)`.
pub struct GameAuraScheduleScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<AuraSchedule, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GameAuraScheduleTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `game_aura_schedule`.
    pub fn scheduled_id(&self) -> GameAuraScheduleScheduledIdUnique<'ctx> {
        GameAuraScheduleScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GameAuraScheduleScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<AuraSchedule> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<AuraSchedule>("game_aura_schedule");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<AuraSchedule>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AuraSchedule>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `AuraSchedule`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait game_aura_scheduleQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `AuraSchedule`.
    fn game_aura_schedule(&self) -> __sdk::__query_builder::Table<AuraSchedule>;
}

impl game_aura_scheduleQueryTableAccess for __sdk::QueryTableAccessor {
    fn game_aura_schedule(&self) -> __sdk::__query_builder::Table<AuraSchedule> {
        __sdk::__query_builder::Table::new("game_aura_schedule")
    }
}
