// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::chat_channel_member_type::ChatChannelMember;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `game_chat_channel_member`.
///
/// Obtain a handle from the [`GameChatChannelMemberTableAccess::game_chat_channel_member`] method on [`super::RemoteTables`],
/// like `ctx.db.game_chat_channel_member()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_chat_channel_member().on_insert(...)`.
pub struct GameChatChannelMemberTableHandle<'ctx> {
    imp: __sdk::TableHandle<ChatChannelMember>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `game_chat_channel_member`.
pub struct GameChatChannelMemberTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for GameChatChannelMemberTableAccessor {
    type Row = ChatChannelMember;
    type Handle<'db> = GameChatChannelMemberTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.game_chat_channel_member()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `game_chat_channel_member`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GameChatChannelMemberTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GameChatChannelMemberTableHandle`], which mediates access to the table `game_chat_channel_member`.
    fn game_chat_channel_member(&self) -> GameChatChannelMemberTableHandle<'_>;
}

impl GameChatChannelMemberTableAccess for super::RemoteTables {
    fn game_chat_channel_member(&self) -> GameChatChannelMemberTableHandle<'_> {
        GameChatChannelMemberTableHandle {
            imp: self
                .imp
                .get_table::<ChatChannelMember>("game_chat_channel_member"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GameChatChannelMemberInsertCallbackId(__sdk::CallbackId);
pub struct GameChatChannelMemberDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for GameChatChannelMemberTableHandle<'ctx> {
    type Row = ChatChannelMember;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ChatChannelMember> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for GameChatChannelMemberTableHandle<'ctx> {
    type Row = ChatChannelMember;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ChatChannelMember> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GameChatChannelMemberInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameChatChannelMemberInsertCallbackId {
        GameChatChannelMemberInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameChatChannelMemberInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GameChatChannelMemberDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameChatChannelMemberDeleteCallbackId {
        GameChatChannelMemberDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameChatChannelMemberDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for GameChatChannelMemberTableHandle<'ctx> {
    type InsertCallbackId = GameChatChannelMemberInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameChatChannelMemberInsertCallbackId {
        GameChatChannelMemberInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameChatChannelMemberInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for GameChatChannelMemberTableHandle<'ctx> {
    type DeleteCallbackId = GameChatChannelMemberDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameChatChannelMemberDeleteCallbackId {
        GameChatChannelMemberDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameChatChannelMemberDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GameChatChannelMemberUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GameChatChannelMemberTableHandle<'ctx> {
    type UpdateCallbackId = GameChatChannelMemberUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameChatChannelMemberUpdateCallbackId {
        GameChatChannelMemberUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameChatChannelMemberUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for GameChatChannelMemberTableHandle<'ctx> {
    type UpdateCallbackId = GameChatChannelMemberUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameChatChannelMemberUpdateCallbackId {
        GameChatChannelMemberUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameChatChannelMemberUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `game_chat_channel_member`,
/// which allows point queries on the field of the same name
/// via the [`GameChatChannelMemberIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_chat_channel_member().id().find(...)`.
pub struct GameChatChannelMemberIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ChatChannelMember, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GameChatChannelMemberTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `game_chat_channel_member`.
    pub fn id(&self) -> GameChatChannelMemberIdUnique<'ctx> {
        GameChatChannelMemberIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GameChatChannelMemberIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ChatChannelMember> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ChatChannelMember>("game_chat_channel_member");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ChatChannelMember>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ChatChannelMember>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ChatChannelMember`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait game_chat_channel_memberQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ChatChannelMember`.
    fn game_chat_channel_member(&self) -> __sdk::__query_builder::Table<ChatChannelMember>;
}

impl game_chat_channel_memberQueryTableAccess for __sdk::QueryTableAccessor {
    fn game_chat_channel_member(&self) -> __sdk::__query_builder::Table<ChatChannelMember> {
        __sdk::__query_builder::Table::new("game_chat_channel_member")
    }
}
