// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::mail_arrival_type::MailArrival;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `game_mail_arrival`.
///
/// Obtain a handle from the [`GameMailArrivalTableAccess::game_mail_arrival`] method on [`super::RemoteTables`],
/// like `ctx.db.game_mail_arrival()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_mail_arrival().on_insert(...)`.
pub struct GameMailArrivalTableHandle<'ctx> {
    imp: __sdk::TableHandle<MailArrival>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `game_mail_arrival`.
pub struct GameMailArrivalTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for GameMailArrivalTableAccessor {
    type Row = MailArrival;
    type Handle<'db> = GameMailArrivalTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.game_mail_arrival()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `game_mail_arrival`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GameMailArrivalTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GameMailArrivalTableHandle`], which mediates access to the table `game_mail_arrival`.
    fn game_mail_arrival(&self) -> GameMailArrivalTableHandle<'_>;
}

impl GameMailArrivalTableAccess for super::RemoteTables {
    fn game_mail_arrival(&self) -> GameMailArrivalTableHandle<'_> {
        GameMailArrivalTableHandle {
            imp: self.imp.get_table::<MailArrival>("game_mail_arrival"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GameMailArrivalInsertCallbackId(__sdk::CallbackId);
pub struct GameMailArrivalDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for GameMailArrivalTableHandle<'ctx> {
    type Row = MailArrival;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MailArrival> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for GameMailArrivalTableHandle<'ctx> {
    type Row = MailArrival;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MailArrival> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GameMailArrivalInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameMailArrivalInsertCallbackId {
        GameMailArrivalInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameMailArrivalInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GameMailArrivalDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameMailArrivalDeleteCallbackId {
        GameMailArrivalDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameMailArrivalDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for GameMailArrivalTableHandle<'ctx> {
    type InsertCallbackId = GameMailArrivalInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameMailArrivalInsertCallbackId {
        GameMailArrivalInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameMailArrivalInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for GameMailArrivalTableHandle<'ctx> {
    type DeleteCallbackId = GameMailArrivalDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameMailArrivalDeleteCallbackId {
        GameMailArrivalDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameMailArrivalDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GameMailArrivalUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GameMailArrivalTableHandle<'ctx> {
    type UpdateCallbackId = GameMailArrivalUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameMailArrivalUpdateCallbackId {
        GameMailArrivalUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameMailArrivalUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for GameMailArrivalTableHandle<'ctx> {
    type UpdateCallbackId = GameMailArrivalUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameMailArrivalUpdateCallbackId {
        GameMailArrivalUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameMailArrivalUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `game_mail_arrival`,
/// which allows point queries on the field of the same name
/// via the [`GameMailArrivalIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_mail_arrival().id().find(...)`.
pub struct GameMailArrivalIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MailArrival, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GameMailArrivalTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `game_mail_arrival`.
    pub fn id(&self) -> GameMailArrivalIdUnique<'ctx> {
        GameMailArrivalIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GameMailArrivalIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<MailArrival> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MailArrival>("game_mail_arrival");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MailArrival>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MailArrival>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MailArrival`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait game_mail_arrivalQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MailArrival`.
    fn game_mail_arrival(&self) -> __sdk::__query_builder::Table<MailArrival>;
}

impl game_mail_arrivalQueryTableAccess for __sdk::QueryTableAccessor {
    fn game_mail_arrival(&self) -> __sdk::__query_builder::Table<MailArrival> {
        __sdk::__query_builder::Table::new("game_mail_arrival")
    }
}
