// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::creature_dead_callback_cast_admission_type::CreatureDeadCallbackCastAdmission;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `game_creature_dead_callback_cast_admission`.
///
/// Obtain a handle from the [`GameCreatureDeadCallbackCastAdmissionTableAccess::game_creature_dead_callback_cast_admission`] method on [`super::RemoteTables`],
/// like `ctx.db.game_creature_dead_callback_cast_admission()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_creature_dead_callback_cast_admission().on_insert(...)`.
pub struct GameCreatureDeadCallbackCastAdmissionTableHandle<'ctx> {
    imp: __sdk::TableHandle<CreatureDeadCallbackCastAdmission>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `game_creature_dead_callback_cast_admission`.
pub struct GameCreatureDeadCallbackCastAdmissionTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables>
    for GameCreatureDeadCallbackCastAdmissionTableAccessor
{
    type Row = CreatureDeadCallbackCastAdmission;
    type Handle<'db> = GameCreatureDeadCallbackCastAdmissionTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.game_creature_dead_callback_cast_admission()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `game_creature_dead_callback_cast_admission`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GameCreatureDeadCallbackCastAdmissionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GameCreatureDeadCallbackCastAdmissionTableHandle`], which mediates access to the table `game_creature_dead_callback_cast_admission`.
    fn game_creature_dead_callback_cast_admission(
        &self,
    ) -> GameCreatureDeadCallbackCastAdmissionTableHandle<'_>;
}

impl GameCreatureDeadCallbackCastAdmissionTableAccess for super::RemoteTables {
    fn game_creature_dead_callback_cast_admission(
        &self,
    ) -> GameCreatureDeadCallbackCastAdmissionTableHandle<'_> {
        GameCreatureDeadCallbackCastAdmissionTableHandle {
            imp: self.imp.get_table::<CreatureDeadCallbackCastAdmission>(
                "game_creature_dead_callback_cast_admission",
            ),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GameCreatureDeadCallbackCastAdmissionInsertCallbackId(__sdk::CallbackId);
pub struct GameCreatureDeadCallbackCastAdmissionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for GameCreatureDeadCallbackCastAdmissionTableHandle<'ctx> {
    type Row = CreatureDeadCallbackCastAdmission;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CreatureDeadCallbackCastAdmission> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for GameCreatureDeadCallbackCastAdmissionTableHandle<'ctx> {
    type Row = CreatureDeadCallbackCastAdmission;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CreatureDeadCallbackCastAdmission> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GameCreatureDeadCallbackCastAdmissionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameCreatureDeadCallbackCastAdmissionInsertCallbackId {
        GameCreatureDeadCallbackCastAdmissionInsertCallbackId(
            self.imp.on_insert(Box::new(callback)),
        )
    }

    fn remove_on_insert(&self, callback: GameCreatureDeadCallbackCastAdmissionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GameCreatureDeadCallbackCastAdmissionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameCreatureDeadCallbackCastAdmissionDeleteCallbackId {
        GameCreatureDeadCallbackCastAdmissionDeleteCallbackId(
            self.imp.on_delete(Box::new(callback)),
        )
    }

    fn remove_on_delete(&self, callback: GameCreatureDeadCallbackCastAdmissionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for GameCreatureDeadCallbackCastAdmissionTableHandle<'ctx> {
    type InsertCallbackId = GameCreatureDeadCallbackCastAdmissionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameCreatureDeadCallbackCastAdmissionInsertCallbackId {
        GameCreatureDeadCallbackCastAdmissionInsertCallbackId(
            self.imp.on_insert(Box::new(callback)),
        )
    }

    fn remove_on_insert(&self, callback: GameCreatureDeadCallbackCastAdmissionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for GameCreatureDeadCallbackCastAdmissionTableHandle<'ctx> {
    type DeleteCallbackId = GameCreatureDeadCallbackCastAdmissionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameCreatureDeadCallbackCastAdmissionDeleteCallbackId {
        GameCreatureDeadCallbackCastAdmissionDeleteCallbackId(
            self.imp.on_delete(Box::new(callback)),
        )
    }

    fn remove_on_delete(&self, callback: GameCreatureDeadCallbackCastAdmissionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GameCreatureDeadCallbackCastAdmissionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GameCreatureDeadCallbackCastAdmissionTableHandle<'ctx> {
    type UpdateCallbackId = GameCreatureDeadCallbackCastAdmissionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameCreatureDeadCallbackCastAdmissionUpdateCallbackId {
        GameCreatureDeadCallbackCastAdmissionUpdateCallbackId(
            self.imp.on_update(Box::new(callback)),
        )
    }

    fn remove_on_update(&self, callback: GameCreatureDeadCallbackCastAdmissionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for GameCreatureDeadCallbackCastAdmissionTableHandle<'ctx> {
    type UpdateCallbackId = GameCreatureDeadCallbackCastAdmissionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameCreatureDeadCallbackCastAdmissionUpdateCallbackId {
        GameCreatureDeadCallbackCastAdmissionUpdateCallbackId(
            self.imp.on_update(Box::new(callback)),
        )
    }

    fn remove_on_update(&self, callback: GameCreatureDeadCallbackCastAdmissionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `caster_guid` unique index on the table `game_creature_dead_callback_cast_admission`,
/// which allows point queries on the field of the same name
/// via the [`GameCreatureDeadCallbackCastAdmissionCasterGuidUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_creature_dead_callback_cast_admission().caster_guid().find(...)`.
pub struct GameCreatureDeadCallbackCastAdmissionCasterGuidUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CreatureDeadCallbackCastAdmission, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GameCreatureDeadCallbackCastAdmissionTableHandle<'ctx> {
    /// Get a handle on the `caster_guid` unique index on the table `game_creature_dead_callback_cast_admission`.
    pub fn caster_guid(&self) -> GameCreatureDeadCallbackCastAdmissionCasterGuidUnique<'ctx> {
        GameCreatureDeadCallbackCastAdmissionCasterGuidUnique {
            imp: self.imp.get_unique_constraint::<u64>("caster_guid"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GameCreatureDeadCallbackCastAdmissionCasterGuidUnique<'ctx> {
    /// Find the subscribed row whose `caster_guid` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<CreatureDeadCallbackCastAdmission> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CreatureDeadCallbackCastAdmission>(
        "game_creature_dead_callback_cast_admission",
    );
    _table.add_unique_constraint::<u64>("caster_guid", |row| &row.caster_guid);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CreatureDeadCallbackCastAdmission>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<CreatureDeadCallbackCastAdmission>",
            "TableUpdate",
        )
        .with_cause(e)
        .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CreatureDeadCallbackCastAdmission`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait game_creature_dead_callback_cast_admissionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CreatureDeadCallbackCastAdmission`.
    fn game_creature_dead_callback_cast_admission(
        &self,
    ) -> __sdk::__query_builder::Table<CreatureDeadCallbackCastAdmission>;
}

impl game_creature_dead_callback_cast_admissionQueryTableAccess for __sdk::QueryTableAccessor {
    fn game_creature_dead_callback_cast_admission(
        &self,
    ) -> __sdk::__query_builder::Table<CreatureDeadCallbackCastAdmission> {
        __sdk::__query_builder::Table::new("game_creature_dead_callback_cast_admission")
    }
}
