// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::start_item_type::StartItem;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `game_start_item`.
///
/// Obtain a handle from the [`GameStartItemTableAccess::game_start_item`] method on [`super::RemoteTables`],
/// like `ctx.db.game_start_item()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_start_item().on_insert(...)`.
pub struct GameStartItemTableHandle<'ctx> {
    imp: __sdk::TableHandle<StartItem>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `game_start_item`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GameStartItemTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GameStartItemTableHandle`], which mediates access to the table `game_start_item`.
    fn game_start_item(&self) -> GameStartItemTableHandle<'_>;
}

impl GameStartItemTableAccess for super::RemoteTables {
    fn game_start_item(&self) -> GameStartItemTableHandle<'_> {
        GameStartItemTableHandle {
            imp: self.imp.get_table::<StartItem>("game_start_item"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GameStartItemInsertCallbackId(__sdk::CallbackId);
pub struct GameStartItemDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for GameStartItemTableHandle<'ctx> {
    type Row = StartItem;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = StartItem> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GameStartItemInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameStartItemInsertCallbackId {
        GameStartItemInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameStartItemInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GameStartItemDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameStartItemDeleteCallbackId {
        GameStartItemDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameStartItemDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GameStartItemUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GameStartItemTableHandle<'ctx> {
    type UpdateCallbackId = GameStartItemUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameStartItemUpdateCallbackId {
        GameStartItemUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameStartItemUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `game_start_item`,
/// which allows point queries on the field of the same name
/// via the [`GameStartItemIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_start_item().id().find(...)`.
pub struct GameStartItemIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<StartItem, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GameStartItemTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `game_start_item`.
    pub fn id(&self) -> GameStartItemIdUnique<'ctx> {
        GameStartItemIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GameStartItemIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<StartItem> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<StartItem>("game_start_item");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<StartItem>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<StartItem>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `StartItem`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait game_start_itemQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `StartItem`.
    fn game_start_item(&self) -> __sdk::__query_builder::Table<StartItem>;
}

impl game_start_itemQueryTableAccess for __sdk::QueryTableAccessor {
    fn game_start_item(&self) -> __sdk::__query_builder::Table<StartItem> {
        __sdk::__query_builder::Table::new("game_start_item")
    }
}
