// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::character_away_type::CharacterAway;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `game_character_away`.
///
/// Obtain a handle from the [`GameCharacterAwayTableAccess::game_character_away`] method on [`super::RemoteTables`],
/// like `ctx.db.game_character_away()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_character_away().on_insert(...)`.
pub struct GameCharacterAwayTableHandle<'ctx> {
    imp: __sdk::TableHandle<CharacterAway>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `game_character_away`.
pub struct GameCharacterAwayTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for GameCharacterAwayTableAccessor {
    type Row = CharacterAway;
    type Handle<'db> = GameCharacterAwayTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.game_character_away()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `game_character_away`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GameCharacterAwayTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GameCharacterAwayTableHandle`], which mediates access to the table `game_character_away`.
    fn game_character_away(&self) -> GameCharacterAwayTableHandle<'_>;
}

impl GameCharacterAwayTableAccess for super::RemoteTables {
    fn game_character_away(&self) -> GameCharacterAwayTableHandle<'_> {
        GameCharacterAwayTableHandle {
            imp: self.imp.get_table::<CharacterAway>("game_character_away"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GameCharacterAwayInsertCallbackId(__sdk::CallbackId);
pub struct GameCharacterAwayDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for GameCharacterAwayTableHandle<'ctx> {
    type Row = CharacterAway;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CharacterAway> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for GameCharacterAwayTableHandle<'ctx> {
    type Row = CharacterAway;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CharacterAway> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GameCharacterAwayInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameCharacterAwayInsertCallbackId {
        GameCharacterAwayInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameCharacterAwayInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GameCharacterAwayDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameCharacterAwayDeleteCallbackId {
        GameCharacterAwayDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameCharacterAwayDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for GameCharacterAwayTableHandle<'ctx> {
    type InsertCallbackId = GameCharacterAwayInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameCharacterAwayInsertCallbackId {
        GameCharacterAwayInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameCharacterAwayInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for GameCharacterAwayTableHandle<'ctx> {
    type DeleteCallbackId = GameCharacterAwayDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameCharacterAwayDeleteCallbackId {
        GameCharacterAwayDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameCharacterAwayDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GameCharacterAwayUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GameCharacterAwayTableHandle<'ctx> {
    type UpdateCallbackId = GameCharacterAwayUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameCharacterAwayUpdateCallbackId {
        GameCharacterAwayUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameCharacterAwayUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for GameCharacterAwayTableHandle<'ctx> {
    type UpdateCallbackId = GameCharacterAwayUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameCharacterAwayUpdateCallbackId {
        GameCharacterAwayUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameCharacterAwayUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `character_guid` unique index on the table `game_character_away`,
/// which allows point queries on the field of the same name
/// via the [`GameCharacterAwayCharacterGuidUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_character_away().character_guid().find(...)`.
pub struct GameCharacterAwayCharacterGuidUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CharacterAway, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GameCharacterAwayTableHandle<'ctx> {
    /// Get a handle on the `character_guid` unique index on the table `game_character_away`.
    pub fn character_guid(&self) -> GameCharacterAwayCharacterGuidUnique<'ctx> {
        GameCharacterAwayCharacterGuidUnique {
            imp: self.imp.get_unique_constraint::<u64>("character_guid"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GameCharacterAwayCharacterGuidUnique<'ctx> {
    /// Find the subscribed row whose `character_guid` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<CharacterAway> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CharacterAway>("game_character_away");
    _table.add_unique_constraint::<u64>("character_guid", |row| &row.character_guid);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CharacterAway>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CharacterAway>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CharacterAway`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait game_character_awayQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CharacterAway`.
    fn game_character_away(&self) -> __sdk::__query_builder::Table<CharacterAway>;
}

impl game_character_awayQueryTableAccess for __sdk::QueryTableAccessor {
    fn game_character_away(&self) -> __sdk::__query_builder::Table<CharacterAway> {
        __sdk::__query_builder::Table::new("game_character_away")
    }
}
