// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::relay_concurrency_type::RelayConcurrency;
use super::relay_definition_type::RelayDefinition;
use super::relay_lifetime_type::RelayLifetime;
use super::relay_step_type::RelayStep;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `game_creature_ai_relay_definition`.
///
/// Obtain a handle from the [`GameCreatureAiRelayDefinitionTableAccess::game_creature_ai_relay_definition`] method on [`super::RemoteTables`],
/// like `ctx.db.game_creature_ai_relay_definition()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_creature_ai_relay_definition().on_insert(...)`.
pub struct GameCreatureAiRelayDefinitionTableHandle<'ctx> {
    imp: __sdk::TableHandle<RelayDefinition>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `game_creature_ai_relay_definition`.
pub struct GameCreatureAiRelayDefinitionTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for GameCreatureAiRelayDefinitionTableAccessor {
    type Row = RelayDefinition;
    type Handle<'db> = GameCreatureAiRelayDefinitionTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.game_creature_ai_relay_definition()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `game_creature_ai_relay_definition`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GameCreatureAiRelayDefinitionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GameCreatureAiRelayDefinitionTableHandle`], which mediates access to the table `game_creature_ai_relay_definition`.
    fn game_creature_ai_relay_definition(&self) -> GameCreatureAiRelayDefinitionTableHandle<'_>;
}

impl GameCreatureAiRelayDefinitionTableAccess for super::RemoteTables {
    fn game_creature_ai_relay_definition(&self) -> GameCreatureAiRelayDefinitionTableHandle<'_> {
        GameCreatureAiRelayDefinitionTableHandle {
            imp: self
                .imp
                .get_table::<RelayDefinition>("game_creature_ai_relay_definition"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GameCreatureAiRelayDefinitionInsertCallbackId(__sdk::CallbackId);
pub struct GameCreatureAiRelayDefinitionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for GameCreatureAiRelayDefinitionTableHandle<'ctx> {
    type Row = RelayDefinition;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RelayDefinition> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for GameCreatureAiRelayDefinitionTableHandle<'ctx> {
    type Row = RelayDefinition;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RelayDefinition> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GameCreatureAiRelayDefinitionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameCreatureAiRelayDefinitionInsertCallbackId {
        GameCreatureAiRelayDefinitionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameCreatureAiRelayDefinitionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GameCreatureAiRelayDefinitionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameCreatureAiRelayDefinitionDeleteCallbackId {
        GameCreatureAiRelayDefinitionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameCreatureAiRelayDefinitionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for GameCreatureAiRelayDefinitionTableHandle<'ctx> {
    type InsertCallbackId = GameCreatureAiRelayDefinitionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameCreatureAiRelayDefinitionInsertCallbackId {
        GameCreatureAiRelayDefinitionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameCreatureAiRelayDefinitionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for GameCreatureAiRelayDefinitionTableHandle<'ctx> {
    type DeleteCallbackId = GameCreatureAiRelayDefinitionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameCreatureAiRelayDefinitionDeleteCallbackId {
        GameCreatureAiRelayDefinitionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameCreatureAiRelayDefinitionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GameCreatureAiRelayDefinitionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GameCreatureAiRelayDefinitionTableHandle<'ctx> {
    type UpdateCallbackId = GameCreatureAiRelayDefinitionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameCreatureAiRelayDefinitionUpdateCallbackId {
        GameCreatureAiRelayDefinitionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameCreatureAiRelayDefinitionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for GameCreatureAiRelayDefinitionTableHandle<'ctx> {
    type UpdateCallbackId = GameCreatureAiRelayDefinitionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameCreatureAiRelayDefinitionUpdateCallbackId {
        GameCreatureAiRelayDefinitionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameCreatureAiRelayDefinitionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `game_creature_ai_relay_definition`,
/// which allows point queries on the field of the same name
/// via the [`GameCreatureAiRelayDefinitionIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_creature_ai_relay_definition().id().find(...)`.
pub struct GameCreatureAiRelayDefinitionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<RelayDefinition, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GameCreatureAiRelayDefinitionTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `game_creature_ai_relay_definition`.
    pub fn id(&self) -> GameCreatureAiRelayDefinitionIdUnique<'ctx> {
        GameCreatureAiRelayDefinitionIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GameCreatureAiRelayDefinitionIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<RelayDefinition> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<RelayDefinition>("game_creature_ai_relay_definition");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<RelayDefinition>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RelayDefinition>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `RelayDefinition`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait game_creature_ai_relay_definitionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `RelayDefinition`.
    fn game_creature_ai_relay_definition(&self) -> __sdk::__query_builder::Table<RelayDefinition>;
}

impl game_creature_ai_relay_definitionQueryTableAccess for __sdk::QueryTableAccessor {
    fn game_creature_ai_relay_definition(&self) -> __sdk::__query_builder::Table<RelayDefinition> {
        __sdk::__query_builder::Table::new("game_creature_ai_relay_definition")
    }
}
