// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::creature_spell_type::CreatureSpell;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `game_creature_spell`.
///
/// Obtain a handle from the [`GameCreatureSpellTableAccess::game_creature_spell`] method on [`super::RemoteTables`],
/// like `ctx.db.game_creature_spell()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_creature_spell().on_insert(...)`.
pub struct GameCreatureSpellTableHandle<'ctx> {
    imp: __sdk::TableHandle<CreatureSpell>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `game_creature_spell`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GameCreatureSpellTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GameCreatureSpellTableHandle`], which mediates access to the table `game_creature_spell`.
    fn game_creature_spell(&self) -> GameCreatureSpellTableHandle<'_>;
}

impl GameCreatureSpellTableAccess for super::RemoteTables {
    fn game_creature_spell(&self) -> GameCreatureSpellTableHandle<'_> {
        GameCreatureSpellTableHandle {
            imp: self.imp.get_table::<CreatureSpell>("game_creature_spell"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GameCreatureSpellInsertCallbackId(__sdk::CallbackId);
pub struct GameCreatureSpellDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for GameCreatureSpellTableHandle<'ctx> {
    type Row = CreatureSpell;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CreatureSpell> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GameCreatureSpellInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameCreatureSpellInsertCallbackId {
        GameCreatureSpellInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameCreatureSpellInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GameCreatureSpellDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameCreatureSpellDeleteCallbackId {
        GameCreatureSpellDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameCreatureSpellDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GameCreatureSpellUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GameCreatureSpellTableHandle<'ctx> {
    type UpdateCallbackId = GameCreatureSpellUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameCreatureSpellUpdateCallbackId {
        GameCreatureSpellUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameCreatureSpellUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `game_creature_spell`,
/// which allows point queries on the field of the same name
/// via the [`GameCreatureSpellIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_creature_spell().id().find(...)`.
pub struct GameCreatureSpellIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CreatureSpell, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GameCreatureSpellTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `game_creature_spell`.
    pub fn id(&self) -> GameCreatureSpellIdUnique<'ctx> {
        GameCreatureSpellIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GameCreatureSpellIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<CreatureSpell> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CreatureSpell>("game_creature_spell");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CreatureSpell>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CreatureSpell>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CreatureSpell`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait game_creature_spellQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CreatureSpell`.
    fn game_creature_spell(&self) -> __sdk::__query_builder::Table<CreatureSpell>;
}

impl game_creature_spellQueryTableAccess for __sdk::QueryTableAccessor {
    fn game_creature_spell(&self) -> __sdk::__query_builder::Table<CreatureSpell> {
        __sdk::__query_builder::Table::new("game_creature_spell")
    }
}
