// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::creature_ai_summon_origin_type::CreatureAiSummonOrigin;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `game_creature_ai_summon_origin`.
///
/// Obtain a handle from the [`GameCreatureAiSummonOriginTableAccess::game_creature_ai_summon_origin`] method on [`super::RemoteTables`],
/// like `ctx.db.game_creature_ai_summon_origin()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_creature_ai_summon_origin().on_insert(...)`.
pub struct GameCreatureAiSummonOriginTableHandle<'ctx> {
    imp: __sdk::TableHandle<CreatureAiSummonOrigin>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `game_creature_ai_summon_origin`.
pub struct GameCreatureAiSummonOriginTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for GameCreatureAiSummonOriginTableAccessor {
    type Row = CreatureAiSummonOrigin;
    type Handle<'db> = GameCreatureAiSummonOriginTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.game_creature_ai_summon_origin()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `game_creature_ai_summon_origin`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GameCreatureAiSummonOriginTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GameCreatureAiSummonOriginTableHandle`], which mediates access to the table `game_creature_ai_summon_origin`.
    fn game_creature_ai_summon_origin(&self) -> GameCreatureAiSummonOriginTableHandle<'_>;
}

impl GameCreatureAiSummonOriginTableAccess for super::RemoteTables {
    fn game_creature_ai_summon_origin(&self) -> GameCreatureAiSummonOriginTableHandle<'_> {
        GameCreatureAiSummonOriginTableHandle {
            imp: self
                .imp
                .get_table::<CreatureAiSummonOrigin>("game_creature_ai_summon_origin"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GameCreatureAiSummonOriginInsertCallbackId(__sdk::CallbackId);
pub struct GameCreatureAiSummonOriginDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for GameCreatureAiSummonOriginTableHandle<'ctx> {
    type Row = CreatureAiSummonOrigin;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CreatureAiSummonOrigin> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for GameCreatureAiSummonOriginTableHandle<'ctx> {
    type Row = CreatureAiSummonOrigin;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CreatureAiSummonOrigin> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GameCreatureAiSummonOriginInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameCreatureAiSummonOriginInsertCallbackId {
        GameCreatureAiSummonOriginInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameCreatureAiSummonOriginInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GameCreatureAiSummonOriginDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameCreatureAiSummonOriginDeleteCallbackId {
        GameCreatureAiSummonOriginDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameCreatureAiSummonOriginDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for GameCreatureAiSummonOriginTableHandle<'ctx> {
    type InsertCallbackId = GameCreatureAiSummonOriginInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameCreatureAiSummonOriginInsertCallbackId {
        GameCreatureAiSummonOriginInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameCreatureAiSummonOriginInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for GameCreatureAiSummonOriginTableHandle<'ctx> {
    type DeleteCallbackId = GameCreatureAiSummonOriginDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameCreatureAiSummonOriginDeleteCallbackId {
        GameCreatureAiSummonOriginDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameCreatureAiSummonOriginDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GameCreatureAiSummonOriginUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GameCreatureAiSummonOriginTableHandle<'ctx> {
    type UpdateCallbackId = GameCreatureAiSummonOriginUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameCreatureAiSummonOriginUpdateCallbackId {
        GameCreatureAiSummonOriginUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameCreatureAiSummonOriginUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for GameCreatureAiSummonOriginTableHandle<'ctx> {
    type UpdateCallbackId = GameCreatureAiSummonOriginUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameCreatureAiSummonOriginUpdateCallbackId {
        GameCreatureAiSummonOriginUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameCreatureAiSummonOriginUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `creature_guid` unique index on the table `game_creature_ai_summon_origin`,
/// which allows point queries on the field of the same name
/// via the [`GameCreatureAiSummonOriginCreatureGuidUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_creature_ai_summon_origin().creature_guid().find(...)`.
pub struct GameCreatureAiSummonOriginCreatureGuidUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CreatureAiSummonOrigin, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GameCreatureAiSummonOriginTableHandle<'ctx> {
    /// Get a handle on the `creature_guid` unique index on the table `game_creature_ai_summon_origin`.
    pub fn creature_guid(&self) -> GameCreatureAiSummonOriginCreatureGuidUnique<'ctx> {
        GameCreatureAiSummonOriginCreatureGuidUnique {
            imp: self.imp.get_unique_constraint::<u64>("creature_guid"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GameCreatureAiSummonOriginCreatureGuidUnique<'ctx> {
    /// Find the subscribed row whose `creature_guid` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<CreatureAiSummonOrigin> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<CreatureAiSummonOrigin>("game_creature_ai_summon_origin");
    _table.add_unique_constraint::<u64>("creature_guid", |row| &row.creature_guid);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CreatureAiSummonOrigin>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CreatureAiSummonOrigin>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CreatureAiSummonOrigin`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait game_creature_ai_summon_originQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CreatureAiSummonOrigin`.
    fn game_creature_ai_summon_origin(
        &self,
    ) -> __sdk::__query_builder::Table<CreatureAiSummonOrigin>;
}

impl game_creature_ai_summon_originQueryTableAccess for __sdk::QueryTableAccessor {
    fn game_creature_ai_summon_origin(
        &self,
    ) -> __sdk::__query_builder::Table<CreatureAiSummonOrigin> {
        __sdk::__query_builder::Table::new("game_creature_ai_summon_origin")
    }
}
