// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::bot_invite_intent_type::BotInviteIntent;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `game_bot_invite_intent`.
///
/// Obtain a handle from the [`GameBotInviteIntentTableAccess::game_bot_invite_intent`] method on [`super::RemoteTables`],
/// like `ctx.db.game_bot_invite_intent()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_bot_invite_intent().on_insert(...)`.
pub struct GameBotInviteIntentTableHandle<'ctx> {
    imp: __sdk::TableHandle<BotInviteIntent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `game_bot_invite_intent`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GameBotInviteIntentTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GameBotInviteIntentTableHandle`], which mediates access to the table `game_bot_invite_intent`.
    fn game_bot_invite_intent(&self) -> GameBotInviteIntentTableHandle<'_>;
}

impl GameBotInviteIntentTableAccess for super::RemoteTables {
    fn game_bot_invite_intent(&self) -> GameBotInviteIntentTableHandle<'_> {
        GameBotInviteIntentTableHandle {
            imp: self
                .imp
                .get_table::<BotInviteIntent>("game_bot_invite_intent"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GameBotInviteIntentInsertCallbackId(__sdk::CallbackId);
pub struct GameBotInviteIntentDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for GameBotInviteIntentTableHandle<'ctx> {
    type Row = BotInviteIntent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BotInviteIntent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GameBotInviteIntentInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameBotInviteIntentInsertCallbackId {
        GameBotInviteIntentInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameBotInviteIntentInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GameBotInviteIntentDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameBotInviteIntentDeleteCallbackId {
        GameBotInviteIntentDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameBotInviteIntentDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GameBotInviteIntentUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GameBotInviteIntentTableHandle<'ctx> {
    type UpdateCallbackId = GameBotInviteIntentUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameBotInviteIntentUpdateCallbackId {
        GameBotInviteIntentUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameBotInviteIntentUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `game_bot_invite_intent`,
/// which allows point queries on the field of the same name
/// via the [`GameBotInviteIntentIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_bot_invite_intent().id().find(...)`.
pub struct GameBotInviteIntentIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<BotInviteIntent, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GameBotInviteIntentTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `game_bot_invite_intent`.
    pub fn id(&self) -> GameBotInviteIntentIdUnique<'ctx> {
        GameBotInviteIntentIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GameBotInviteIntentIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<BotInviteIntent> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<BotInviteIntent>("game_bot_invite_intent");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<BotInviteIntent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<BotInviteIntent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `BotInviteIntent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait game_bot_invite_intentQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `BotInviteIntent`.
    fn game_bot_invite_intent(&self) -> __sdk::__query_builder::Table<BotInviteIntent>;
}

impl game_bot_invite_intentQueryTableAccess for __sdk::QueryTableAccessor {
    fn game_bot_invite_intent(&self) -> __sdk::__query_builder::Table<BotInviteIntent> {
        __sdk::__query_builder::Table::new("game_bot_invite_intent")
    }
}
