// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::spell_cast_event_type::SpellCastEvent;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `game_spell_cast_event`.
///
/// Obtain a handle from the [`GameSpellCastEventTableAccess::game_spell_cast_event`] method on [`super::RemoteTables`],
/// like `ctx.db.game_spell_cast_event()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_spell_cast_event().on_insert(...)`.
pub struct GameSpellCastEventTableHandle<'ctx> {
    imp: __sdk::TableHandle<SpellCastEvent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `game_spell_cast_event`.
pub struct GameSpellCastEventTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for GameSpellCastEventTableAccessor {
    type Row = SpellCastEvent;
    type Handle<'db> = GameSpellCastEventTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.game_spell_cast_event()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `game_spell_cast_event`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GameSpellCastEventTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GameSpellCastEventTableHandle`], which mediates access to the table `game_spell_cast_event`.
    fn game_spell_cast_event(&self) -> GameSpellCastEventTableHandle<'_>;
}

impl GameSpellCastEventTableAccess for super::RemoteTables {
    fn game_spell_cast_event(&self) -> GameSpellCastEventTableHandle<'_> {
        GameSpellCastEventTableHandle {
            imp: self
                .imp
                .get_table::<SpellCastEvent>("game_spell_cast_event"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GameSpellCastEventInsertCallbackId(__sdk::CallbackId);
pub struct GameSpellCastEventDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for GameSpellCastEventTableHandle<'ctx> {
    type Row = SpellCastEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SpellCastEvent> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for GameSpellCastEventTableHandle<'ctx> {
    type Row = SpellCastEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SpellCastEvent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GameSpellCastEventInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameSpellCastEventInsertCallbackId {
        GameSpellCastEventInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameSpellCastEventInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GameSpellCastEventDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameSpellCastEventDeleteCallbackId {
        GameSpellCastEventDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameSpellCastEventDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for GameSpellCastEventTableHandle<'ctx> {
    type InsertCallbackId = GameSpellCastEventInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameSpellCastEventInsertCallbackId {
        GameSpellCastEventInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameSpellCastEventInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for GameSpellCastEventTableHandle<'ctx> {
    type DeleteCallbackId = GameSpellCastEventDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameSpellCastEventDeleteCallbackId {
        GameSpellCastEventDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameSpellCastEventDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GameSpellCastEventUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GameSpellCastEventTableHandle<'ctx> {
    type UpdateCallbackId = GameSpellCastEventUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameSpellCastEventUpdateCallbackId {
        GameSpellCastEventUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameSpellCastEventUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for GameSpellCastEventTableHandle<'ctx> {
    type UpdateCallbackId = GameSpellCastEventUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameSpellCastEventUpdateCallbackId {
        GameSpellCastEventUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameSpellCastEventUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `game_spell_cast_event`,
/// which allows point queries on the field of the same name
/// via the [`GameSpellCastEventIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_spell_cast_event().id().find(...)`.
pub struct GameSpellCastEventIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SpellCastEvent, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GameSpellCastEventTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `game_spell_cast_event`.
    pub fn id(&self) -> GameSpellCastEventIdUnique<'ctx> {
        GameSpellCastEventIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GameSpellCastEventIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<SpellCastEvent> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SpellCastEvent>("game_spell_cast_event");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SpellCastEvent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SpellCastEvent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SpellCastEvent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait game_spell_cast_eventQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SpellCastEvent`.
    fn game_spell_cast_event(&self) -> __sdk::__query_builder::Table<SpellCastEvent>;
}

impl game_spell_cast_eventQueryTableAccess for __sdk::QueryTableAccessor {
    fn game_spell_cast_event(&self) -> __sdk::__query_builder::Table<SpellCastEvent> {
        __sdk::__query_builder::Table::new("game_spell_cast_event")
    }
}
