// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GraveyardZone {
    pub row_id: u64,
    pub safe_loc_id: u32,
    pub zone_id: u32,
    pub faction: u32,
}

impl __sdk::InModule for GraveyardZone {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `GraveyardZone`.
///
/// Provides typed access to columns for query building.
pub struct GraveyardZoneCols {
    pub row_id: __sdk::__query_builder::Col<GraveyardZone, u64>,
    pub safe_loc_id: __sdk::__query_builder::Col<GraveyardZone, u32>,
    pub zone_id: __sdk::__query_builder::Col<GraveyardZone, u32>,
    pub faction: __sdk::__query_builder::Col<GraveyardZone, u32>,
}

impl __sdk::__query_builder::HasCols for GraveyardZone {
    type Cols = GraveyardZoneCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GraveyardZoneCols {
            row_id: __sdk::__query_builder::Col::new(table_name, "row_id"),
            safe_loc_id: __sdk::__query_builder::Col::new(table_name, "safe_loc_id"),
            zone_id: __sdk::__query_builder::Col::new(table_name, "zone_id"),
            faction: __sdk::__query_builder::Col::new(table_name, "faction"),
        }
    }
}

/// Indexed column accessor struct for the table `GraveyardZone`.
///
/// Provides typed access to indexed columns for query building.
pub struct GraveyardZoneIxCols {
    pub row_id: __sdk::__query_builder::IxCol<GraveyardZone, u64>,
    pub zone_id: __sdk::__query_builder::IxCol<GraveyardZone, u32>,
}

impl __sdk::__query_builder::HasIxCols for GraveyardZone {
    type IxCols = GraveyardZoneIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        GraveyardZoneIxCols {
            row_id: __sdk::__query_builder::IxCol::new(table_name, "row_id"),
            zone_id: __sdk::__query_builder::IxCol::new(table_name, "zone_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for GraveyardZone {}
