// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GroupInviteArgs {
    pub target_guid: u64,
}

impl From<GroupInviteArgs> for super::Reducer {
    fn from(args: GroupInviteArgs) -> Self {
        Self::GroupInvite {
            target_guid: args.target_guid,
        }
    }
}

impl __sdk::InModule for GroupInviteArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `group_invite`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait group_invite {
    /// Request that the remote module invoke the reducer `group_invite` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`group_invite:group_invite_then`] to run a callback after the reducer completes.
    fn group_invite(&self, target_guid: u64) -> __sdk::Result<()> {
        self.group_invite_then(target_guid, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `group_invite` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn group_invite_then(
        &self,
        target_guid: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl group_invite for super::RemoteReducers {
    fn group_invite_then(
        &self,
        target_guid: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(GroupInviteArgs { target_guid }, callback)
    }
}
