// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GuildEvent {
    pub id: u64,
    pub guild_id: u32,
    pub recipient_guid: u64,
    pub kind: u8,
    pub subject_guid: u64,
    pub other_guid: u64,
    pub strings: Vec<String>,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for GuildEvent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `GuildEvent`.
///
/// Provides typed access to columns for query building.
pub struct GuildEventCols {
    pub id: __sdk::__query_builder::Col<GuildEvent, u64>,
    pub guild_id: __sdk::__query_builder::Col<GuildEvent, u32>,
    pub recipient_guid: __sdk::__query_builder::Col<GuildEvent, u64>,
    pub kind: __sdk::__query_builder::Col<GuildEvent, u8>,
    pub subject_guid: __sdk::__query_builder::Col<GuildEvent, u64>,
    pub other_guid: __sdk::__query_builder::Col<GuildEvent, u64>,
    pub strings: __sdk::__query_builder::Col<GuildEvent, Vec<String>>,
    pub created_at: __sdk::__query_builder::Col<GuildEvent, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for GuildEvent {
    type Cols = GuildEventCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GuildEventCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            guild_id: __sdk::__query_builder::Col::new(table_name, "guild_id"),
            recipient_guid: __sdk::__query_builder::Col::new(table_name, "recipient_guid"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            subject_guid: __sdk::__query_builder::Col::new(table_name, "subject_guid"),
            other_guid: __sdk::__query_builder::Col::new(table_name, "other_guid"),
            strings: __sdk::__query_builder::Col::new(table_name, "strings"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `GuildEvent`.
///
/// Provides typed access to indexed columns for query building.
pub struct GuildEventIxCols {
    pub guild_id: __sdk::__query_builder::IxCol<GuildEvent, u32>,
    pub id: __sdk::__query_builder::IxCol<GuildEvent, u64>,
    pub recipient_guid: __sdk::__query_builder::IxCol<GuildEvent, u64>,
}

impl __sdk::__query_builder::HasIxCols for GuildEvent {
    type IxCols = GuildEventIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        GuildEventIxCols {
            guild_id: __sdk::__query_builder::IxCol::new(table_name, "guild_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            recipient_guid: __sdk::__query_builder::IxCol::new(table_name, "recipient_guid"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for GuildEvent {}
