// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GuildRank {
    pub id: u64,
    pub guild_id: u64,
    pub rank_index: u32,
    pub name: String,
    pub rights: u32,
}

impl __sdk::InModule for GuildRank {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `GuildRank`.
///
/// Provides typed access to columns for query building.
pub struct GuildRankCols {
    pub id: __sdk::__query_builder::Col<GuildRank, u64>,
    pub guild_id: __sdk::__query_builder::Col<GuildRank, u64>,
    pub rank_index: __sdk::__query_builder::Col<GuildRank, u32>,
    pub name: __sdk::__query_builder::Col<GuildRank, String>,
    pub rights: __sdk::__query_builder::Col<GuildRank, u32>,
}

impl __sdk::__query_builder::HasCols for GuildRank {
    type Cols = GuildRankCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GuildRankCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            guild_id: __sdk::__query_builder::Col::new(table_name, "guild_id"),
            rank_index: __sdk::__query_builder::Col::new(table_name, "rank_index"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            rights: __sdk::__query_builder::Col::new(table_name, "rights"),
        }
    }
}

/// Indexed column accessor struct for the table `GuildRank`.
///
/// Provides typed access to indexed columns for query building.
pub struct GuildRankIxCols {
    pub guild_id: __sdk::__query_builder::IxCol<GuildRank, u64>,
    pub id: __sdk::__query_builder::IxCol<GuildRank, u64>,
}

impl __sdk::__query_builder::HasIxCols for GuildRank {
    type IxCols = GuildRankIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        GuildRankIxCols {
            guild_id: __sdk::__query_builder::IxCol::new(table_name, "guild_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for GuildRank {}
