// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GwAuctionHoldBidArgs {
    pub operation_id: u64,
    pub bidder_guid: u64,
    pub auctioneer_guid: u64,
    pub auction_id: u32,
    pub house: u32,
    pub offer: u32,
}

impl From<GwAuctionHoldBidArgs> for super::Reducer {
    fn from(args: GwAuctionHoldBidArgs) -> Self {
        Self::GwAuctionHoldBid {
            operation_id: args.operation_id,
            bidder_guid: args.bidder_guid,
            auctioneer_guid: args.auctioneer_guid,
            auction_id: args.auction_id,
            house: args.house,
            offer: args.offer,
        }
    }
}

impl __sdk::InModule for GwAuctionHoldBidArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `gw_auction_hold_bid`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait gw_auction_hold_bid {
    /// Request that the remote module invoke the reducer `gw_auction_hold_bid` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`gw_auction_hold_bid:gw_auction_hold_bid_then`] to run a callback after the reducer completes.
    fn gw_auction_hold_bid(
        &self,
        operation_id: u64,
        bidder_guid: u64,
        auctioneer_guid: u64,
        auction_id: u32,
        house: u32,
        offer: u32,
    ) -> __sdk::Result<()> {
        self.gw_auction_hold_bid_then(
            operation_id,
            bidder_guid,
            auctioneer_guid,
            auction_id,
            house,
            offer,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `gw_auction_hold_bid` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn gw_auction_hold_bid_then(
        &self,
        operation_id: u64,
        bidder_guid: u64,
        auctioneer_guid: u64,
        auction_id: u32,
        house: u32,
        offer: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl gw_auction_hold_bid for super::RemoteReducers {
    fn gw_auction_hold_bid_then(
        &self,
        operation_id: u64,
        bidder_guid: u64,
        auctioneer_guid: u64,
        auction_id: u32,
        house: u32,
        offer: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            GwAuctionHoldBidArgs {
                operation_id,
                bidder_guid,
                auctioneer_guid,
                auction_id,
                house,
                offer,
            },
            callback,
        )
    }
}
