// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GwCastItemTargetArgs {
    pub actor_guid: u64,
    pub spell_id: u32,
    pub slot: u8,
}

impl From<GwCastItemTargetArgs> for super::Reducer {
    fn from(args: GwCastItemTargetArgs) -> Self {
        Self::GwCastItemTarget {
            actor_guid: args.actor_guid,
            spell_id: args.spell_id,
            slot: args.slot,
        }
    }
}

impl __sdk::InModule for GwCastItemTargetArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
pub trait gw_cast_item_target {
    fn gw_cast_item_target(&self, actor_guid: u64, spell_id: u32, slot: u8) -> __sdk::Result<()> {
        self.gw_cast_item_target_then(actor_guid, spell_id, slot, |_, _| {})
    }

    fn gw_cast_item_target_then(
        &self,
        actor_guid: u64,
        spell_id: u32,
        slot: u8,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl gw_cast_item_target for super::RemoteReducers {
    fn gw_cast_item_target_then(
        &self,
        actor_guid: u64,
        spell_id: u32,
        slot: u8,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            GwCastItemTargetArgs {
                actor_guid,
                spell_id,
                slot,
            },
            callback,
        )
    }
}
