// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GwDuelAcceptArgs {
    pub actor_guid: u64,
    pub flag_guid: u64,
}

impl From<GwDuelAcceptArgs> for super::Reducer {
    fn from(args: GwDuelAcceptArgs) -> Self {
        Self::GwDuelAccept {
            actor_guid: args.actor_guid,
            flag_guid: args.flag_guid,
        }
    }
}

impl __sdk::InModule for GwDuelAcceptArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `gw_duel_accept`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait gw_duel_accept {
    /// Request that the remote module invoke the reducer `gw_duel_accept` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`gw_duel_accept:gw_duel_accept_then`] to run a callback after the reducer completes.
    fn gw_duel_accept(&self, actor_guid: u64, flag_guid: u64) -> __sdk::Result<()> {
        self.gw_duel_accept_then(actor_guid, flag_guid, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `gw_duel_accept` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn gw_duel_accept_then(
        &self,
        actor_guid: u64,
        flag_guid: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl gw_duel_accept for super::RemoteReducers {
    fn gw_duel_accept_then(
        &self,
        actor_guid: u64,
        flag_guid: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            GwDuelAcceptArgs {
                actor_guid,
                flag_guid,
            },
            callback,
        )
    }
}
