// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GwPlayerLoginArgs {
    pub account_id: u64,
    pub character_guid: u64,
}

impl From<GwPlayerLoginArgs> for super::Reducer {
    fn from(args: GwPlayerLoginArgs) -> Self {
        Self::GwPlayerLogin {
            account_id: args.account_id,
            character_guid: args.character_guid,
        }
    }
}

impl __sdk::InModule for GwPlayerLoginArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `gw_player_login`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait gw_player_login {
    /// Request that the remote module invoke the reducer `gw_player_login` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`gw_player_login:gw_player_login_then`] to run a callback after the reducer completes.
    fn gw_player_login(&self, account_id: u64, character_guid: u64) -> __sdk::Result<()> {
        self.gw_player_login_then(account_id, character_guid, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `gw_player_login` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn gw_player_login_then(
        &self,
        account_id: u64,
        character_guid: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl gw_player_login for super::RemoteReducers {
    fn gw_player_login_then(
        &self,
        account_id: u64,
        character_guid: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            GwPlayerLoginArgs {
                account_id,
                character_guid,
            },
            callback,
        )
    }
}
