// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::session_actor_type::SessionActor;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GwSetTradeItemArgs {
    pub request_actor: SessionActor,
    pub trade_slot: u8,
    pub inv_slot: u8,
}

impl From<GwSetTradeItemArgs> for super::Reducer {
    fn from(args: GwSetTradeItemArgs) -> Self {
        Self::GwSetTradeItem {
            request_actor: args.request_actor,
            trade_slot: args.trade_slot,
            inv_slot: args.inv_slot,
        }
    }
}

impl __sdk::InModule for GwSetTradeItemArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `gw_set_trade_item`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait gw_set_trade_item {
    /// Request that the remote module invoke the reducer `gw_set_trade_item` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`gw_set_trade_item:gw_set_trade_item_then`] to run a callback after the reducer completes.
    fn gw_set_trade_item(
        &self,
        request_actor: SessionActor,
        trade_slot: u8,
        inv_slot: u8,
    ) -> __sdk::Result<()> {
        self.gw_set_trade_item_then(request_actor, trade_slot, inv_slot, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `gw_set_trade_item` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn gw_set_trade_item_then(
        &self,
        request_actor: SessionActor,
        trade_slot: u8,
        inv_slot: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl gw_set_trade_item for super::RemoteReducers {
    fn gw_set_trade_item_then(
        &self,
        request_actor: SessionActor,
        trade_slot: u8,
        inv_slot: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            GwSetTradeItemArgs {
                request_actor,
                trade_slot,
                inv_slot,
            },
            callback,
        )
    }
}
