// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::session_actor_type::SessionActor;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GwSetTradeGoldArgs {
    pub request_actor: SessionActor,
    pub copper: u32,
}

impl From<GwSetTradeGoldArgs> for super::Reducer {
    fn from(args: GwSetTradeGoldArgs) -> Self {
        Self::GwSetTradeGold {
            request_actor: args.request_actor,
            copper: args.copper,
        }
    }
}

impl __sdk::InModule for GwSetTradeGoldArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `gw_set_trade_gold`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait gw_set_trade_gold {
    /// Request that the remote module invoke the reducer `gw_set_trade_gold` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`gw_set_trade_gold:gw_set_trade_gold_then`] to run a callback after the reducer completes.
    fn gw_set_trade_gold(&self, request_actor: SessionActor, copper: u32) -> __sdk::Result<()> {
        self.gw_set_trade_gold_then(request_actor, copper, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `gw_set_trade_gold` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn gw_set_trade_gold_then(
        &self,
        request_actor: SessionActor,
        copper: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl gw_set_trade_gold for super::RemoteReducers {
    fn gw_set_trade_gold_then(
        &self,
        request_actor: SessionActor,
        copper: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            GwSetTradeGoldArgs {
                request_actor,
                copper,
            },
            callback,
        )
    }
}
