// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct InstallGuidRangeArgs {
    pub base: u64,
}

impl From<InstallGuidRangeArgs> for super::Reducer {
    fn from(args: InstallGuidRangeArgs) -> Self {
        Self::InstallGuidRange { base: args.base }
    }
}

impl __sdk::InModule for InstallGuidRangeArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `install_guid_range`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait install_guid_range {
    /// Request that the remote module invoke the reducer `install_guid_range` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`install_guid_range:install_guid_range_then`] to run a callback after the reducer completes.
    fn install_guid_range(&self, base: u64) -> __sdk::Result<()> {
        self.install_guid_range_then(base, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `install_guid_range` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn install_guid_range_then(
        &self,
        base: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl install_guid_range for super::RemoteReducers {
    fn install_guid_range_then(
        &self,
        base: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(InstallGuidRangeArgs { base }, callback)
    }
}
