// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct NavChunk {
    pub key: u64,
    pub map_id: u32,
    pub cell_x: u16,
    pub cell_y: u16,
    pub base_z: f32,
    pub walk: Vec<u8>,
    pub obs: Vec<u8>,
}

impl __sdk::InModule for NavChunk {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `NavChunk`.
///
/// Provides typed access to columns for query building.
pub struct NavChunkCols {
    pub key: __sdk::__query_builder::Col<NavChunk, u64>,
    pub map_id: __sdk::__query_builder::Col<NavChunk, u32>,
    pub cell_x: __sdk::__query_builder::Col<NavChunk, u16>,
    pub cell_y: __sdk::__query_builder::Col<NavChunk, u16>,
    pub base_z: __sdk::__query_builder::Col<NavChunk, f32>,
    pub walk: __sdk::__query_builder::Col<NavChunk, Vec<u8>>,
    pub obs: __sdk::__query_builder::Col<NavChunk, Vec<u8>>,
}

impl __sdk::__query_builder::HasCols for NavChunk {
    type Cols = NavChunkCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        NavChunkCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            map_id: __sdk::__query_builder::Col::new(table_name, "map_id"),
            cell_x: __sdk::__query_builder::Col::new(table_name, "cell_x"),
            cell_y: __sdk::__query_builder::Col::new(table_name, "cell_y"),
            base_z: __sdk::__query_builder::Col::new(table_name, "base_z"),
            walk: __sdk::__query_builder::Col::new(table_name, "walk"),
            obs: __sdk::__query_builder::Col::new(table_name, "obs"),
        }
    }
}

/// Indexed column accessor struct for the table `NavChunk`.
///
/// Provides typed access to indexed columns for query building.
pub struct NavChunkIxCols {
    pub key: __sdk::__query_builder::IxCol<NavChunk, u64>,
}

impl __sdk::__query_builder::HasIxCols for NavChunk {
    type IxCols = NavChunkIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        NavChunkIxCols {
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for NavChunk {}
