// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct NavigationInputs {
    pub imported_revision: Option<u64>,
    pub navigation_enabled: bool,
    pub collision_enabled: bool,
    pub coverage_enabled: bool,
    pub static_generation: Option<u64>,
    pub coverage_generation: Option<u64>,
}

impl __sdk::InModule for NavigationInputs {
    type Module = super::RemoteModule;
}
