// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct NavigationRevision {
    pub id: u8,
    pub revision: u64,
}

impl __sdk::InModule for NavigationRevision {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `NavigationRevision`.
///
/// Provides typed access to columns for query building.
pub struct NavigationRevisionCols {
    pub id: __sdk::__query_builder::Col<NavigationRevision, u8>,
    pub revision: __sdk::__query_builder::Col<NavigationRevision, u64>,
}

impl __sdk::__query_builder::HasCols for NavigationRevision {
    type Cols = NavigationRevisionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        NavigationRevisionCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            revision: __sdk::__query_builder::Col::new(table_name, "revision"),
        }
    }
}

/// Indexed column accessor struct for the table `NavigationRevision`.
///
/// Provides typed access to indexed columns for query building.
pub struct NavigationRevisionIxCols {
    pub id: __sdk::__query_builder::IxCol<NavigationRevision, u8>,
}

impl __sdk::__query_builder::HasIxCols for NavigationRevision {
    type IxCols = NavigationRevisionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        NavigationRevisionIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for NavigationRevision {}
