// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PkgExampleSeedNoteArgs {
    pub character_guid: u64,
    pub note: String,
}

impl From<PkgExampleSeedNoteArgs> for super::Reducer {
    fn from(args: PkgExampleSeedNoteArgs) -> Self {
        Self::PkgExampleSeedNote {
            character_guid: args.character_guid,
            note: args.note,
        }
    }
}

impl __sdk::InModule for PkgExampleSeedNoteArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `pkg_example_seed_note`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait pkg_example_seed_note {
    /// Request that the remote module invoke the reducer `pkg_example_seed_note` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`pkg_example_seed_note:pkg_example_seed_note_then`] to run a callback after the reducer completes.
    fn pkg_example_seed_note(&self, character_guid: u64, note: String) -> __sdk::Result<()> {
        self.pkg_example_seed_note_then(character_guid, note, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `pkg_example_seed_note` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn pkg_example_seed_note_then(
        &self,
        character_guid: u64,
        note: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl pkg_example_seed_note for super::RemoteReducers {
    fn pkg_example_seed_note_then(
        &self,
        character_guid: u64,
        note: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            PkgExampleSeedNoteArgs {
                character_guid,
                note,
            },
            callback,
        )
    }
}
