// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PlayerbotsSpawnArgs {
    pub count: u32,
    pub x: f32,
    pub y: f32,
    pub z: f32,
}

impl From<PlayerbotsSpawnArgs> for super::Reducer {
    fn from(args: PlayerbotsSpawnArgs) -> Self {
        Self::PlayerbotsSpawn {
            count: args.count,
            x: args.x,
            y: args.y,
            z: args.z,
        }
    }
}

impl __sdk::InModule for PlayerbotsSpawnArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `playerbots_spawn`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait playerbots_spawn {
    /// Request that the remote module invoke the reducer `playerbots_spawn` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`playerbots_spawn:playerbots_spawn_then`] to run a callback after the reducer completes.
    fn playerbots_spawn(&self, count: u32, x: f32, y: f32, z: f32) -> __sdk::Result<()> {
        self.playerbots_spawn_then(count, x, y, z, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `playerbots_spawn` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn playerbots_spawn_then(
        &self,
        count: u32,
        x: f32,
        y: f32,
        z: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl playerbots_spawn for super::RemoteReducers {
    fn playerbots_spawn_then(
        &self,
        count: u32,
        x: f32,
        y: f32,
        z: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(PlayerbotsSpawnArgs { count, x, y, z }, callback)
    }
}
