// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct QuestTemplate {
    pub entry: u32,
    pub min_level: u32,
    pub quest_level: u32,
    pub title: String,
    pub reward_money: u32,
    pub reward_xp: u32,
    pub prev_quest_id: u32,
    pub required_races: u32,
    pub required_classes: u32,
    pub zone_or_sort: i32,
    pub rew_rep_faction_1: u32,
    pub rew_rep_value_1: i32,
    pub rew_rep_faction_2: u32,
    pub rew_rep_value_2: i32,
    pub src_item: u32,
    pub src_item_count: u32,
    pub repeatable: bool,
    pub next_quest_id: u32,
    pub limit_time: u32,
    pub reward_money_max_level: u32,
}

impl __sdk::InModule for QuestTemplate {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `QuestTemplate`.
///
/// Provides typed access to columns for query building.
pub struct QuestTemplateCols {
    pub entry: __sdk::__query_builder::Col<QuestTemplate, u32>,
    pub min_level: __sdk::__query_builder::Col<QuestTemplate, u32>,
    pub quest_level: __sdk::__query_builder::Col<QuestTemplate, u32>,
    pub title: __sdk::__query_builder::Col<QuestTemplate, String>,
    pub reward_money: __sdk::__query_builder::Col<QuestTemplate, u32>,
    pub reward_xp: __sdk::__query_builder::Col<QuestTemplate, u32>,
    pub prev_quest_id: __sdk::__query_builder::Col<QuestTemplate, u32>,
    pub required_races: __sdk::__query_builder::Col<QuestTemplate, u32>,
    pub required_classes: __sdk::__query_builder::Col<QuestTemplate, u32>,
    pub zone_or_sort: __sdk::__query_builder::Col<QuestTemplate, i32>,
    pub rew_rep_faction_1: __sdk::__query_builder::Col<QuestTemplate, u32>,
    pub rew_rep_value_1: __sdk::__query_builder::Col<QuestTemplate, i32>,
    pub rew_rep_faction_2: __sdk::__query_builder::Col<QuestTemplate, u32>,
    pub rew_rep_value_2: __sdk::__query_builder::Col<QuestTemplate, i32>,
    pub src_item: __sdk::__query_builder::Col<QuestTemplate, u32>,
    pub src_item_count: __sdk::__query_builder::Col<QuestTemplate, u32>,
    pub repeatable: __sdk::__query_builder::Col<QuestTemplate, bool>,
    pub next_quest_id: __sdk::__query_builder::Col<QuestTemplate, u32>,
    pub limit_time: __sdk::__query_builder::Col<QuestTemplate, u32>,
    pub reward_money_max_level: __sdk::__query_builder::Col<QuestTemplate, u32>,
}

impl __sdk::__query_builder::HasCols for QuestTemplate {
    type Cols = QuestTemplateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        QuestTemplateCols {
            entry: __sdk::__query_builder::Col::new(table_name, "entry"),
            min_level: __sdk::__query_builder::Col::new(table_name, "min_level"),
            quest_level: __sdk::__query_builder::Col::new(table_name, "quest_level"),
            title: __sdk::__query_builder::Col::new(table_name, "title"),
            reward_money: __sdk::__query_builder::Col::new(table_name, "reward_money"),
            reward_xp: __sdk::__query_builder::Col::new(table_name, "reward_xp"),
            prev_quest_id: __sdk::__query_builder::Col::new(table_name, "prev_quest_id"),
            required_races: __sdk::__query_builder::Col::new(table_name, "required_races"),
            required_classes: __sdk::__query_builder::Col::new(table_name, "required_classes"),
            zone_or_sort: __sdk::__query_builder::Col::new(table_name, "zone_or_sort"),
            rew_rep_faction_1: __sdk::__query_builder::Col::new(table_name, "rew_rep_faction_1"),
            rew_rep_value_1: __sdk::__query_builder::Col::new(table_name, "rew_rep_value_1"),
            rew_rep_faction_2: __sdk::__query_builder::Col::new(table_name, "rew_rep_faction_2"),
            rew_rep_value_2: __sdk::__query_builder::Col::new(table_name, "rew_rep_value_2"),
            src_item: __sdk::__query_builder::Col::new(table_name, "src_item"),
            src_item_count: __sdk::__query_builder::Col::new(table_name, "src_item_count"),
            repeatable: __sdk::__query_builder::Col::new(table_name, "repeatable"),
            next_quest_id: __sdk::__query_builder::Col::new(table_name, "next_quest_id"),
            limit_time: __sdk::__query_builder::Col::new(table_name, "limit_time"),
            reward_money_max_level: __sdk::__query_builder::Col::new(
                table_name,
                "reward_money_max_level",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `QuestTemplate`.
///
/// Provides typed access to indexed columns for query building.
pub struct QuestTemplateIxCols {
    pub entry: __sdk::__query_builder::IxCol<QuestTemplate, u32>,
}

impl __sdk::__query_builder::HasIxCols for QuestTemplate {
    type IxCols = QuestTemplateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        QuestTemplateIxCols {
            entry: __sdk::__query_builder::IxCol::new(table_name, "entry"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for QuestTemplate {}
