// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct QuestRewardItem {
    pub id: u64,
    pub quest_entry: u32,
    pub item_entry: u32,
    pub count: u32,
}

impl __sdk::InModule for QuestRewardItem {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `QuestRewardItem`.
///
/// Provides typed access to columns for query building.
pub struct QuestRewardItemCols {
    pub id: __sdk::__query_builder::Col<QuestRewardItem, u64>,
    pub quest_entry: __sdk::__query_builder::Col<QuestRewardItem, u32>,
    pub item_entry: __sdk::__query_builder::Col<QuestRewardItem, u32>,
    pub count: __sdk::__query_builder::Col<QuestRewardItem, u32>,
}

impl __sdk::__query_builder::HasCols for QuestRewardItem {
    type Cols = QuestRewardItemCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        QuestRewardItemCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            quest_entry: __sdk::__query_builder::Col::new(table_name, "quest_entry"),
            item_entry: __sdk::__query_builder::Col::new(table_name, "item_entry"),
            count: __sdk::__query_builder::Col::new(table_name, "count"),
        }
    }
}

/// Indexed column accessor struct for the table `QuestRewardItem`.
///
/// Provides typed access to indexed columns for query building.
pub struct QuestRewardItemIxCols {
    pub id: __sdk::__query_builder::IxCol<QuestRewardItem, u64>,
    pub quest_entry: __sdk::__query_builder::IxCol<QuestRewardItem, u32>,
}

impl __sdk::__query_builder::HasIxCols for QuestRewardItem {
    type IxCols = QuestRewardItemIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        QuestRewardItemIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            quest_entry: __sdk::__query_builder::IxCol::new(table_name, "quest_entry"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for QuestRewardItem {}
