// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RealmAuctionRefundBidArgs {
    pub operation_id: u64,
    pub bidder_guid: u64,
    pub auction_id: u32,
    pub offer: u32,
    pub deferred_refund: u32,
}

impl From<RealmAuctionRefundBidArgs> for super::Reducer {
    fn from(args: RealmAuctionRefundBidArgs) -> Self {
        Self::RealmAuctionRefundBid {
            operation_id: args.operation_id,
            bidder_guid: args.bidder_guid,
            auction_id: args.auction_id,
            offer: args.offer,
            deferred_refund: args.deferred_refund,
        }
    }
}

impl __sdk::InModule for RealmAuctionRefundBidArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `realm_auction_refund_bid`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait realm_auction_refund_bid {
    /// Request that the remote module invoke the reducer `realm_auction_refund_bid` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`realm_auction_refund_bid:realm_auction_refund_bid_then`] to run a callback after the reducer completes.
    fn realm_auction_refund_bid(
        &self,
        operation_id: u64,
        bidder_guid: u64,
        auction_id: u32,
        offer: u32,
        deferred_refund: u32,
    ) -> __sdk::Result<()> {
        self.realm_auction_refund_bid_then(
            operation_id,
            bidder_guid,
            auction_id,
            offer,
            deferred_refund,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `realm_auction_refund_bid` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn realm_auction_refund_bid_then(
        &self,
        operation_id: u64,
        bidder_guid: u64,
        auction_id: u32,
        offer: u32,
        deferred_refund: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl realm_auction_refund_bid for super::RemoteReducers {
    fn realm_auction_refund_bid_then(
        &self,
        operation_id: u64,
        bidder_guid: u64,
        auction_id: u32,
        offer: u32,
        deferred_refund: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RealmAuctionRefundBidArgs {
                operation_id,
                bidder_guid,
                auction_id,
                offer,
                deferred_refund,
            },
            callback,
        )
    }
}
