// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::transfer_reaper_schedule_type::TransferReaperSchedule;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ReapTransfersArgs {
    pub schedule: TransferReaperSchedule,
}

impl From<ReapTransfersArgs> for super::Reducer {
    fn from(args: ReapTransfersArgs) -> Self {
        Self::ReapTransfers {
            schedule: args.schedule,
        }
    }
}

impl __sdk::InModule for ReapTransfersArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `reap_transfers`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait reap_transfers {
    /// Request that the remote module invoke the reducer `reap_transfers` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`reap_transfers:reap_transfers_then`] to run a callback after the reducer completes.
    fn reap_transfers(&self, schedule: TransferReaperSchedule) -> __sdk::Result<()> {
        self.reap_transfers_then(schedule, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `reap_transfers` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn reap_transfers_then(
        &self,
        schedule: TransferReaperSchedule,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl reap_transfers for super::RemoteReducers {
    fn reap_transfers_then(
        &self,
        schedule: TransferReaperSchedule,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ReapTransfersArgs { schedule }, callback)
    }
}
