// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ResetTalentsArgs {
    pub trainer_guid: u64,
}

impl From<ResetTalentsArgs> for super::Reducer {
    fn from(args: ResetTalentsArgs) -> Self {
        Self::ResetTalents {
            trainer_guid: args.trainer_guid,
        }
    }
}

impl __sdk::InModule for ResetTalentsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `reset_talents`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait reset_talents {
    /// Request that the remote module invoke the reducer `reset_talents` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`reset_talents:reset_talents_then`] to run a callback after the reducer completes.
    fn reset_talents(&self, trainer_guid: u64) -> __sdk::Result<()> {
        self.reset_talents_then(trainer_guid, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `reset_talents` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn reset_talents_then(
        &self,
        trainer_guid: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl reset_talents for super::RemoteReducers {
    fn reset_talents_then(
        &self,
        trainer_guid: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ResetTalentsArgs { trainer_guid }, callback)
    }
}
