// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RevokeAlphaTestToolsArgs {
    pub account_name: String,
}

impl From<RevokeAlphaTestToolsArgs> for super::Reducer {
    fn from(args: RevokeAlphaTestToolsArgs) -> Self {
        Self::RevokeAlphaTestTools {
            account_name: args.account_name,
        }
    }
}

impl __sdk::InModule for RevokeAlphaTestToolsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `revoke_alpha_test_tools`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait revoke_alpha_test_tools {
    /// Request that the remote module invoke the reducer `revoke_alpha_test_tools` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`revoke_alpha_test_tools:revoke_alpha_test_tools_then`] to run a callback after the reducer completes.
    fn revoke_alpha_test_tools(&self, account_name: String) -> __sdk::Result<()> {
        self.revoke_alpha_test_tools_then(account_name, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `revoke_alpha_test_tools` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn revoke_alpha_test_tools_then(
        &self,
        account_name: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl revoke_alpha_test_tools for super::RemoteReducers {
    fn revoke_alpha_test_tools_then(
        &self,
        account_name: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(RevokeAlphaTestToolsArgs { account_name }, callback)
    }
}
