// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SellItemArgs {
    pub vendor_guid: u64,
    pub slot: u8,
}

impl From<SellItemArgs> for super::Reducer {
    fn from(args: SellItemArgs) -> Self {
        Self::SellItem {
            vendor_guid: args.vendor_guid,
            slot: args.slot,
        }
    }
}

impl __sdk::InModule for SellItemArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `sell_item`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait sell_item {
    /// Request that the remote module invoke the reducer `sell_item` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`sell_item:sell_item_then`] to run a callback after the reducer completes.
    fn sell_item(&self, vendor_guid: u64, slot: u8) -> __sdk::Result<()> {
        self.sell_item_then(vendor_guid, slot, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `sell_item` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn sell_item_then(
        &self,
        vendor_guid: u64,
        slot: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl sell_item for super::RemoteReducers {
    fn sell_item_then(
        &self,
        vendor_guid: u64,
        slot: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SellItemArgs { vendor_guid, slot }, callback)
    }
}
