// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetActionButtonArgs {
    pub button: u8,
    pub action: u32,
    pub action_type: u8,
}

impl From<SetActionButtonArgs> for super::Reducer {
    fn from(args: SetActionButtonArgs) -> Self {
        Self::SetActionButton {
            button: args.button,
            action: args.action,
            action_type: args.action_type,
        }
    }
}

impl __sdk::InModule for SetActionButtonArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_action_button`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_action_button {
    /// Request that the remote module invoke the reducer `set_action_button` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_action_button:set_action_button_then`] to run a callback after the reducer completes.
    fn set_action_button(&self, button: u8, action: u32, action_type: u8) -> __sdk::Result<()> {
        self.set_action_button_then(button, action, action_type, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_action_button` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_action_button_then(
        &self,
        button: u8,
        action: u32,
        action_type: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_action_button for super::RemoteReducers {
    fn set_action_button_then(
        &self,
        button: u8,
        action: u32,
        action_type: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetActionButtonArgs {
                button,
                action,
                action_type,
            },
            callback,
        )
    }
}
