// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SpellImpactEvent {
    pub id: u64,
    pub caster_guid: u64,
    pub target_guid: u64,
    pub spell_id: u32,
    pub created_at: __sdk::Timestamp,
    pub damage: u32,
    pub school: u8,
    pub is_crit: bool,
    pub resisted: u32,
    pub absorbed: u32,
    pub map_id: u32,
    pub instance_id: u64,
    pub grid_x: i32,
    pub grid_y: i32,
}

impl __sdk::InModule for SpellImpactEvent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SpellImpactEvent`.
///
/// Provides typed access to columns for query building.
pub struct SpellImpactEventCols {
    pub id: __sdk::__query_builder::Col<SpellImpactEvent, u64>,
    pub caster_guid: __sdk::__query_builder::Col<SpellImpactEvent, u64>,
    pub target_guid: __sdk::__query_builder::Col<SpellImpactEvent, u64>,
    pub spell_id: __sdk::__query_builder::Col<SpellImpactEvent, u32>,
    pub created_at: __sdk::__query_builder::Col<SpellImpactEvent, __sdk::Timestamp>,
    pub damage: __sdk::__query_builder::Col<SpellImpactEvent, u32>,
    pub school: __sdk::__query_builder::Col<SpellImpactEvent, u8>,
    pub is_crit: __sdk::__query_builder::Col<SpellImpactEvent, bool>,
    pub resisted: __sdk::__query_builder::Col<SpellImpactEvent, u32>,
    pub absorbed: __sdk::__query_builder::Col<SpellImpactEvent, u32>,
    pub map_id: __sdk::__query_builder::Col<SpellImpactEvent, u32>,
    pub instance_id: __sdk::__query_builder::Col<SpellImpactEvent, u64>,
    pub grid_x: __sdk::__query_builder::Col<SpellImpactEvent, i32>,
    pub grid_y: __sdk::__query_builder::Col<SpellImpactEvent, i32>,
}

impl __sdk::__query_builder::HasCols for SpellImpactEvent {
    type Cols = SpellImpactEventCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SpellImpactEventCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            caster_guid: __sdk::__query_builder::Col::new(table_name, "caster_guid"),
            target_guid: __sdk::__query_builder::Col::new(table_name, "target_guid"),
            spell_id: __sdk::__query_builder::Col::new(table_name, "spell_id"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            damage: __sdk::__query_builder::Col::new(table_name, "damage"),
            school: __sdk::__query_builder::Col::new(table_name, "school"),
            is_crit: __sdk::__query_builder::Col::new(table_name, "is_crit"),
            resisted: __sdk::__query_builder::Col::new(table_name, "resisted"),
            absorbed: __sdk::__query_builder::Col::new(table_name, "absorbed"),
            map_id: __sdk::__query_builder::Col::new(table_name, "map_id"),
            instance_id: __sdk::__query_builder::Col::new(table_name, "instance_id"),
            grid_x: __sdk::__query_builder::Col::new(table_name, "grid_x"),
            grid_y: __sdk::__query_builder::Col::new(table_name, "grid_y"),
        }
    }
}

/// Indexed column accessor struct for the table `SpellImpactEvent`.
///
/// Provides typed access to indexed columns for query building.
pub struct SpellImpactEventIxCols {
    pub id: __sdk::__query_builder::IxCol<SpellImpactEvent, u64>,
}

impl __sdk::__query_builder::HasIxCols for SpellImpactEvent {
    type IxCols = SpellImpactEventIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SpellImpactEventIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SpellImpactEvent {}
