// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SunkenTempleSuppression {
    pub scheduled_id: u64,
    pub scheduled_at: __sdk::ScheduleAt,
    pub instance_id: u64,
}

impl __sdk::InModule for SunkenTempleSuppression {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SunkenTempleSuppression`.
///
/// Provides typed access to columns for query building.
pub struct SunkenTempleSuppressionCols {
    pub scheduled_id: __sdk::__query_builder::Col<SunkenTempleSuppression, u64>,
    pub scheduled_at: __sdk::__query_builder::Col<SunkenTempleSuppression, __sdk::ScheduleAt>,
    pub instance_id: __sdk::__query_builder::Col<SunkenTempleSuppression, u64>,
}

impl __sdk::__query_builder::HasCols for SunkenTempleSuppression {
    type Cols = SunkenTempleSuppressionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SunkenTempleSuppressionCols {
            scheduled_id: __sdk::__query_builder::Col::new(table_name, "scheduled_id"),
            scheduled_at: __sdk::__query_builder::Col::new(table_name, "scheduled_at"),
            instance_id: __sdk::__query_builder::Col::new(table_name, "instance_id"),
        }
    }
}

/// Indexed column accessor struct for the table `SunkenTempleSuppression`.
///
/// Provides typed access to indexed columns for query building.
pub struct SunkenTempleSuppressionIxCols {
    pub instance_id: __sdk::__query_builder::IxCol<SunkenTempleSuppression, u64>,
    pub scheduled_id: __sdk::__query_builder::IxCol<SunkenTempleSuppression, u64>,
}

impl __sdk::__query_builder::HasIxCols for SunkenTempleSuppression {
    type IxCols = SunkenTempleSuppressionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SunkenTempleSuppressionIxCols {
            instance_id: __sdk::__query_builder::IxCol::new(table_name, "instance_id"),
            scheduled_id: __sdk::__query_builder::IxCol::new(table_name, "scheduled_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SunkenTempleSuppression {}
