// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SystemMessageEvent {
    pub id: u64,
    pub recipient_identity: __sdk::Identity,
    pub recipient_guid: u64,
    pub message: String,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for SystemMessageEvent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SystemMessageEvent`.
///
/// Provides typed access to columns for query building.
pub struct SystemMessageEventCols {
    pub id: __sdk::__query_builder::Col<SystemMessageEvent, u64>,
    pub recipient_identity: __sdk::__query_builder::Col<SystemMessageEvent, __sdk::Identity>,
    pub recipient_guid: __sdk::__query_builder::Col<SystemMessageEvent, u64>,
    pub message: __sdk::__query_builder::Col<SystemMessageEvent, String>,
    pub created_at: __sdk::__query_builder::Col<SystemMessageEvent, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for SystemMessageEvent {
    type Cols = SystemMessageEventCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SystemMessageEventCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            recipient_identity: __sdk::__query_builder::Col::new(table_name, "recipient_identity"),
            recipient_guid: __sdk::__query_builder::Col::new(table_name, "recipient_guid"),
            message: __sdk::__query_builder::Col::new(table_name, "message"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `SystemMessageEvent`.
///
/// Provides typed access to indexed columns for query building.
pub struct SystemMessageEventIxCols {
    pub id: __sdk::__query_builder::IxCol<SystemMessageEvent, u64>,
    pub recipient_identity: __sdk::__query_builder::IxCol<SystemMessageEvent, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for SystemMessageEvent {
    type IxCols = SystemMessageEventIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SystemMessageEventIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            recipient_identity: __sdk::__query_builder::IxCol::new(
                table_name,
                "recipient_identity",
            ),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SystemMessageEvent {}
