// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::aura_schedule_type::AuraSchedule;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TickAurasArgs {
    pub schedule: AuraSchedule,
}

impl From<TickAurasArgs> for super::Reducer {
    fn from(args: TickAurasArgs) -> Self {
        Self::TickAuras {
            schedule: args.schedule,
        }
    }
}

impl __sdk::InModule for TickAurasArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `tick_auras`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait tick_auras {
    /// Request that the remote module invoke the reducer `tick_auras` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`tick_auras:tick_auras_then`] to run a callback after the reducer completes.
    fn tick_auras(&self, schedule: AuraSchedule) -> __sdk::Result<()> {
        self.tick_auras_then(schedule, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `tick_auras` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn tick_auras_then(
        &self,
        schedule: AuraSchedule,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl tick_auras for super::RemoteReducers {
    fn tick_auras_then(
        &self,
        schedule: AuraSchedule,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(TickAurasArgs { schedule }, callback)
    }
}
