// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::melee_schedule_type::MeleeSchedule;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TickMeleeArgs {
    pub schedule: MeleeSchedule,
}

impl From<TickMeleeArgs> for super::Reducer {
    fn from(args: TickMeleeArgs) -> Self {
        Self::TickMelee {
            schedule: args.schedule,
        }
    }
}

impl __sdk::InModule for TickMeleeArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `tick_melee`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait tick_melee {
    /// Request that the remote module invoke the reducer `tick_melee` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`tick_melee:tick_melee_then`] to run a callback after the reducer completes.
    fn tick_melee(&self, schedule: MeleeSchedule) -> __sdk::Result<()> {
        self.tick_melee_then(schedule, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `tick_melee` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn tick_melee_then(
        &self,
        schedule: MeleeSchedule,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl tick_melee for super::RemoteReducers {
    fn tick_melee_then(
        &self,
        schedule: MeleeSchedule,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(TickMeleeArgs { schedule }, callback)
    }
}
