// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct VmapGenerationChunk {
    pub id: u64,
    pub generation_id: u64,
    pub shard_ordinal: u32,
    pub key: u64,
    pub map_id: u32,
    pub cell_x: u16,
    pub cell_y: u16,
    pub blob: Vec<u8>,
}

impl __sdk::InModule for VmapGenerationChunk {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `VmapGenerationChunk`.
///
/// Provides typed access to columns for query building.
pub struct VmapGenerationChunkCols {
    pub id: __sdk::__query_builder::Col<VmapGenerationChunk, u64>,
    pub generation_id: __sdk::__query_builder::Col<VmapGenerationChunk, u64>,
    pub shard_ordinal: __sdk::__query_builder::Col<VmapGenerationChunk, u32>,
    pub key: __sdk::__query_builder::Col<VmapGenerationChunk, u64>,
    pub map_id: __sdk::__query_builder::Col<VmapGenerationChunk, u32>,
    pub cell_x: __sdk::__query_builder::Col<VmapGenerationChunk, u16>,
    pub cell_y: __sdk::__query_builder::Col<VmapGenerationChunk, u16>,
    pub blob: __sdk::__query_builder::Col<VmapGenerationChunk, Vec<u8>>,
}

impl __sdk::__query_builder::HasCols for VmapGenerationChunk {
    type Cols = VmapGenerationChunkCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        VmapGenerationChunkCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            generation_id: __sdk::__query_builder::Col::new(table_name, "generation_id"),
            shard_ordinal: __sdk::__query_builder::Col::new(table_name, "shard_ordinal"),
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            map_id: __sdk::__query_builder::Col::new(table_name, "map_id"),
            cell_x: __sdk::__query_builder::Col::new(table_name, "cell_x"),
            cell_y: __sdk::__query_builder::Col::new(table_name, "cell_y"),
            blob: __sdk::__query_builder::Col::new(table_name, "blob"),
        }
    }
}

/// Indexed column accessor struct for the table `VmapGenerationChunk`.
///
/// Provides typed access to indexed columns for query building.
pub struct VmapGenerationChunkIxCols {
    pub generation_id: __sdk::__query_builder::IxCol<VmapGenerationChunk, u64>,
    pub id: __sdk::__query_builder::IxCol<VmapGenerationChunk, u64>,
}

impl __sdk::__query_builder::HasIxCols for VmapGenerationChunk {
    type IxCols = VmapGenerationChunkIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        VmapGenerationChunkIxCols {
            generation_id: __sdk::__query_builder::IxCol::new(table_name, "generation_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for VmapGenerationChunk {}
