// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct WhisperEvent {
    pub id: u64,
    pub recipient_identity: __sdk::Identity,
    pub other_guid: u64,
    pub is_inform: bool,
    pub message: String,
    pub created_at: __sdk::Timestamp,
    pub recipient_guid: u64,
}

impl __sdk::InModule for WhisperEvent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `WhisperEvent`.
///
/// Provides typed access to columns for query building.
pub struct WhisperEventCols {
    pub id: __sdk::__query_builder::Col<WhisperEvent, u64>,
    pub recipient_identity: __sdk::__query_builder::Col<WhisperEvent, __sdk::Identity>,
    pub other_guid: __sdk::__query_builder::Col<WhisperEvent, u64>,
    pub is_inform: __sdk::__query_builder::Col<WhisperEvent, bool>,
    pub message: __sdk::__query_builder::Col<WhisperEvent, String>,
    pub created_at: __sdk::__query_builder::Col<WhisperEvent, __sdk::Timestamp>,
    pub recipient_guid: __sdk::__query_builder::Col<WhisperEvent, u64>,
}

impl __sdk::__query_builder::HasCols for WhisperEvent {
    type Cols = WhisperEventCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        WhisperEventCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            recipient_identity: __sdk::__query_builder::Col::new(table_name, "recipient_identity"),
            other_guid: __sdk::__query_builder::Col::new(table_name, "other_guid"),
            is_inform: __sdk::__query_builder::Col::new(table_name, "is_inform"),
            message: __sdk::__query_builder::Col::new(table_name, "message"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            recipient_guid: __sdk::__query_builder::Col::new(table_name, "recipient_guid"),
        }
    }
}

/// Indexed column accessor struct for the table `WhisperEvent`.
///
/// Provides typed access to indexed columns for query building.
pub struct WhisperEventIxCols {
    pub id: __sdk::__query_builder::IxCol<WhisperEvent, u64>,
    pub recipient_identity: __sdk::__query_builder::IxCol<WhisperEvent, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for WhisperEvent {
    type IxCols = WhisperEventIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        WhisperEventIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            recipient_identity: __sdk::__query_builder::IxCol::new(
                table_name,
                "recipient_identity",
            ),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for WhisperEvent {}
