//! The cast core — `resolve_cast_at` (+ its extracted `check_cast_gates` gate sweep) / `resolve_cast` /
//! `begin_cast` / the passive-apply path (`passive_applies_effect_kind` / `apply_spell_auras`). 381
//! split: the targeting/effect-dispatch half (`select_targets` / `aura_apply` / `apply_effect`) lives in
//! the sibling `targeting` module; the cast-bar teardown family moved into `control.rs`. `cast::mod`
//! glob re-exports both cast siblings, and `spell::mod` globs `cast::*` in turn, so every
//! `crate::spell::<sym>` call site is unchanged by the split.

use spacetimedb::{log, ReducerContext, ScheduleAt, Table, TimeDuration};

// The `game_world_entity` accessor trait (generated by the table macro in world.rs) must be in scope to
// read/write the live unit row by guid. `game_creature_template` reads the target's creature_type for
// the Sap-opener humanoid gate.
use crate::{game_creature_template, game_world_entity, WorldEntity};
// The `game_item_template` accessor (generated by the table macro in items/tables.rs) — the REQ_DAGGER
// gate joins the caster's main-hand item instance onto its template to read the weapon subclass.
use crate::items::game_item_template;
// Tables, taxonomy consts, math helpers, and the control predicates are all re-exported by `spell::mod`.
use crate::spell::*;

// ===========================================================================================
//  Cast resolution
// ===========================================================================================

// One argument per field of the cast being resolved; the caller has already split the spell/effect rows, so there is no single row type left to pass.
#[allow(clippy::too_many_arguments)]
/// Resolve a cast by explicit caster + explicit target guid: header lookup → GCD gate → cost gate +
/// deduction → iterate `game_spell_effect` in order, dispatching each to its handler → emit ONE cast
/// visual → start the GCD. The single source of truth every cast entry point funnels through
/// (`resolve_cast` self-wraps it; `cast_spell` passes the client target; the debug reducers pass an
/// explicit pair). A multi-effect spell just runs the loop more than once; adding a behavior is a new
/// `kind` + handler arm, with zero edits to this cast core.
///
/// Cost discipline: the caster row is read once, charged, and flushed with one `.update` BEFORE the
/// effect loop (effects act on distinct target rows, or re-read the caster for a self-heal). A cost-0
/// cast does NO caster write — keeping the Battle Shout baseline byte-for-byte.
pub(crate) fn resolve_cast_at(
    ctx: &ReducerContext,
    caster_guid: u64,
    spell_id: u32,
    level: u8,
    target_guid: u64,
    // true ONLY when called from `fire_pending_cast` (a TIMED cast finishing its cast bar): written onto
    // the cast-GO event so the gateway emits GO+COOLDOWN WITHOUT a second SMSG_SPELL_START(0) (the START
    // was already sent at begin_cast). false for an instant cast, a channel, a creature cast, and a
    // triggered cast — all of which still want the START(0)+GO+COOLDOWN instant packet sequence.
    is_completion: bool,
    // true ONLY on the player CMSG_CAST_SPELL path (088; threaded via begin_cast from the cast_spell
    // reducer): the gateway sent that caster's START/RESULT/GO synchronously, so the relay suppresses
    // its duplicate. Channel ticks / triggers / creature / debug / item-use casts pass false and the
    // relay DELIVERS the caster's visual (they never had a synchronous send).
    client_initiated: bool,
    // The clicked GROUND point (118 phase 2), for a ground-targeted cast (CMSG_CAST_SPELL's
    // DEST_LOCATION). `Some` → AREA effects splash from it and a ground patch anchors there; `None` for
    // every non-ground cast (self/unit-target/creature/trigger). Threaded verbatim to select_targets +
    // create_ground_area.
    dest: Option<(f32, f32, f32)>,
) -> Result<(), String> {
    let hdr = ctx
        .db
        .game_spell()
        .spell_id()
        .find(spell_id)
        .ok_or_else(|| format!("unknown spell {spell_id}"))?;

    let mut caster = crate::helpers::live_entity(ctx, caster_guid)
        .map_err(|_| format!("caster {caster_guid} not in world"))?;

    // Load the spell's effects ONCE — used by both `check_cast_gates` (the faction/linked-debuff/radius
    // gates) and the effect loop below. Sorted by effect_index for deterministic order, EXCEPT
    // E_INTERRUPT resolves FIRST: a damage effect at a lower index runs
    // break_auras_on_damage→interrupt_cast, which clears the target's pending cast before a later
    // E_INTERRUPT could read its school for the lockout (Kick/Earth Shock carry E_DAMAGE at index 1,
    // E_INTERRUPT at index 2). Resolving the interrupt first makes the school-lockout order-independent,
    // so a re-import that restores the natural effect order can't silently regress it. Loaded here, ahead
    // of the gate sweep (a pure read — hoisting it earlier than its original mid-gate position changes
    // nothing observable), so `check_cast_gates` can borrow it.
    let mut effects: Vec<SpellEffect> = ctx
        .db
        .game_spell_effect()
        .by_spell()
        .filter(&spell_id)
        .collect();
    effects.sort_by_key(|e| (e.kind != E_INTERRUPT, e.effect_index));

    check_cast_gates(ctx, &caster, &hdr, &effects, target_guid, spell_id, level)?;

    // Charge + flush BEFORE the effects (a self-heal effect re-reads the caster row, so it sees the
    // deducted power; a cost-0 cast writes nothing, preserving the Battle Shout baseline). Deduct ONLY for
    // players — a creature has no pool to drain (and its power stays 0 for the relayed peer view).
    // FSR (Five-Second Rule): stamp `mana_regen_paused_until_ms = now_ms + 5000` whenever mana is
    // spent — the regen tick skips mana for 5s after this, then resumes regardless of combat state
    // (vanilla parity). The `now_ms` here reuses the same epoch-ms formula as combat_until_ms.
    // 114: an on-next-swing spell (Heroic Strike/Cleave) VALIDATES cost at press (the gate above,
    // vanilla shows "Not enough rage" immediately) but CHARGES when the swing FIRES (resolve_swing) —
    // a press-time rage deduction was operator-flagged as wrong (vanilla defers it to the fire).
    let queued_next_swing = effects.iter().any(|e| e.kind == E_NEXT_SWING);
    if caster.is_player() && hdr.cost > 0 && !queued_next_swing {
        let now_ms = (ctx.timestamp.to_micros_since_unix_epoch() / 1000) as u64;
        caster.power = caster.power.saturating_sub(hdr.cost);
        // FSR only applies when mana is spent; rage/energy/health costs must not suppress mana regen.
        if hdr.power_type == lyracore_shared::packing::power_type::MANA {
            caster.mana_regen_paused_until_ms = now_ms + 5000;
        }
        ctx.db.game_world_entity().guid().update(caster);
    }

    // Stealth breaks on action: casting drops the caster's A_STEALTH presence BEFORE the effects run, so
    // a stealthed rogue that casts any spell is revealed. EXCEPTION — a STEALTH_SAFE spell (Sap, Pick
    // Pocket) keeps the rogue stealthed (vanilla: sapping / pick-pocketing doesn't break stealth); the
    // importer flags those by name. Stealth ITSELF needs no special-case — its effect re-applies the
    // A_STEALTH aura further down this same loop, AFTER this break, so re-casting Stealth nets stealthed
    // (a refresh). No-op for an un-stealthed caster (the common case). The other action chokepoint is the
    // swing path (resolve_swing).
    if hdr.cast_flags & SPELL_ATTR_STEALTH_SAFE == 0 {
        break_stealth(ctx, caster_guid);
    }

    // CRAFT reagent gate (282, data-driven) — the profession-loop's reagent cost, co-located with the
    // money/power gates above and BEFORE the E_CREATE_ITEM product grant. A recipe = a spell with a
    // CREATE-ITEM effect AND imported reagents; consume EVERY reagent now (multi-reagent). `remove_items`
    // returns Err (rolling the whole tx back) when a reagent is short, so a craft you can't afford fails
    // atomically — no product, no skill, no power spent. Scoped to create-item spells so a reagent-
    // consuming BUFF (Arcane Intellect → Arcane Powder, no CreateItem effect) is untouched (no regression);
    // a conjure (CreateItem, no reagents) has an empty list → no-op.
    if effects.iter().any(|e| e.kind == E_CREATE_ITEM) {
        for (item, count) in recipe_reagents(ctx, spell_id) {
            crate::items::remove_items(ctx, caster_guid, item, count)?;
        }
    }

    // Run the effects in `effect_index` order (loaded above for the faction gate). Accumulate the
    // post-mitigation damage dealt to the PRIMARY target this cast — only hits on `target_guid` count, so a
    // self-effect / a secondary target doesn't pollute the single-target damage log (multi-target / AoE
    // per-target logging is a follow-up; see the table doc). Summed across damage effects (a multi-effect
    // damage spell), then written onto the cast-GO row so the gateway relays SMSG_SPELLNONMELEEDAMAGELOG.
    let mut total_damage: u32 = 0;
    let mut total_healed: u32 = 0;
    let mut total_resisted: u32 = 0;
    let mut total_absorbed: u32 = 0;
    let mut any_crit = false;
    for e in &effects {
        let points = effect_amount(
            e.base_points,
            e.die_sides,
            e.per_level,
            level as u32,
            hdr.spell_level,
            hdr.max_level,
            ctx.random::<u32>(),
        );
        for t in select_targets(ctx, caster_guid, target_guid, e, dest) {
            // `target_guid` is the cast's EXPLICIT target (the enemy); `t` is this effect's RESOLVED target
            // (T_SELF → the caster). The combo-FINISHER duration scaling needs the enemy key, so thread the
            // explicit `target_guid` as `cast_target_guid` alongside the per-effect `t`.
            let hit = apply_effect(
                ctx,
                e,
                &hdr,
                caster_guid,
                t,
                target_guid,
                level,
                points,
                dest,
            );
            // Only hits on the PRIMARY target feed the single-target damage log (crit/resist/absorb too).
            if t == target_guid {
                total_damage = total_damage.saturating_add(hit.dealt);
                total_resisted = total_resisted.saturating_add(hit.resisted);
                total_absorbed = total_absorbed.saturating_add(hit.absorbed);
                total_healed = total_healed.saturating_add(hit.healed);
                any_crit |= hit.crit;
            }
        }
    }
    // SpellSchool INDEX (0=normal..6=arcane) from the spell header's school BITMASK (1,2,4,…,64) via
    // trailing_zeros — the same mask→index the gateway's SMSG_SPELLNONMELEEDAMAGELOG `school` wants. Stored
    // on the row so the gateway stays dumb. school_mask 0 (rare/unset) → index 0 (Normal/physical).
    let school_index = if hdr.school_mask == 0 {
        0u8
    } else {
        hdr.school_mask.trailing_zeros() as u8
    };

    // ONE cast visual per cast (the caster's animation/SFX), even for a multi-effect spell. This is the
    // cast-GO (the spell resolves): cast_time_ms 0, aimed at the primary target so the gateway's
    // SMSG_SPELL_GO missile flies at it. (A timed spell already emitted a cast-START event in begin_cast.)
    //
    // EXCEPT an on-next-swing QUEUE cast (Heroic Strike/Cleave, 114): the spell did NOT fire — it parked
    // on `next_swing_spell`. Vanilla sends NOTHING at queue time (the client lights the button locally on
    // the press and holds it as a pending cast); the GO + yellow damage log are emitted by the SWING when
    // it fires (resolve_swing inserts the is_completion=true row). Emitting GO here is exactly what
    // un-lit the button and made the damage read as white (the 114 bug pair).
    if !queued_next_swing {
        ctx.db.game_spell_cast_event().insert(SpellCastEvent {
            target_guid,
            // FIX 1: true only on a TIMED-cast COMPLETION (from fire_pending_cast) → gateway suppresses the
            // second START(0). false for instant/channel/creature/triggered → gateway keeps START(0)+GO+CD.
            is_completion,
            // FIX 2: the total post-mitigation damage + school → gateway relays SMSG_SPELLNONMELEEDAMAGELOG
            // (the floating damage number) when damage > 0. 0 for heals/buffs → no damage log.
            damage: total_damage,
            healed: total_healed,
            school: school_index,
            // SPELL-CRIT: the crit flag + resisted/absorbed breakdown for the primary target → gateway renders
            // hit_info=CriticalHit and the (N resisted)/(N absorbed) suffixes. Defaults on a non-damage cast.
            is_crit: any_crit,
            resisted: total_resisted,
            absorbed: total_absorbed,
            // The cooldown starts at the GO (the spell fired). Only spells with a real cooldown send the packet.
            cooldown_ms: hdr.cooldown_ms,
            client_initiated,
            ..SpellCastEvent::signal(ctx, caster_guid, spell_id)
        });
    }

    // AGGRO-ON-HOSTILE-CAST: a player casting an ENEMY-targeting spell at a creature pulls it into combat at
    // CAST time. Vanilla aggros the instant you cast, NOT on the DoT's first tick (~3s later), so this is the
    // cast-level twin of apply_target_damage's engage — it covers DoTs/debuffs (Corruption / Curse of Agony)
    // that apply an aura with NO immediate damage and so never reach apply_target_damage. Gated on hits_enemy
    // so a buff/heal never arms a friendly target; arm_spell_retaliation self-guards (player caster, creature
    // target, not already engaged) so a direct-damage spell that already armed in the effect loop no-ops here,
    // and threat accrues per DoT tick in the scheduler (not a token seed). [server]
    let cast_hits_enemy = effects
        .iter()
        .any(|e| matches!(e.target, T_TARGET_ENEMY | T_AREA_ENEMY | T_CHAIN_ENEMY));
    let caster_is_player = ctx
        .db
        .game_world_entity()
        .guid()
        .find(caster_guid)
        .map(|c| c.is_player())
        .unwrap_or(false);
    if caster_is_player && cast_hits_enemy {
        crate::spell::effects::arm_spell_retaliation(ctx, caster_guid, target_guid);
    }

    // Start the GCD (only on a successful cast). A 0-gcd spell sets none.
    if hdr.gcd_ms > 0 {
        let ready_at = ctx
            .timestamp
            .checked_add(TimeDuration::from_micros((hdr.gcd_ms as i64) * 1000))
            .unwrap_or(ctx.timestamp);
        let cooldowns = ctx.db.game_spell_cooldown();
        if cooldowns.caster_guid().find(caster_guid).is_some() {
            cooldowns.caster_guid().update(SpellCooldown {
                caster_guid,
                ready_at,
            });
        } else {
            cooldowns.insert(SpellCooldown {
                caster_guid,
                ready_at,
            });
        }
    }

    // Start the per-spell cooldown (only on a fully successful cast, and only when the spell HAS one).
    // The `(caster_guid, spell_id)` row's `ready_at` is `now + cooldown_ms`; refresh in place if it
    // already exists (e.g. an expired prior cast left a stale row), else insert. A `cooldown_ms == 0`
    // spell writes nothing — so every current seed spell leaves `game_spell_cd` empty (baseline-safe).
    if hdr.cooldown_ms > 0 {
        let ready_at = ctx
            .timestamp
            .checked_add(TimeDuration::from_micros((hdr.cooldown_ms as i64) * 1000))
            .unwrap_or(ctx.timestamp);
        let cds = ctx.db.game_spell_cd();
        if let Some(mut row) = cds
            .by_caster()
            .filter(&caster_guid)
            .find(|r| r.spell_id == spell_id)
        {
            row.ready_at = ready_at;
            cds.id().update(row);
        } else {
            cds.insert(SpellCd {
                id: 0,
                caster_guid,
                spell_id,
                ready_at,
            });
        }
    }

    // Notify-hook (146): the cast fully RESOLVED — every cast path (player, timed completion,
    // channel, creature, triggered, debug) funnels through this success exit. Rejections above
    // returned Err and never reach here.
    crate::hooks::fire_on_cast_resolved(
        ctx,
        &crate::hooks::CastResolvedPayload {
            caster_guid,
            spell_id,
            target_guid,
        },
    );
    Ok(())
}

/// The GATE SWEEP `resolve_cast_at` runs before spending anything — extracted (381) from what used to be
/// a single ~630-line function, where each of these checks landed as its own commented block, one per
/// work item, in this exact order. Every check here is READ-ONLY (no `.update`/`.insert`/`.delete`, no
/// `power`/item/reagent spend) — the hard boundary is the COST CHARGE in `resolve_cast_at` right after
/// this returns `Ok`, so "spend nothing before cost" holds by construction: nothing below can spend, and
/// everything that spends runs strictly after this call. `effects` is the SAME already-loaded,
/// already-sorted (E_INTERRUPT-first) vec `resolve_cast_at`'s effect loop reuses.
///
/// One deliberate reorder from the pre-381 layout: `is_action_blocked` used to run BEFORE the caster row
/// was loaded (it only reads `game_aura`, not the row); `check_cast_gates` takes the row already in hand,
/// so the load now happens first in the caller. Both are independent early-bail reads with no shared
/// state, so this is a no-observable-difference reorder — not a behavior change.
fn check_cast_gates(
    ctx: &ReducerContext,
    caster: &WorldEntity,
    hdr: &Spell,
    effects: &[SpellEffect],
    target_guid: u64,
    spell_id: u32,
    level: u8,
) -> Result<(), String> {
    let caster_guid = caster.guid;

    // CC: an ACTION-blocked caster (stunned, polymorphed, OR feared) cannot cast. This is the chokepoint
    // for every cast path — player casts, instant `begin_cast`, the delayed `fire_pending_cast` completion,
    // and the creature cast pass — so stun/poly/fear blocks ALL spellcasting (the creature pass also
    // early-outs on this in tick_creatures). Baseline-safe: an un-CC'd caster has no CC aura → `false` →
    // unchanged.
    if is_action_blocked(ctx, caster_guid) {
        return Err(format!("caster {caster_guid} cannot act (stun/poly/fear)"));
    }

    // A DEAD caster cannot cast (mirrors the movement_update dead gate) — closes a dead-player-casting
    // exploit where a corpse buffs itself / debuffs enemies during the death/corpse run. This is the
    // shared chokepoint, so it covers every path (player, instant, delayed completion, creature cast).
    if caster.dead {
        return Err(format!("caster {caster_guid} is dead"));
    }

    // Taming is completion-gated and revalidated here before cost or any write. The handler repeats
    // the same read immediately before conversion to keep its standalone contract safe.
    if effects.iter().any(|effect| effect.kind == E_TAME_CREATURE) {
        crate::creatures::validate_tame(ctx, caster, target_guid)?;
    }

    // Level gate: a CHARACTER cannot cast a rank above its level. Pairs with the trainer level-gate so a
    // higher rank is both UNBUYABLE and UNCASTABLE until you level up — the leveling spine. Keyed on the
    // spell's spell_level (the rank's level); spell_level 0 (no requirement) never gates. Baseline-safe:
    // the seeded rank-1 kit is spell_level 1, so it never trips for a level-1 character.
    // CREATURES are exempt (`is_player()` guard): a mob's rank routinely exceeds its level by design (e.g.
    // Defias Rogue Wizard L9-10 casts Frostbolt 13322 spell_level 20), and the leveling spine is a
    // player-only concept. The guard keeps player casts BYTE-IDENTICAL — see `level_gate_blocks`. [server]
    if level_gate_blocks(caster.is_player(), hdr.spell_level, level) {
        return Err(format!(
            "spell {spell_id} requires level {} (caster is level {level})",
            hdr.spell_level
        ));
    }

    // Stance gate (Tier 3a — Warrior stances): a stance-restricted ability (Stances usability mask != 0) is
    // castable ONLY while the caster is in an allowed stance — bit `1 << stance` of the mask. A mask of 0
    // (every non-warrior, every stance-agnostic spell, the stance-switch spells themselves) never gates, so
    // it is byte-identical for all existing spells/units (baseline-safe). Placed with the intrinsic-eligibility
    // gates (after the level gate, before GCD/cost) so a wrong-stance cast spends nothing — the school-lockout
    // / react-window precedent. Keyed on the caster's `stance` field + the header mask, NEVER a spell id.
    if !stance_allows(hdr.stances, caster.stance) {
        return Err(format!(
            "spell {spell_id} cannot be cast in the caster's current stance ({})",
            caster.stance
        ));
    }

    // School-lockout gate (the Kick silence): a cast whose SCHOOL was just interrupted on this caster is
    // refused until the ~5s lockout expires. Scan the caster's `game_school_lockout` rows (the `by_caster`
    // index) for one matching this spell's `school_mask` that is still ACTIVE (`school_locked` → `until >
    // now`). Placed with the intrinsic-eligibility gates (after dead/level, before GCD/cost) so a locked
    // cast spends nothing. Baseline-safe: a caster who was never Kicked has no lockout row → no match →
    // byte-identical. `school_mask` (a u8 bitmask) is the school field; the lock is keyed on its exact
    // value (single-school spells in vanilla → one bit set).
    if let Some(lock) = ctx
        .db
        .game_school_lockout()
        .by_caster()
        .filter(&caster_guid)
        .find(|r| {
            r.school == hdr.school_mask
                && school_locked(
                    ctx.timestamp.to_micros_since_unix_epoch(),
                    r.until.to_micros_since_unix_epoch(),
                )
        })
    {
        let _ = lock;
        return Err(format!(
            "spell {spell_id} school {} is locked (interrupted) for caster {caster_guid}",
            hdr.school_mask
        ));
    }

    // GCD gate (before cost so an on-cooldown cast spends nothing). The GCD is the per-CASTER row in
    // `game_spell_cooldown` (one row, any spell).
    if let Some(cd) = ctx.db.game_spell_cooldown().caster_guid().find(caster_guid) {
        if is_on_cooldown(
            ctx.timestamp.to_micros_since_unix_epoch(),
            cd.ready_at.to_micros_since_unix_epoch(),
        ) {
            return Err("spell not ready (global cooldown)".to_string());
        }
    }

    // Per-spell cooldown gate (the SEPARATE second gate — checked AFTER the GCD, still BEFORE cost/range
    // so a still-cooling spell spends nothing). Only relevant when this spell HAS its own cooldown
    // (`cooldown_ms > 0`); a `cooldown_ms == 0` spell never wrote a `game_spell_cd` row, so this scan
    // finds nothing and the gate is a no-op (baseline-safe — the existing seed spells are all 0). The
    // logical key is `(caster_guid, spell_id)`: scan the caster's rows (the `by_caster` index) for THIS
    // spell. A boundary tick (`now == ready_at`) is READY (`is_ready_at`), matching the GCD's `<` semantics.
    if hdr.cooldown_ms > 0 {
        if let Some(cd) = ctx
            .db
            .game_spell_cd()
            .by_caster()
            .filter(&caster_guid)
            .find(|r| r.spell_id == spell_id)
        {
            if !is_ready_at(
                ctx.timestamp.to_micros_since_unix_epoch(),
                cd.ready_at.to_micros_since_unix_epoch(),
            ) {
                return Err("spell not ready (cooldown)".to_string());
            }
        }
    }

    // React-window gates (Tier 2b — Overpower / Revenge). A reactive ability is castable ONLY inside the
    // ~5s window the attack table ARMS on the CASTER's own row (resolve_swing stamps `overpower_until_ms`
    // on a HIT_DODGE of the caster's swing; `revenge_until_ms` on a dodge/parry/block BY the caster). Keyed
    // on the cast_flags bit, NEVER a spell id; checks the in-hand `caster` row. Placed with the intrinsic
    // gates (after the cooldown, before range/cost) so a refused react-cast spends nothing. Baseline-safe:
    // a spell without the bit skips both branches (every existing spell), and an un-armed window is 0 →
    // `react_window_active` is false → the gate refuses until a real dodge arms it.
    if hdr.cast_flags & (SPELL_ATTR_REQ_OVERPOWER | SPELL_ATTR_REQ_REVENGE) != 0 {
        let now_ms = (ctx.timestamp.to_micros_since_unix_epoch() / 1000) as u64;
        if hdr.cast_flags & SPELL_ATTR_REQ_OVERPOWER != 0
            && !crate::combat::react_window_active(caster.overpower_until_ms, now_ms)
        {
            return Err(format!(
                "spell {spell_id} requires an Overpower window (the target must have dodged your swing)"
            ));
        }
        if hdr.cast_flags & SPELL_ATTR_REQ_REVENGE != 0
            && !crate::combat::react_window_active(caster.revenge_until_ms, now_ms)
        {
            return Err(format!(
                "spell {spell_id} requires a Revenge window (you must have dodged/parried/blocked)"
            ));
        }
    }

    // Range gate (after GCD, before cost so an out-of-range cast spends nothing). Only a ranged spell
    // (`range_yd > 0`) cast at a DISTINCT target is checked — a self-cast (target == caster) and a
    // `range_yd == 0` spell skip it, so self/adjacent casts are unaffected. The
    // caster row is already in hand; the target row is read fresh (a missing target is left to the
    // effect handlers to no-op on).
    if hdr.range_yd > 0 && target_guid != caster_guid {
        if let Some(target) = ctx.db.game_world_entity().guid().find(target_guid) {
            // World coordinates are per-map, so a Euclidean distance is only meaningful when both units
            // share a map AND instance (work-item 190 slice 1) — a cross-map/cross-instance target is
            // unreachable (treat as out of range) before trusting it.
            if caster.map_id != target.map_id || caster.instance_id != target.instance_id {
                return Err(format!(
                    "target on another map (caster {} != target {})",
                    caster.map_id, target.map_id
                ));
            }
            let dist = distance_3d(caster.x, caster.y, caster.z, target.x, target.y, target.z);
            // Range LEEWAY (vanilla): the cast-COMPLETION range check is lenient — vanilla adds the
            // target's combat reach + a moving-target tolerance, so a mob that drifts a couple yards out of
            // nominal range during the cast still gets hit (mirrors the melee leeway in combat/tables.rs:
            // MELEE_RANGE_LEEWAY_SQ). A mob that RUNS well clear still exceeds this and the cast fails →
            // fire_pending_cast emits the interrupt teardown. Deliberate simplification: flat ≈
            // combat-reach + 8/3 moving tolerance; bump CAST_RANGE_LEEWAY_YD if it still feels too
            // tight on a fleeing mob.
            const CAST_RANGE_LEEWAY_YD: f32 = 2.0 + 8.0 / 3.0; // ≈ 4.67 yd
            if dist > hdr.range_yd as f32 + CAST_RANGE_LEEWAY_YD {
                return Err(format!(
                    "target out of range ({dist:.1} yd > {} + {:.1} yd leeway)",
                    hdr.range_yd, CAST_RANGE_LEEWAY_YD
                ));
            }
        }
    }

    // Faction target gate (after range, before cost — a wrong-faction cast spends nothing). The
    // harmful/helpful signal is the EFFECT TARGET KIND, NOT `is_negative` (that flag is aura buff/debuff
    // polarity for dispel/UI — a direct-damage Fireball is is_negative=false yet is still enemy-only).
    // An ENEMY-targeted effect (T_TARGET_ENEMY / T_AREA_ENEMY / T_CHAIN_ENEMY) cannot land on a FRIENDLY
    // unit; an ALLY-targeted effect (T_TARGET_ALLY / T_AREA_ALLY) cannot land on a HOSTILE unit. T_SELF
    // and T_TARGET_ANY impose no faction constraint (self-buffs; Dispel works on anyone). Self-cast
    // (target == caster, incl. the upstream 0→caster substitution) bypasses, so every self-cast is
    // byte-identical — and a T_SELF-only spell cast "at" an enemy is allowed because it hits neither
    // (hits_enemy = hits_ally = false). NEUTRAL units stay both attackable AND buffable (distinct
    // is_friendly / is_hostile, not a single !hostile). A missing faction template → both predicates
    // false → permissive (no block on absent data). This gates the EXPLICIT target; the area/chain
    // fan-out in `select_targets` re-checks `is_hostile`/`is_friendly` PER resolved target, so a PBAoE
    // (explicit==0, which skips this gate) is still faction-filtered there — no exploit is opened.
    if target_guid != caster_guid {
        // A_FLAG effects are excluded from BOTH scans (266): an inert marker aura carries whatever
        // target type the DBC happened to encode (Taunt's ModTaunt marker reads ALLY, Slice and
        // Dice's read ally too — the name-fix precedent) and imposes no real faction constraint;
        // letting it vote turned Taunt into "targets allies" and refused every yank.
        let hits_enemy = effects.iter().any(|e| {
            e.kind != A_FLAG && matches!(e.target, T_TARGET_ENEMY | T_AREA_ENEMY | T_CHAIN_ENEMY)
        });
        let hits_ally = effects
            .iter()
            .any(|e| e.kind != A_FLAG && matches!(e.target, T_TARGET_ALLY | T_AREA_ALLY));
        if hits_enemy || hits_ally {
            if let Some(target) = ctx.db.game_world_entity().guid().find(target_guid) {
                let friendly = crate::faction::is_friendly(
                    ctx,
                    caster.faction_template,
                    target.faction_template,
                );
                let hostile = crate::faction::is_hostile(
                    ctx,
                    caster.faction_template,
                    target.faction_template,
                );
                if let Some(class) =
                    faction_target_violation(hits_enemy, hits_ally, friendly, hostile)
                {
                    return Err(format!(
                        "spell {spell_id} targets {class} — cannot be cast on this unit ({target_guid})"
                    ));
                }
            }
        }
    }

    // Linked-debuff refusal gate (Weakened Soul / "diminishing re-application" mechanic, #013): an aura
    // effect may carry a LINKED debuff spell id in its otherwise-dead `p1` field (every current aura effect
    // imports/seeds `p1 == 0` — see `aura_apply`'s `eff_p1` freeze, which only special-cases
    // `A_PERIODIC_TRIGGER`; this is the first consumer of a nonzero `p1` on any OTHER aura kind). When set,
    // the EXPLICIT cast target carrying an ACTIVE aura from that linked spell id REFUSES the whole cast
    // (before cost, so a refused cast spends nothing) — generic over the kind/spell id, never named here.
    // PW:Shield (17) sets its `A_ABSORB` effect's `p1` to Weakened Soul's spell id (6788) and Weakened
    // Soul's OWN application (below, after the aura lands) carries `p1 == 0` (a plain marker, not itself
    // linked), so re-shielding within the ~15s window is refused exactly like vanilla, and Weakened Soul
    // applying itself can never self-refuse. Baseline-safe: every spell with `p1 == 0` on every aura effect
    // (every existing seed/imported spell) skips this — the gate is a provable no-op without the data.
    if let Some(e) = effects.iter().find(|e| {
        e.kind & KIND_AURA_BIT != 0 && e.p1 != 0 && has_aura(ctx, target_guid, e.p1 as u32)
    }) {
        return Err(format!(
            "spell {spell_id} refused — target {target_guid} carries the linked debuff {} (Weakened-Soul-style lockout)",
            e.p1
        ));
    }

    // Blink (116) requires its teleport DISTANCE as data — the effect's DBC radius (`radius_yd`,
    // SpellRadius.dbc = 20yd for Blink). A 0/unauthored radius is a DATA BUG, not something to paper
    // over with a hardcoded default (a silent fallback would hide a mis-seeded spell forever). Reject
    // the cast LOUD: the Err propagates to the reducer → SMSG_CAST_FAILED at the client AND a server log.
    if let Some(e) = effects
        .iter()
        .find(|e| e.kind == E_BLINK && e.radius_yd <= 0.0)
    {
        return Err(format!(
            "spell {spell_id} (Blink) effect {} has no radius — teleport distance is unauthored data",
            e.effect_index
        ));
    }
    // A ground-AoE (118) with no radius is unauthored data — reject LOUD rather than spawn a 0-radius
    // area that silently damages nobody (same fail-loud stance as Blink's distance).
    if let Some(e) = effects
        .iter()
        .find(|e| e.kind == E_PERSISTENT_AREA && e.radius_yd <= 0.0)
    {
        return Err(format!(
            "spell {spell_id} (ground-AoE) effect {} has no radius — area size is unauthored data",
            e.effect_index
        ));
    }

    // Rogue cast-gate flags (REQ_BEHIND / REQ_STEALTH + Sap's out-of-combat + humanoid constraints). All
    // read the in-hand `caster`, the spell header flags, and a fresh target row, and all REJECT before the
    // cost charge so a refused cast spends nothing. Keyed on `hdr.cast_flags` bits set by the importer (by
    // name) — the engine never names a spell. Placed AFTER the faction gate and BEFORE the cost/break so
    // `is_stealthed` still reads the caster's pre-break stealth. Baseline-safe: a spell with none of these
    // bits set skips every branch (every existing seed/imported spell). [entity]
    if target_guid != caster_guid {
        // REQ_BEHIND (Backstab): the caster must be in the target's rear 180° hemisphere.
        if hdr.cast_flags & SPELL_ATTR_REQ_BEHIND != 0 {
            let target = crate::helpers::live_entity(ctx, target_guid)
                .map_err(|_| format!("spell {spell_id} target {target_guid} not in world"))?;
            if !is_behind(caster.x, caster.y, target.x, target.y, target.orientation) {
                return Err(format!(
                    "spell {spell_id} must be cast from BEHIND the target ({target_guid})"
                ));
            }
        }
        // REQ_STEALTH (Sap): the caster must be stealthed. Read BEFORE the break below.
        if hdr.cast_flags & SPELL_ATTR_REQ_STEALTH != 0 && !is_stealthed(ctx, caster_guid) {
            return Err(format!(
                "spell {spell_id} requires stealth (caster {caster_guid} is not stealthed)"
            ));
        }
        // Sap-shaped opener constraints: an INCAP_OPENER spell (Sap) additionally requires the target to be
        // OUT of combat AND a HUMANOID creature (vanilla Sap). Keyed on the SEPARATE SPELL_ATTR_INCAP_OPENER
        // bit (NOT REQ_STEALTH) so a non-Sap stealth opener (Garrote — usable on any type, in or out of
        // combat) does NOT inherit these. The live IN_COMBAT unit-flag bit is the cheap authoritative read
        // (kept in sync by enter_combat / the sense-drop pass); the type comes off the template.
        if hdr.cast_flags & SPELL_ATTR_INCAP_OPENER != 0 {
            if let Some(target) = ctx.db.game_world_entity().guid().find(target_guid) {
                if target.unit_flags & lyracore_shared::constants::unit_flags::IN_COMBAT != 0 {
                    return Err(format!(
                        "spell {spell_id} cannot target a unit IN COMBAT ({target_guid})"
                    ));
                }
                // Players are always Humanoid (no creature_template row) — a missing template would
                // otherwise reject every player target.
                let is_humanoid = target.is_player()
                    || ctx
                        .db
                        .game_creature_template()
                        .entry()
                        .find(target.entry)
                        .is_some_and(|t| t.creature_type == HUMANOID_TYPE);
                if !is_humanoid {
                    return Err(format!(
                        "spell {spell_id} can only target a Humanoid ({target_guid})"
                    ));
                }
            }
        }
    }

    // REQ_DAGGER (Backstab): the caster must have a DAGGER equipped in the MAIN-HAND slot. Join the
    // caster's item instance in the main-hand equip slot -> its template -> weapon subclass == DAGGER.
    // A missing main-hand item, a missing template row, a BROKEN weapon, or any non-dagger subclass all
    // refuse — same "no weapon damage" shape as `equipped_weapon_damage`'s broken-weapon check. Placed
    // with the other rogue cast-gate flags, before the cost charge, so a refused cast spends nothing.
    // Baseline-safe: a spell without the bit (every existing spell) skips this entirely.
    if hdr.cast_flags & SPELL_ATTR_REQ_DAGGER != 0 {
        let has_dagger =
            crate::items::item_in_slot(ctx, caster_guid, crate::items::equip_slot::MAINHAND)
                .and_then(|inst| {
                    let tmpl = ctx.db.game_item_template().entry().find(inst.entry)?;
                    if crate::items::item_is_broken(&tmpl, &inst) {
                        return None;
                    }
                    Some(
                        tmpl.class == lyracore_shared::constants::starter_item::CLASS_WEAPON
                            && tmpl.subclass == crate::items::weapon_subclass::DAGGER,
                    )
                })
                .unwrap_or(false);
        if !has_dagger {
            return Err(format!(
                "spell {spell_id} requires a dagger equipped in the main hand (caster {caster_guid})"
            ));
        }
    }

    // Cost gate (cost 0 always affords → baseline-safe). CREATURES are exempt (`is_player()` guard): a
    // creature has NO mana pool (`build_creature_entity` sets power=0/max_power=0) and vanilla mob AI is
    // not mana-managed, so a caster mob / pet would otherwise be rejected on EVERY cost>0 spell (Frostbolt
    // cost 90, Frost Armor cost 10). Gating on `is_player()` (not a spell-id branch) keeps player casts
    // BYTE-IDENTICAL and avoids wiring a mob mana column — see `cost_gate_blocks`. [server]
    if cost_gate_blocks(caster.is_player(), caster.power, hdr.cost) {
        return Err(format!(
            "not enough power: have {}, need {}",
            caster.power, hdr.cost
        ));
    }

    Ok(())
}

/// Resolve a SELF-cast (target == caster) — the thin wrapper preserving the original `resolve_cast`
/// signature so `debug_force_cast` (debug.rs) compiles + behaves unchanged. Self effects ignore the
/// target guid, so self-targeting them is a no-op.
#[cfg_attr(not(feature = "debug_reducers"), allow(dead_code))]
pub(crate) fn resolve_cast(
    ctx: &ReducerContext,
    caster_guid: u64,
    spell_id: u32,
    level: u8,
) -> Result<(), String> {
    // A self-cast is not a timed-cast completion (it resolves synchronously) — instant packet sequence.
    resolve_cast_at(
        ctx,
        caster_guid,
        spell_id,
        level,
        caster_guid,
        false,
        false,
        None,
    )
}

/// Begin a cast, honoring the spell's **cast time**: an instant spell (`cast_time_ms == 0`) resolves
/// synchronously through `resolve_cast_at`; a timed spell schedules a one-shot `PendingCast` whose
/// `fire_pending_cast` callback applies the effect after the cast bar completes. GCD/cost are enforced
/// at cast END (the deliberate simplification; cast-START GCD + interrupt is a later slice).
pub(crate) fn begin_cast(
    ctx: &ReducerContext,
    caster_guid: u64,
    spell_id: u32,
    level: u8,
    target_guid: u64,
    // 088: true only from the cast_spell reducer (the CMSG path) — see resolve_cast_at's param doc.
    client_initiated: bool,
    // The clicked GROUND point (118 phase 2) for a ground-targeted cast. An INSTANT/channel ground cast
    // passes it straight to resolve_cast_at; a TIMED one stashes it on the PendingCast row so the
    // completion (`fire_pending_cast`) can anchor the patch at the click. `None` for every normal cast.
    dest: Option<(f32, f32, f32)>,
) -> Result<(), String> {
    let hdr = ctx
        .db
        .game_spell()
        .spell_id()
        .find(spell_id)
        .ok_or_else(|| format!("unknown spell {spell_id}"))?;

    // A NEW cast breaks any channel already in progress (vanilla: casting interrupts your channel). Fired
    // here at the cast ENTRY so it covers both the instant and the timed branch — and BEFORE the new
    // channel's own `resolve_cast_at` places its aura, so re-casting Arcane Missiles cleanly restarts it.
    // The per-tick missile triggers go straight through `resolve_cast_at` (NOT begin_cast), so a channel
    // never breaks itself. No-op without an active channel/cast (the common path).
    break_channel(ctx, caster_guid);

    // A CHANNELED spell resolves IMMEDIATELY (it never schedules a cast-bar `PendingCast`) — the cast runs
    // the gates + cost ONCE up front, and its `A_PERIODIC_TRIGGER` self-aura then ticks the per-tick missile
    // over `duration_ms` (`tick_auras` does the cadence + the N-tick bound + reaping). This is the channel's
    // THIRD branch alongside instant + timed, keyed on the `SPELL_ATTR_CHANNELED` header bit (set by the
    // importer from the DBC), never a spell id. Arcane Missiles' DBC `cast_time_ms` is already 0 so it would
    // take the instant path regardless; this guard makes a channel resolve-now even if a channeled spell
    // carried a nonzero cast time, and documents the channel path explicitly.
    // Spell-modifier fold (264): the caster's A_SPELLMOD auras (Improved Fireball et al) move THIS
    // spell's cast time — flat then percent, floored at 0. The folded value drives the
    // instant-vs-timed branch, the completion schedule AND the START event's cast bar in LOCKSTEP
    // (a bar that lies about the fire time is the wedge class the cast-lock saga taught us).
    let (ct_flat, ct_pct) =
        crate::spell::math::spell_mod(ctx, caster_guid, SPELLMOD_OP_CASTING_TIME, &hdr);
    let cast_ms = crate::spell::math::apply_spell_mod(hdr.cast_time_ms, ct_flat, ct_pct);

    let completed_channel = hdr.cast_flags & SPELL_ATTR_CHANNELED != 0
        && ctx
            .db
            .game_spell_effect()
            .by_spell()
            .filter(&spell_id)
            .any(|effect| effect.kind == E_TAME_CREATURE);
    if !completed_channel && (cast_ms == 0 || hdr.cast_flags & SPELL_ATTR_CHANNELED != 0) {
        // Instant / channel: resolves NOW (no pending cast bar), so it is NOT a completion — the gateway
        // sends the full instant START(0)+GO+COOLDOWN sequence.
        return resolve_cast_at(
            ctx,
            caster_guid,
            spell_id,
            level,
            target_guid,
            false,
            client_initiated,
            dest,
        );
    }

    let completion_ms = if completed_channel {
        hdr.duration_ms.max(1)
    } else {
        cast_ms
    };
    let fire_at = ctx
        .timestamp
        .checked_add(TimeDuration::from_micros((completion_ms as i64) * 1000))
        .unwrap_or(ctx.timestamp);
    // A new timed cast supersedes any prior pending cast for this caster (vanilla cancels the
    // current spell when a new one starts). Clear stale rows SILENTLY (no is_interrupted signal — that
    // is only for an actual cancel/Kick) so a missed CMSG_CANCEL_CAST can't strand a pending cast that
    // later fires a phantom GO and wedges the client. `cancel_cast` handles the explicit Esc; this is the
    // backstop for the recast path.
    let stale: Vec<u64> = ctx
        .db
        .game_pending_cast()
        .iter()
        .filter(|p| p.caster_guid == caster_guid)
        .map(|p| p.scheduled_id)
        .collect();
    for id in stale {
        ctx.db.game_pending_cast().scheduled_id().delete(id);
    }
    let (has_dest, (dx, dy, dz)) = match dest {
        Some(p) => (true, p),
        None => (false, (0.0, 0.0, 0.0)),
    };
    ctx.db.game_pending_cast().insert(PendingCast {
        scheduled_id: 0,
        scheduled_at: ScheduleAt::Time(fire_at),
        caster_guid,
        spell_id,
        level,
        target_guid,
        pushback_count: 0, // fresh cast: no pushbacks yet
        has_dest,
        dest_x: dx,
        dest_y: dy,
        dest_z: dz,
    });
    // Cast-START event: the gateway relays SMSG_SPELL_START so observers see the cast bar FILL over
    // `cast_time_ms` (the GO event fires later at completion). `game_pending_cast` is non-public, so this
    // public row is the cast-start signal.
    ctx.db.game_spell_cast_event().insert(SpellCastEvent {
        target_guid,
        cast_time_ms: completion_ms,
        // A cast-START is never a completion and carries no damage/cooldown (the GO event at resolve
        // does both); the baseline's is_interrupted:false/delay_ms:0 already hold.
        ..SpellCastEvent::signal(ctx, caster_guid, spell_id)
    });
    Ok(())
}

/// True when a spell effect's `kind` should reach the passive-apply path (`apply_spell_auras`'s
/// `aura_apply` loop) — exactly the aura-kind effects (`KIND_AURA_BIT` set), the SAME split the real cast
/// path already uses to route an effect to `aura_apply` vs its instant handler (`apply_effect` above,
/// `apply_linked_debuff`'s `by_spell().filter(...)`). An instant effect (e.g. Consecration 26573's sole
/// effect, `E_PERSISTENT_AREA` — a ground-AoE) has no business being handed to `aura_apply`: that fn does
/// not interpret instant-kind semantics, it just inserts a `game_aura` row verbatim, which manufactures a
/// spurious aura — and buff-bar/floating-combat-text feedback — for a spell the target never actually cast
/// (#90: every talent-granted ACTIVE did this on login and world-change). Pure so it is unit-tested
/// without a `ReducerContext` (module crate convention — no ctx harness by design).
pub(crate) fn passive_applies_effect_kind(kind: u8) -> bool {
    kind & KIND_AURA_BIT != 0
}

/// Apply a passive (non-cast) spell's auras to `target_guid` at `rank` — each effect's magnitude is
/// `rank * base_points` (so Cruelty rank 3 = +300 crit). Used by talent passives, RACIAL passives, and
/// resurrection sickness (always rank 1 for the latter two). Deliberately BYPASSES the cast gates
/// (`resolve_cast_at`'s GCD/cost/range/action-blocked/dead checks): the source is a passive applied at
/// login / on-learn, not a cast. Self-sourced (caster == target). Idempotent: `aura_apply` refreshes by
/// `effect_id`, so a rank-up re-applies the SAME effect at the new (higher) magnitude — no stacking, and a
/// relog re-applies harmlessly. No-op for an unknown spell id (logged). ONLY aura-kind effects
/// (`KIND_AURA_BIT`) are applied — a talent whose rank-spell is an ACTIVE (Consecration 26573, one
/// `E_PERSISTENT_AREA` effect, no aura effects) must light nothing here; `learn_spell` (the caller in
/// `talent.rs`) already puts the spell in the book, which is what makes it castable. Mirrors the same
/// `KIND_AURA_BIT` filter the real cast path already applies (`apply_effect`/`apply_linked_debuff` above).
/// #90: this filter was previously missing, so EVERY instant effect of a talent rank spell (e.g.
/// Consecration's ground-AoE) was handed to `aura_apply`, minting a spurious aura row / floating combat
/// text on every login and world change. [entity]
pub(crate) fn apply_spell_auras(
    ctx: &ReducerContext,
    spell_id: u32,
    target_guid: u64,
    level: u8,
    rank: u8,
) {
    let Some(mut hdr) = ctx.db.game_spell().spell_id().find(spell_id) else {
        log::info!("apply_spell_auras: unknown spell {spell_id}");
        return;
    };
    // A talent/login PASSIVE with DBC duration 0 is PERMANENT — the pick is its lifetime; only the
    // rank supersede or a respec removes it. Without this the ~1s expiry reap deleted a fresh
    // Improved Fireball modifier (264 live find: rank-2's A_SPELLMOD aura vanished before the next
    // cast). u32::MAX is the established infinite sentinel (Devotion Aura/stances). Scoped HERE
    // (the passive-apply path) so combat casts' real durations are untouched.
    if hdr.duration_ms == 0 {
        hdr.duration_ms = u32::MAX;
    }
    let effects: Vec<SpellEffect> = ctx
        .db
        .game_spell_effect()
        .by_spell()
        .filter(&spell_id)
        .filter(|e| passive_applies_effect_kind(e.kind))
        .collect();
    if effects.is_empty() {
        // Either a data bug (a genuinely passive spell with no effect rows — surface it) or, just as
        // often now, an ACTIVE spell whose effects are all instant (Consecration): nothing to apply, and
        // that silence is correct, not a bug. `apply_spell_auras: unknown spell` above still fires for a
        // missing header, so this log line is purely informational.
        log::info!(
            "apply_spell_auras: spell {spell_id} has no aura-kind effects — nothing applied"
        );
        return;
    }
    for e in effects {
        let points = (rank as i32) * e.base_points;
        // Self-sourced (caster == target); carries no combo-FINISHER flag, so the
        // `cast_target_guid` (== target_guid here) is only used by the flag-gated path, which is inert.
        aura_apply(
            ctx,
            &e,
            &hdr,
            target_guid,
            target_guid,
            target_guid,
            level,
            points,
        );
    }
}
