//! The ctx-bound spell/aura ORCHESTRATION family: the handful of `math.rs` helpers that don't just
//! compute a number but WRITE to the live module — mutating `game_world_entity`/`game_aura`/
//! `game_melee_attack` rows, dispatching into `combat::apply_hit`'s kill fork, or both. Split out of
//! `math.rs` (388) so that file's own doc claim — "everything here is unit-testable without a live
//! module" — is true again: every fn below takes a `ReducerContext` and has a side effect, so none of
//! them belong in a "pure spell math" file, and (per the `test_scan` playbook) none of them get a direct
//! unit test here either — there is no `ReducerContext` harness in this crate by design. `mod.rs`
//! glob re-exports this module (`pub(crate) use effects::*`), so every `crate::spell::<sym>` call site is
//! unchanged by the move.

// `Table` provides `.insert()`/`.update()`/`.delete()` on a table handle; `ReducerContext` is the live db
// handle every fn here threads.
use spacetimedb::{ReducerContext, Table};

// The `game_world_entity` accessor trait (generated by the table macro in world.rs) must be in scope to
// read/write the live unit row by guid.
use crate::game_world_entity;
// The `game_melee_attack` accessor + the `MeleeAttack` struct (re-exported from `combat`): a PLAYER's
// spell damage arms the target creature's reciprocal melee engagement so it RETALIATES.
use crate::{game_melee_attack, MeleeAttack};
// The taxonomy consts, the `Aura` struct + the generated `game_aura`/`game_spell` accessor traits, and
// every pure helper this file calls (`should_arm_spell_retaliation`, `dispel_category_matches`,
// `rederive_pool`, `absorb_draw`, `drain_shields`, `stat_bonus`, ...) are re-exported by `mod.rs`.
use super::*;

/// Should a PLAYER's spell hit arm the target creature's reciprocal melee retaliation? True only when the
/// caster is a player, the target is a CREATURE, and that creature has no engagement of its own yet — the
/// exact gate `aggro_pass` applies to a meleed creature, lifted pure so it's unit-tested. A creature/PvP
/// caster (`!caster_is_player`), a player target (`target_is_player`), or an already-engaged creature
/// (`target_already_engaged`) → false: never make a player auto-retaliate, and don't yank a creature off
/// its current target. Pure — unit-tested in `math.rs`. [server]
///
/// Arm the reciprocal creature→player melee retaliation when a player's HOSTILE spell touches an UNENGAGED
/// creature — the ranged/spell twin of `combat::aggro_pass`. Used by BOTH the damage path (`apply_target_damage`,
/// Shadow Bolt / Fireball) AND the cast-level engage in `resolve_cast_at` (Corruption / Curse of Agony — a DoT
/// or debuff that applies an aura with no immediate damage and so never reaches `apply_target_damage`). Gated by
/// [`should_arm_spell_retaliation`] (defined in `math.rs`): a player caster, a creature target, and no existing
/// engagement (so it never makes a player retaliate, never yanks a creature off its current target, never
/// double-inserts on the `attacker_guid` PK). Idempotent — safe to call from both paths on the same cast. The
/// creature tick then chases + swings, exactly like a melee pull. [server]
pub(crate) fn arm_spell_retaliation(ctx: &ReducerContext, caster_guid: u64, target_guid: u64) {
    let entities = ctx.db.game_world_entity();
    let caster_is_player = entities
        .guid()
        .find(caster_guid)
        .map(|c| c.is_player())
        .unwrap_or(false);
    let target_is_player = entities
        .guid()
        .find(target_guid)
        .map(|t| t.is_player())
        .unwrap_or(true);
    let melee = ctx.db.game_melee_attack();
    let already_engaged = melee.attacker_guid().find(target_guid).is_some();
    if should_arm_spell_retaliation(caster_is_player, target_is_player, already_engaged) {
        melee.insert(MeleeAttack {
            attacker_guid: target_guid, // the creature
            target_guid: caster_guid,   // the player who cast on it
            last_swing_ms: 0,           // swing back on the next melee tick
            ranged_spell_id: 0,         // creature retaliates in melee
            last_offhand_swing_ms: 0,
            rout_ends_ms: 0,
            pursuit_ends_ms: 0,
            leash_x: 0.0,
            leash_y: 0.0,
        });
    }
}

/// Apply `basis` spell damage to `target_guid`, credited to `caster_guid`. A CREATURE reduced to 0
/// **dies** via the SHARED `combat::kill_creature` (corpse + loot + decay — identical to a melee blow);
/// a PLAYER is FLOORED at 1 hp (no spell-death of players yet). A non-lethal hit just subtracts. No-op
/// if the target is gone/dead. XP credited only when the caster is a PLAYER. [entity]
/// Returns `(dealt, absorbed)`: the post-mitigation damage written to health and the amount an A_ABSORB
/// shield soaked before the health write (so the cast-GO row can carry the absorbed figure for the
/// floating damage log). A target that's gone/dead absorbs nothing → `(0, 0)`.
pub(crate) fn apply_target_damage(
    ctx: &ReducerContext,
    target_guid: u64,
    caster_guid: u64,
    basis: i32,
) -> (u32, u32) {
    let entities = ctx.db.game_world_entity();
    // A target that is gone or already a corpse absorbs nothing at all.
    if entities
        .guid()
        .find(target_guid)
        .map(|t| t.dead)
        .unwrap_or(true)
    {
        return (0, 0);
    }
    // Stage 1 of the SHARED damage pipeline (#370): the caster's outgoing % (Defensive Stance's −10%
    // plus any A_MOD_COMBAT(COMBAT_DMG_DONE) curse), the target's A_MOD_DAMAGE_TAKEN %, absorb shields
    // (soaked BEFORE the kill check, so a fully-absorbed hit can't kill), and the GM godmode zero.
    // This is the exact chain the melee/ranged swings fold — they used to be four hand-maintained
    // copies of it.
    let (dmg, absorbed) =
        crate::combat::fold_incoming_damage(ctx, caster_guid, target_guid, basis.max(0) as u32);
    if dmg == 0 {
        return (0, absorbed); // entirely soaked (or godmode) — no health write, no kill
    }
    // The caster is now IN COMBAT — its own UNIT_FLAG_IN_COMBAT (the pure-caster fix: the auto-attack
    // stance can't show a unit that only ever casts). Before the application below so a killing spell
    // flags it too. Re-fetches the caster, so there is no stale-copy overwrite.
    crate::combat::enter_combat(ctx, caster_guid);
    // Stage 2: the SHARED application — the lethal fork through `kill_creature` (a PLAYER target is
    // floored at 1 hp instead: `HitSource::Spell`, there is no spell-death of players yet), the health
    // write, the surviving target's IN_COMBAT stamp, break-on-damage with the `0` attacker sentinel
    // (a spell must not feed the melee-only A_PROC_ON_HIT reactive-chill scan), threat, and the
    // engage-on-damage retaliation arm.
    crate::combat::apply_hit(
        ctx,
        caster_guid,
        target_guid,
        dmg,
        crate::combat::HitSource::Spell,
    );
    // The post-mitigation damage actually dealt + the amount absorbed — the caller (the E_DAMAGE/
    // E_WEAPON_STRIKE arm) sums these into the cast-GO row so the gateway can relay the floating damage
    // number (with the absorbed/resisted breakdown).
    (dmg, absorbed)
}

/// Strip DEBUFFS off `target_guid` in the dispel category `category` — each aura whose
/// `caster_guid != target_guid` (a foreign-cast aura) AND whose OWN spell's `dispel_type` is dispellable
/// by `category` (`dispel_category_matches`, defined in `math.rs`), leaving self-buffs untouched. A
/// `category` of 0 strips every foreign aura (the strip-all behavior). Joins each aura to its
/// `game_spell` header for the category; an aura whose header is gone falls back to its own `dispel_type`
/// (which is 0, so it survives a categorized dispel — never mis-stripped). Collect-then-delete by PK.
/// Returns the count removed.
pub(crate) fn dispel_target(ctx: &ReducerContext, target_guid: u64, category: u8) -> u32 {
    let auras = ctx.db.game_aura();
    let spells = ctx.db.game_spell();
    // Collect full rows (not just ids): a DISPEL is the other DR-removal event (work-item 192) — CC
    // diminishing returns starts its 15s window at removal (natural expiry OR dispel), so each dispelled
    // row's `eff_*` fields must still be readable to check `dr_category_for_effect` BEFORE it's deleted.
    let debuffs: Vec<Aura> = auras
        .by_target()
        .filter(&target_guid)
        .filter(|a| a.caster_guid != target_guid)
        .filter(|a| {
            let aura_cat = spells
                .spell_id()
                .find(a.spell_id)
                .map(|s| s.dispel_type)
                .unwrap_or(0);
            dispel_category_matches(category, aura_cat)
        })
        .collect();
    let removed = debuffs.len() as u32;
    let now_micros = ctx.timestamp.to_micros_since_unix_epoch();
    for a in debuffs {
        if let Some(dr_category) = crate::spell::stacking::dr_category_for_effect(
            ctx,
            a.eff_kind,
            a.eff_p0_kind,
            a.eff_p0,
            a.target_guid,
        ) {
            crate::spell::stacking::dr_window_on_removal(
                ctx,
                a.target_guid,
                dr_category,
                now_micros,
            );
        }
        auras.id().delete(a.id);
    }
    removed
}

/// Recompute `unit_guid`'s `max_health` from EFFECTIVE stamina and (for mana classes) `max_power` from
/// EFFECTIVE intellect, then CLAMP current health/power down to the new max, and write the row. The
/// re-derivation uses the EXACT login curve: `max_health_for(race, class, level)` (the login value, which
/// already folds the unit's base stamina) plus the marginal HP from every `A_MOD_STAT(STA)` aura's
/// stamina bonus (`stat_bonus(.., STAT_STA)`), composed through `stats::hp_from_stamina` so the
/// per-stamina yield matches login (10 HP/point above 20). The mana twin uses `max_power_for` +
/// `stats::mana_from_intellect` for the INT bonus, and ONLY for a mana class (a rage/energy class keeps
/// its login `max_power` untouched — INT doesn't feed those pools).
///
/// BASELINE SAFETY: with NO STA/INT aura the bonus is 0, so `rederive_pool` (defined in `math.rs`) returns
/// the login max byte for byte; the new max equals the stored max and the write is SKIPPED (no-op).
/// race/class come from the unit's packed `unit_bytes_0` (byte0/byte1); a unit not in the world is a
/// no-op. [entity]
pub(crate) fn recompute_vitals(ctx: &ReducerContext, unit_guid: u64) {
    let entities = ctx.db.game_world_entity();
    let Some(mut e) = entities.guid().find(unit_guid) else {
        return;
    };
    // The login stat-curve max only models PLAYERS — a creature's `max_health` is its spawned template
    // HP, NOT `max_health_for`, so re-deriving it from the player curve would corrupt it. A creature
    // therefore keeps its (template) max even if it somehow carried a STA aura (out of slice scope).
    if !e.is_player() {
        return;
    }
    let (race, class, _gender, _pt) = lyracore_shared::packing::unpack4(e.unit_bytes_0);

    // --- max_health from effective stamina (every class has health) ---
    let login_max_health = crate::stats::max_health_for(ctx, race, class, e.level);
    // Effective Stamina bonus = aura A_MOD_STAT(STA) PLUS the Stamina summed across EQUIPPED gear
    // — so a +Stamina chest/ring actually grows the health bar, not just a Mark-of-the-Wild
    // aura. Mirrors how combat's effective_strength folds aura + gear. No gear and no aura → 0, so the
    // pool stays byte-identical to the bare level curve (baseline-safe).
    let sta_bonus = stat_bonus(ctx, unit_guid, STAT_STA)
        + crate::items::equipped_stat_bonus(ctx, unit_guid, crate::items::EquipStat::Stamina);
    let new_max_health = rederive_pool(
        login_max_health,
        e.stamina,
        sta_bonus,
        crate::stats::hp_from_stamina,
    );

    // --- max_power from effective intellect (MANA classes only — rage/energy don't scale off INT) ---
    let is_mana = lyracore_shared::packing::power_type::for_class(class)
        == lyracore_shared::packing::power_type::MANA;
    let new_max_power = if is_mana {
        let login_max_power = crate::stats::max_power_for(ctx, race, class, e.level);
        // Aura INT + equipped INT, the mana twin of the stamina fold above.
        let int_bonus = stat_bonus(ctx, unit_guid, STAT_INT)
            + crate::items::equipped_stat_bonus(ctx, unit_guid, crate::items::EquipStat::Intellect);
        rederive_pool(
            login_max_power,
            e.intellect,
            int_bonus,
            crate::stats::mana_from_intellect,
        )
    } else {
        e.max_power // unchanged for rage/energy pools
    };

    // --- effective Spirit into the FIELD (regen + the char sheet both read e.spirit; unlike STR/AGI which
    // combat re-derives at read time, Spirit's only consumers read the field, so folding it here is safe —
    // no double-count). base (curve) + flat A_MOD_STAT(SPI) auras, then × the A_MOD_STAT_PCT(SPI) multiplier
    // (The Human Spirit +5%). Re-derives base from the curve each call, so it's idempotent on relog.
    let base_spirit = crate::stats::base_attributes_for(ctx, race, class, e.level).4 as i32;
    let spi_flat = stat_bonus(ctx, unit_guid, STAT_SPI);
    let spi_pct = stat_pct_bonus(ctx, unit_guid, STAT_SPI);
    let new_spirit = (((base_spirit + spi_flat) * (100 + spi_pct)) / 100).max(0) as u32;

    // No-op write skip: if nothing moved (the no-aura baseline), don't touch the row.
    if new_max_health == e.max_health && new_max_power == e.max_power && new_spirit == e.spirit {
        return;
    }

    // Raise/lower the max, then CLAMP current down to it (a dropped buff can pull max below current; a
    // gained buff raises max while current stays — `min` leaves current alone when it's already ≤ max).
    e.max_health = new_max_health;
    e.health = e.health.min(new_max_health);
    e.max_power = new_max_power;
    e.power = e.power.min(new_max_power);
    e.spirit = new_spirit;
    entities.guid().update(e);
}

/// Recompute `unit_guid`'s CHARACTER-SHEET numbers (#517) — the paperdoll fields the gateway's
/// `build_sheet_stats_values` merely reads back, never computes: this is the SINGLE fold, so no aura or
/// gear rule is ever duplicated gateway-side (the trap the previous gateway-only `sheet_stats` mirror
/// hit — it never read `game_aura`, so no aura, including Battle Shout, could ever move the sheet).
///
/// Every number here is derived through the SAME functions the live combat/vitals math already uses —
/// `combat::effective_strength`/`effective_agility` (base + `A_MOD_STAT` aura + equipped gear incl.
/// enchants), `combat::aura_attack_power_bonus` (the `A_MOD_COMBAT(COMBAT_ATTACK_POWER)` fold Battle
/// Shout rides), and `combat::swing_range_ctx` (the EXACT weapon/AP/disarm fold `roll_swing` rolls
/// against) — so the sheet can never drift from what a swing actually does.
///
/// Stores a SIGNED bonus per attribute (`sheet_*_bonus`, base + aura + gear − base) rather than a
/// pos/neg split: `effective = base + bonus` by construction, and the gateway derives the green/red
/// paperdoll split via `bonus.max(0)`/`bonus.min(0)` — trivial sign arithmetic, not aura interpretation,
/// so no drift risk moves back into the gateway. AP is split at the source instead
/// (`sheet_ap_base`/`sheet_ap_mods`) because vanilla renders it through two DIFFERENT wire fields
/// (`UNIT_FIELD_ATTACK_POWER` / `_ATTACK_POWER_MODS`), not a color split of one field.
///
/// A non-player (a creature has no character sheet) is a no-op. [entity]
pub(crate) fn recompute_sheet(ctx: &ReducerContext, unit_guid: u64) {
    let entities = ctx.db.game_world_entity();
    let Some(mut e) = entities.guid().find(unit_guid) else {
        return;
    };
    if !e.is_player() {
        return;
    }
    let (race, class, _gender, _pt) = lyracore_shared::packing::unpack4(e.unit_bytes_0);

    let eff_str = crate::combat::effective_strength(ctx, &e);
    let eff_agi = crate::combat::effective_agility(ctx, &e);
    let str_bonus = eff_str as i32 - e.strength as i32;
    let agi_bonus = eff_agi as i32 - e.agility as i32;
    let sta_bonus = stat_bonus(ctx, unit_guid, STAT_STA)
        + crate::items::equipped_stat_bonus(ctx, unit_guid, crate::items::EquipStat::Stamina);
    let int_bonus = stat_bonus(ctx, unit_guid, STAT_INT)
        + crate::items::equipped_stat_bonus(ctx, unit_guid, crate::items::EquipStat::Intellect);
    // `recompute_vitals` (called first at every real call site) already folds Spirit's base+aura into
    // `e.spirit` — re-derive the SAME base curve so the sheet's bonus is `e.spirit - base`, never a
    // second copy of the aura/pct math.
    let base_spirit = crate::stats::base_attributes_for(ctx, race, class, e.level).4 as i32;
    let spi_bonus = e.spirit as i32 - base_spirit;

    let ap_base = crate::combat::melee_attack_power_for(class, eff_str, eff_agi, e.level);
    let ap_mods = crate::combat::aura_attack_power_bonus(ctx, unit_guid) as i32;
    let (dmg_min, dmg_max) = crate::combat::swing_range_ctx(ctx, &e);
    // #532: melee crit for the sheet is a plain READ of the same fold the swing table rolls
    // against — never a second crit formula.
    let crit_bp = crate::combat::effective_crit_bp(ctx, &e);

    if str_bonus == e.sheet_str_bonus
        && agi_bonus == e.sheet_agi_bonus
        && sta_bonus == e.sheet_sta_bonus
        && int_bonus == e.sheet_int_bonus
        && spi_bonus == e.sheet_spi_bonus
        && ap_base == e.sheet_ap_base
        && ap_mods == e.sheet_ap_mods
        && dmg_min == e.sheet_dmg_min
        && dmg_max == e.sheet_dmg_max
        && crit_bp == e.sheet_crit_bp
    {
        return; // nothing moved — skip the write (baseline-safe no-op)
    }
    e.sheet_str_bonus = str_bonus;
    e.sheet_agi_bonus = agi_bonus;
    e.sheet_sta_bonus = sta_bonus;
    e.sheet_int_bonus = int_bonus;
    e.sheet_spi_bonus = spi_bonus;
    e.sheet_ap_base = ap_base;
    e.sheet_ap_mods = ap_mods;
    e.sheet_dmg_min = dmg_min;
    e.sheet_dmg_max = dmg_max;
    e.sheet_crit_bp = crit_bp;
    entities.guid().update(e);
}

/// Soak `incoming` damage through `target_guid`'s A_ABSORB shields BEFORE any health deduction, and
/// return the REMAINING (un-absorbed) damage. Walks the target's A_ABSORB auras in a STABLE order (by
/// aura `id`, so multiple stacked shields drain deterministically — oldest/lowest id first), drawing
/// each pool down via `absorb_draw` (defined in `math.rs`): a shield that still has pool left is written
/// back with the reduced `amount_remaining`; a shield whose pool reaches 0 is DELETED (fully spent).
/// Stops early once the incoming is fully soaked. A target with NO A_ABSORB aura touches nothing and
/// returns `incoming` unchanged (baseline-safe — the health path is identical to before). Collect-then-
/// mutate (never write the aura table mid-iteration). [entity]
pub(crate) fn absorb_incoming(ctx: &ReducerContext, target_guid: u64, incoming: u32) -> u32 {
    if incoming == 0 {
        return 0;
    }
    let auras = ctx.db.game_aura();
    let mut shields: Vec<Aura> = auras
        .by_target()
        .filter(&target_guid)
        .filter(|a| a.eff_kind == A_ABSORB)
        .collect();
    if shields.is_empty() {
        return incoming; // baseline: no shield → full damage, no table write
    }
    shields.sort_by_key(|a| a.id); // stable consume order (oldest shield first)
    let (updated, deleted, remaining_damage) = drain_shields(shields, incoming);
    for shield in updated {
        auras.id().update(shield); // pool survived, partially soaked → write the reduced amount back
    }
    for id in deleted {
        auras.id().delete(id); // pool spent → the shield breaks
    }
    remaining_damage
}
