//! Pure spell math + the aura-read folds, plus a couple of small self-contained aura-table maintenance
//! helpers (`remove_seal_auras` / `break_stealth` — a local collect-then-delete on `game_aura`, nothing
//! else touched). `mod.rs` re-exports these (`pub use math::*`) so every `crate::spell::<sym>` path
//! resolves. A handful of helpers used by the cast pipeline / scheduler are raised to `pub(crate)`
//! (`apply_resistance`, `resist_magic_damage`, `aura_moves_vitals`). The CROSS-CUTTING ORCHESTRATION half
//! that used to live here — `arm_spell_retaliation` / `apply_target_damage` / `dispel_target` /
//! `recompute_vitals` / `absorb_incoming`, every one of which either WRITES `game_world_entity` or
//! dispatches into another top-level module (`combat::apply_hit`'s kill fork, `stacking::dr_window_on_removal`)
//! — moved to `spell/effects.rs` (388): this file's own charter ("unit-tested off a live module", i.e.
//! never REQUIRING one) only became true again once those left.

// `ReducerContext` is the live db handle every ctx-bound helper in this file threads.
use spacetimedb::ReducerContext;

// The `game_world_entity` accessor trait (generated by the table macro in world.rs) must be in scope to
// read/write the live unit row by guid (the cost gate + heal/damage/vitals effects).
use crate::game_world_entity;
// The taxonomy consts, the `Aura` struct + the generated `game_aura`/`game_spell` accessor traits, and
// the sibling control helpers (`break_auras_on_damage`) are re-exported by `mod.rs`.
use super::*;

// ===========================================================================================
//  Pure helpers (unit-tested off a live module)
// ===========================================================================================

/// Cost gate: can the caster's `power` pay `cost`? A cost of 0 always affords (baseline-safe).
pub(crate) fn can_afford(power: u32, cost: u32) -> bool {
    power >= cost
}

/// Does the COST gate REJECT this cast? Players pay (`!can_afford` → blocked); CREATURES are exempt
/// (no mana pool — `build_creature_entity` leaves power=0, vanilla mob/pet AI is not mana-managed). A
/// pure decision so the player-vs-creature divergence is unit-tested without a live DB. Keyed on
/// `is_player` — NEVER a spell id — so player casts stay byte-identical (a player still pays). [server]
pub(crate) fn cost_gate_blocks(is_player: bool, power: u32, cost: u32) -> bool {
    is_player && !can_afford(power, cost)
}

/// Does the LEVEL gate REJECT this cast? A CHARACTER cannot cast a rank above its level (the leveling
/// spine); a CREATURE may cast an above-level rank (mob ranks routinely exceed the mob's level by
/// design). `spell_level == 0` (no requirement) never gates. Pure → unit-tested; keyed on `is_player`
/// (not a spell id) so player casts stay byte-identical. [server]
pub(crate) fn level_gate_blocks(is_player: bool, spell_level: u8, caster_level: u8) -> bool {
    is_player && spell_level > 0 && (caster_level as u32) < spell_level as u32
}

/// New health after a self-heal of `basis` from `health`, clamped to `max_health`. Negative basis = 0.
pub(crate) fn healed_value(health: u32, max_health: u32, basis: i32) -> u32 {
    let gain = basis.max(0) as u32;
    health.saturating_add(gain).min(max_health)
}

/// New health after `basis` direct damage, FLOORED at 1 (the periodic DoT pass never kills). Negative = 0.
pub fn damaged_value(health: u32, basis: i32) -> u32 {
    health.saturating_sub(basis.max(0) as u32).max(1)
}

/// New power after restoring `basis`, clamped to `max_power`. Negative basis = 0. The power twin of
/// `healed_value` — the A_PERIODIC_ENERGIZE tick (and the instant E_ENERGIZE handler share this shape).
pub(crate) fn energized_value(power: u32, max_power: u32, basis: i32) -> u32 {
    let gain = basis.max(0) as u32;
    power.saturating_add(gain).min(max_power)
}

/// Resolve an effect's magnitude: `base_points + per_level·(clamped_level - spell_level) + roll%die_sides`.
/// Level is clamped into `[spell_level, max_level]` (`max_level == 0` ⇒ no cap, only the floor). A
/// `die_sides` of 0 is deterministic (the random `roll` is ignored). Pure — the scaling/rounding is
/// unit-tested; live casts pass `ctx.random()` for the roll.
pub fn effect_amount(
    base_points: i32,
    die_sides: i32,
    per_level: f32,
    level: u32,
    spell_level: u8,
    max_level: u8,
    roll: u32,
) -> i32 {
    let floor = spell_level as u32;
    let capped = if max_level == 0 {
        level.max(floor)
    } else {
        level.clamp(floor, max_level as u32)
    };
    let levels_above = capped.saturating_sub(floor);
    let scaled = base_points + (per_level * levels_above as f32) as i32;
    let die = if die_sides > 0 {
        (roll % die_sides as u32) as i32
    } else {
        0
    };
    scaled + die
}

/// The spell power an `effective_int` (base INT + gear INT + INT auras) grants: `max(0, effective_int -
/// INT_SPELL_POWER_BASE) / INT_PER_SPELL_POWER`, integer-floored. AT or BELOW the floor this is 0, so a
/// low-INT unit (the L2 starter ~20 INT, every creature) derives ZERO INT spell power — the gate that
/// keeps the baseline magnitude byte-identical. Pure (no ctx) → the ramp/flooring is unit-tested. [entity]
pub(crate) fn int_spell_power(effective_int: i32) -> i32 {
    let above = (effective_int - INT_SPELL_POWER_BASE).max(0);
    if INT_PER_SPELL_POWER <= 0 {
        0
    } else {
        above / INT_PER_SPELL_POWER
    }
}

/// Compose an effect's FINAL magnitude from its resolved `base_points` and the caster's `spell_power`,
/// applying the per-effect coefficient (in percent): `base + spell_power * coeff_pct / 100`. A
/// `spell_power` of 0 (the baseline — no INT ramp, no spell-power aura) returns `base` unchanged, so every
/// current seed cast is byte-identical. A negative `base` is preserved (the caller decides direction);
/// `spell_power` is clamped ≥0 (a debuff can't make the caster heal/hit for LESS than base via a negative
/// power). Pure → the composition arithmetic is unit-tested off the live handlers. [entity]
pub(crate) fn compose_magnitude(base_points: i32, spell_power: i32, coeff_pct: i32) -> i32 {
    let sp = spell_power.max(0);
    base_points + sp * coeff_pct / 100
}

/// INNATE spell crit chance (basis points) before Intellect / auras: 0 — vanilla casters derive spell
/// crit almost entirely from INT + talents, so the floor is 0 and `spell_crit_bp` builds the real chance
/// from `intellect_crit_bp` + the COMBAT_CRIT aura fold.
pub(crate) const SPELL_CRIT_BP: u32 = 0;

/// Intellect-derived spell crit (bp), level-suppressed: `int * 100 / (level + 5)`. More INT → more crit;
/// higher level → less per-INT (the vanilla "more INT per 1% crit at higher level" shape). At L2 with the
/// starter INT (~23) this is ~330bp (3.3%). Low-level approximation, NOT a byte-exact vanilla curve —
/// `100`/`+5` are tuning knobs. Pure.
pub(crate) fn intellect_crit_bp(intellect: u32, level: u32) -> u32 {
    intellect * 100 / (level + 5)
}

/// Apply the vanilla SPELL crit multiplier to integer damage: ×1.5 on a crit (NOT ×2 like a melee
/// swing), via `*3/2`. `is_crit == false` → `dmg` unchanged (baseline-safe). Pure — unit-tested. [pure]
pub(crate) fn apply_spell_crit(dmg: i32, is_crit: bool) -> i32 {
    if is_crit {
        dmg * 3 / 2
    } else {
        dmg
    }
}

/// Fold a +crit aura `bonus` (bp) into the `SPELL_CRIT_BP` base, clamped to `[0, 10000]` so the roll
/// band can't go negative or overflow the 0..10000 line. The spell-crit twin of `crit_bp_with_bonus`;
/// the pure core so `spell_crit_bp` adds the aura sum and the unit tests cover it without a context.
/// `bonus == 0` → exactly `SPELL_CRIT_BP`. Pure. [pure]
pub(crate) fn spell_crit_bp_with_bonus(bonus: i32) -> u32 {
    (SPELL_CRIT_BP as i32 + bonus).clamp(0, 10_000) as u32
}

/// Binary SPELL miss chance in basis points by level difference: 4% vs an equal/lower
/// target, +1%/level for the first two levels the target is above (5%, 6%), then the vanilla +11%/level
/// jump beyond that (+3 → 17%, +4 → 28%, …), capped at 99% so a spell can always theoretically land. This
/// is the direct-damage spell hit table — without it every Fireball/Shadow Bolt that passed the cast gates
/// landed. Mirrors the melee `miss_chance_bp` curve in spirit (level-derived). Pure — unit-tested.
pub(crate) fn spell_miss_chance_bp(attacker_level: u32, target_level: u32) -> u32 {
    let diff = target_level.saturating_sub(attacker_level);
    let bp = match diff {
        0 => 400,
        1 => 500,
        2 => 600,
        d => 600 + (d - 2) * 1100, // +3 → 1700 (17%), then +11%/level
    };
    bp.min(9900)
}

/// The caster's EFFECTIVE spell crit chance (bp): the Intellect-derived chance (`intellect_crit_bp` on the
/// caster's EFFECTIVE INT + level) plus every active `A_MOD_COMBAT(CRIT)` aura (the importer maps
/// `ModSpellCritChance` here too, so a spell-crit buff like "Combat Insight" / a talent raises it). The
/// spell twin of `combat::effective_crit_bp` — `apply_effect`'s E_DAMAGE arm rolls against this. A
/// low-INT, un-buffed L2 caster lands at only a few percent crit. [entity]
pub(crate) fn spell_crit_bp(ctx: &ReducerContext, caster_guid: u64) -> u32 {
    let level = ctx
        .db
        .game_world_entity()
        .guid()
        .find(caster_guid)
        .map(|c| c.level)
        .unwrap_or(0);
    let int_crit =
        intellect_crit_bp(effective_intellect(ctx, caster_guid).max(0) as u32, level) as i32;
    spell_crit_bp_with_bonus(int_crit + combat_field_bonus(ctx, caster_guid, COMBAT_CRIT))
}

/// Is the caster still on the global cooldown? `now < ready` is on-cooldown; the boundary is OFF.
pub(crate) fn is_on_cooldown(now_micros: i64, ready_micros: i64) -> bool {
    now_micros < ready_micros
}

/// Is a cooldown READY at `now` given its `ready_at`? The affirmative twin of `is_on_cooldown` (it's the
/// exact negation: `now >= ready` is ready; the boundary tick is ready). Used by the per-spell cooldown
/// gate so the call site reads in the positive ("ready → may cast"). Pure → unit-tested off the module.
pub(crate) fn is_ready_at(now_micros: i64, ready_micros: i64) -> bool {
    now_micros >= ready_micros
}

/// Is a Kick school-lockout still ACTIVE at `now`? A lockout `until` STRICTLY in the future means the
/// school is still locked (`until > now`); a boundary tick (`until == now`) has expired/cleared, matching
/// the `<`/`>=` "ready at the boundary" convention the cooldown gates use. The `resolve_cast_at` school
/// gate rejects a cast whose school has an active lockout for the caster. Pure → unit-tested off the
/// module.
pub(crate) fn school_locked(now_micros: i64, until_micros: i64) -> bool {
    until_micros > now_micros
}

/// 3-D Euclidean distance between two `(x,y,z)` world points (yards). Pure — the range gate uses it to
/// reject a cast on a target farther than the spell's `range_yd`; unit-tested off the module.
pub(crate) fn distance_3d(ax: f32, ay: f32, az: f32, bx: f32, by: f32, bz: f32) -> f32 {
    let (dx, dy, dz) = (ax - bx, ay - by, az - bz);
    (dx * dx + dy * dy + dz * dz).sqrt()
}

/// Missile travel time (ms) for a projectile flying `distance_yd` at `speed_yps` (so a Shadow Bolt lands
/// on impact, not the instant the cast resolves). `speed_yps <= 0` (a melee/instant/self effect that never
/// sets a missile speed) or a non-positive distance both mean "no delay" → 0, so the caller can add this
/// unconditionally without a separate is-it-a-projectile branch. Pure → unit-tested.
pub(crate) fn projectile_travel_ms(distance_yd: f32, speed_yps: f32) -> u32 {
    if speed_yps <= 0.0 || distance_yd <= 0.0 {
        return 0;
    }
    ((distance_yd / speed_yps) * 1000.0).round().max(0.0) as u32
}

/// True iff the attacker at `(ax, ay)` lies in the REAR 180° hemisphere of a target at `(tx, ty)`
/// facing `target_orientation` (radians, 0 = +X axis, increasing CCW toward +Y — WoW's orientation
/// convention, matching the codebase's universal `dy.atan2(dx)` bearing). Orientation points toward the
/// FACING direction, so "behind" is centered on `target_orientation + π`; vanilla "behind" is anywhere in
/// the rear 180° arc (within 90° of directly-behind). A coincident point (`ax==tx && ay==ty`) has no
/// defined bearing → returns `false` (not behind). Pure → unit-tested off the module; the Backstab
/// positional gate (REQ_BEHIND) calls it in `resolve_cast_at`.
pub(crate) fn is_behind(ax: f32, ay: f32, tx: f32, ty: f32, target_orientation: f32) -> bool {
    let (dx, dy) = (ax - tx, ay - ty);
    if dx == 0.0 && dy == 0.0 {
        return false; // coincident — no bearing, treat as not-behind
    }
    // Dot-product form of the rear-180° test (equivalent to the atan2 arc but EXACT at the ±90° seam, and
    // no wraparound normalization): the attacker is behind iff the target→attacker vector `(dx, dy)` lies
    // in the half-plane OPPOSITE the facing vector `(cos o, sin o)`. The projection onto the facing dir is
    // `dx·cos o + dy·sin o`; `<= 0` ⇒ at-or-behind the perpendicular side line ⇒ rear hemisphere. A
    // perpendicular (side-quadrant) attacker projects to exactly 0 → counted as behind (inclusive `<=`),
    // matching the rear-180° arc — and unlike the atan2 form this boundary is symmetric under f32 rounding.
    dx * target_orientation.cos() + dy * target_orientation.sin() <= 0.0
}

/// True iff the target at `(tx, ty)` lies in the FRONT 180° hemisphere of an attacker at
/// `(ax, ay)` facing `attacker_orientation` — the dual of [`is_behind`], same dot-product form
/// (exact at the ±90° seam). Coincident points count as facing (you can always hit something
/// you're standing on). The melee swing gate (combat/mod.rs) calls this for PLAYER attackers —
/// vanilla refuses swings at a target behind you ("You are facing the wrong way!"); creatures
/// auto-face their victim so they're exempt.
// Deliberate simplification: front 180°, not vanilla's stricter ~120° arc — kills the
// attack-while-fleeing exploit; tighten to 2π/3 if side-swings ever read as cheese.
pub fn is_facing(ax: f32, ay: f32, attacker_orientation: f32, tx: f32, ty: f32) -> bool {
    let (dx, dy) = (tx - ax, ty - ay);
    if dx == 0.0 && dy == 0.0 {
        return true;
    }
    dx * attacker_orientation.cos() + dy * attacker_orientation.sin() > 0.0
}

/// Absolute micros at which a `cast_time_ms` cast finishes, given `now_micros`. Pure mirror of the
/// `checked_add(TimeDuration::from_micros(..))` deadline math used for the PendingCast schedule.
pub fn cast_finish_micros(now_micros: i64, cast_time_ms: u32) -> i64 {
    now_micros + (cast_time_ms as i64) * 1000
}

/// Should a PLAYER's spell hit arm the target creature's reciprocal melee retaliation? True only when the
/// caster is a player, the target is a CREATURE, and that creature has no engagement of its own yet — the
/// exact gate `aggro_pass` applies to a meleed creature, lifted pure so it's unit-tested. A creature/PvP
/// caster (`!caster_is_player`), a player target (`target_is_player`), or an already-engaged creature
/// (`target_already_engaged`) → false: never make a player auto-retaliate, and don't yank a creature off
/// its current target. Pure — unit-tested. [server]
pub(crate) fn should_arm_spell_retaliation(
    caster_is_player: bool,
    target_is_player: bool,
    target_already_engaged: bool,
) -> bool {
    caster_is_player && !target_is_player && !target_already_engaged
}

/// The SpellSchool INDEX (0 normal/physical .. 6 arcane) a damage log carries, from a school BITMASK
/// (1, 2, 4, ... 64). The gateway's `SMSG_SPELLNONMELEEDAMAGELOG` wants the index, so every row that
/// carries a school converts here and the gateway stays dumb. A mask of 0 (unset) reads as physical,
/// and a multi-school mask reads as its lowest school — vanilla's own damage log names one school.
/// Pure. [server]
pub(crate) fn school_index(school_mask: u8) -> u8 {
    if school_mask == 0 {
        0
    } else {
        school_mask.trailing_zeros() as u8
    }
}

/// Reduce `dmg` by the target's resistance to the spell's MAGIC school (vanilla average-resist via
/// `combat::resist_mitigation_pct`, capped 75%, level-scaled on the CASTER). The magic-damage twin of how
/// `roll_swing` folds armor into a melee hit. Returns `dmg` UNCHANGED for: a non-positive `dmg`; a
/// physical-only school (mask bit 0 with no magic bits — spells don't use armor here, out of slice); or a
/// target with no resistance aura matching the school (`resistance == 0`, every unit today) — so an
/// un-warded magic hit takes full damage (baseline-safe). A partially-resisted hit floors at 1.
/// `school_mask` is the spell HEADER's school; the resistance is summed from the target's
/// `A_MOD_RESISTANCE` auras overlapping the magic-school bits (`resistance_bonus`, which also backs
/// armor on bit 0 — masked out here so an armor buff never soaks magic). [entity]
pub(crate) fn apply_resistance(
    ctx: &ReducerContext,
    target_guid: u64,
    caster_guid: u64,
    school_mask: u8,
    dmg: i32,
) -> i32 {
    // A missing caster defaults to level 0 (→ 0% mitigation via the formula guard, i.e. full damage —
    // the safe, baseline-identical default), matching the codebase's "missing caster stat → 0"
    // convention (cf. `spell_power`). A real cast always has the caster in hand, so this is degenerate.
    let caster_level = ctx
        .db
        .game_world_entity()
        .guid()
        .find(caster_guid)
        .map(|c| c.level)
        .unwrap_or(0);
    resist_magic_damage(ctx, target_guid, school_mask, caster_level, dmg)
}

/// The shared magic-resistance core: reduce `dmg` by the target's resistance to `school_mask`'s magic
/// schools, capped per `level` (the cap driver — the CASTER's level for an instant cast, the FROZEN cast
/// level for a DoT tick). Strips the physical/armor bit so an armor buff never soaks magic; returns `dmg`
/// UNCHANGED for a non-positive `dmg`, a physical-only school, or a target with no matching resistance
/// aura (every unit today → baseline-safe). A partially-resisted hit floors at 1. Backs both the instant
/// `apply_resistance` and the periodic-DoT resist in `tick_auras` (no duplicated formula). [entity]
pub(crate) fn resist_magic_damage(
    ctx: &ReducerContext,
    target_guid: u64,
    school_mask: u8,
    level: u32,
    dmg: i32,
) -> i32 {
    if dmg <= 0 {
        return dmg;
    }
    let magic_mask = school_mask & !RESIST_ARMOR; // strip the physical/armor bit (bit 0)
    if magic_mask == 0 {
        return dmg; // pure-physical → no magic resist (armor path is out of slice for spells)
    }
    let resistance = resistance_bonus(ctx, target_guid, magic_mask).max(0) as u32;
    if resistance == 0 {
        return dmg; // no resistance to this school → full damage (baseline-safe)
    }
    let pct = crate::combat::resist_mitigation_pct(resistance, level);
    apply_resist_pct(dmg, pct)
}

/// Reduce a positive `dmg` by a resistance `pct` (basis-point-free, a plain 0..=100 percent from
/// `resist_mitigation_pct`'s 75%-capped curve), FLOORED at 1: a resisted hit is mitigated, never fully
/// negated by resistance alone (only a miss/dodge/immunity upstream can zero it). `pct == 0` is a true
/// no-op — the identity the mask-skip / zero-resistance-skip branches above effectively produce by never
/// reaching this call at all. Pure — the mitigation arithmetic `resist_magic_damage` applies once it has a
/// nonzero school-mask + resistance is unit-tested here without a live ctx.
pub(crate) fn apply_resist_pct(dmg: i32, pct: u32) -> i32 {
    (dmg - dmg * pct as i32 / 100).max(1)
}

/// True iff an aura of dispel category `aura_cat` is stripped by a dispel of category `dispel_cat`.
/// A `dispel_cat` of 0 strips EVERYTHING (the strip-all baseline, category-agnostic); a non-zero
/// `dispel_cat` strips only auras whose own category matches exactly (1=magic/2=curse/3=disease/
/// 4=poison). Pure — the join-and-match logic is unit-tested off the live `dispel_target`.
pub(crate) fn dispel_category_matches(dispel_cat: u8, aura_cat: u8) -> bool {
    dispel_cat == 0 || dispel_cat == aura_cat
}

/// Sum a unit's active SEAL aura amounts (`A_SEAL`): every seal aura on `unit_guid` contributes its
/// frozen `amount × stacks`. The per-swing holy value the melee swing reads (Seal of Righteousness) and
/// the burst Judgement unleashes. 0 with no seal (baseline-safe). The combat pull-read for the seal system.
pub(crate) fn seal_amount(ctx: &ReducerContext, unit_guid: u64) -> i32 {
    sum_active_auras(ctx, unit_guid, |a| a.eff_kind == A_SEAL)
}

/// `seal_amount` plus the seal's SPELL id — the swing-proc damage log (114) names its yellow combat-log
/// line after the seal spell. Only one seal is ever active (`remove_seal_auras` enforces it), so the first
/// `A_SEAL` row's spell_id is THE seal. `(0, 0)` with no seal (baseline-safe).
pub(crate) fn seal_amount_and_spell(ctx: &ReducerContext, unit_guid: u64) -> (i32, u32) {
    let spell = auras_on(ctx, unit_guid)
        .find(|a| a.eff_kind == A_SEAL)
        .map(|a| a.spell_id)
        .unwrap_or(0);
    (seal_amount(ctx, unit_guid), spell)
}

/// Consume the seal (Judgement fires and removes it — only ONE seal is ever active). Removes not just
/// the `A_SEAL`-tagged row but every sibling aura sharing its `spell_id`: a multi-effect seal (Seal of
/// the Crusader's AP+haste+A_SEAL trio) is ONE buff in vanilla, so Judgement must drop the whole thing,
/// not leave the non-seal-tagged effects (AP/haste) behind as an orphaned buff. Collect-then-delete by
/// PK. Returns the count removed.
pub(crate) fn remove_seal_auras(ctx: &ReducerContext, unit_guid: u64) -> u32 {
    let auras = ctx.db.game_aura();
    let seal_spell_ids: std::collections::HashSet<u32> = auras
        .by_target()
        .filter(&unit_guid)
        .filter(|a| a.eff_kind == A_SEAL)
        .map(|a| a.spell_id)
        .collect();
    let ids: Vec<u64> = auras
        .by_target()
        .filter(&unit_guid)
        .filter(|a| seal_spell_ids.contains(&a.spell_id))
        .map(|a| a.id)
        .collect();
    let removed = ids.len() as u32;
    for id in ids {
        auras.id().delete(id);
    }
    removed
}

/// Is `unit_guid` stealthed — does it carry an `A_STEALTH` presence aura? The single read the creature
/// aggro pass uses to skip stealthed targets. `false` without a stealth aura (baseline-safe). No expiry
/// check: A_STEALTH is permanent-until-broken (`break_stealth` removes it; the timer reap in `tick_auras`
/// skips the A_STEALTH kind), so its mere presence is authoritative.
pub(crate) fn is_stealthed(ctx: &ReducerContext, unit_guid: u64) -> bool {
    ctx.db
        .game_aura()
        .by_target()
        .filter(&unit_guid)
        .any(|a| a.eff_kind == A_STEALTH)
}

/// Break stealth: remove every `A_STEALTH` aura on `unit_guid`. Called when the unit acts (lands a swing,
/// casts a non-Stealth spell). No-op (returns 0) on a non-stealthed unit, so action chokepoints can call
/// it unconditionally. Collect-then-delete by PK (mirrors `remove_seal_auras`).
pub(crate) fn break_stealth(ctx: &ReducerContext, unit_guid: u64) -> u32 {
    let auras = ctx.db.game_aura();
    let ids: Vec<u64> = auras
        .by_target()
        .filter(&unit_guid)
        .filter(|a| a.eff_kind == A_STEALTH)
        .map(|a| a.id)
        .collect();
    let removed = ids.len() as u32;
    for id in ids {
        auras.id().delete(id);
    }
    removed
}

/// Spell-modifier fold (264): sum the CASTER's `A_SPELLMOD_FLAT` / `A_SPELLMOD_PCT` auras whose
/// SpellModOp (`eff_p0`) is `op` AND whose affected-spell family mask (`eff_p1`, the DBC
/// EffectItemType) names the cast — the MODIFIER's source spell must share `family_name` with the
/// cast header and `hdr.family_flags & mask != 0` (vanilla's SpellModifier match). Returns
/// `(flat, pct)`, both signed sums — the pull-model twin of `combat_field_bonus` plus the family
/// join (a per-aura game_spell point-find; fine at 1-10 scale). A cast whose family data is
/// un-imported (all zero) matches nothing → (0,0), baseline-safe.
pub(crate) fn spell_mod(
    ctx: &ReducerContext,
    caster_guid: u64,
    op: i32,
    hdr: &Spell,
) -> (i32, i32) {
    if hdr.family_name == 0 || hdr.family_flags == 0 {
        return (0, 0);
    }
    let spells = ctx.db.game_spell();
    let family_ok = |a: &Aura| {
        a.eff_p0 == op
            && spells.spell_id().find(a.spell_id).is_some_and(|src| {
                src.family_name == hdr.family_name
                    && hdr.family_flags & (a.eff_p1 as u32 as u64) != 0
            })
    };
    let flat = sum_active_auras(ctx, caster_guid, |a| {
        a.eff_kind == A_SPELLMOD_FLAT && family_ok(a)
    });
    let pct = sum_active_auras(ctx, caster_guid, |a| {
        a.eff_kind == A_SPELLMOD_PCT && family_ok(a)
    });
    (flat, pct)
}

/// Apply a spell-mod `(flat, pct)` to a magnitude: flat first, then percent, floored at 0 (a
/// −200ms fold on a 100ms base clamps to 0 = instant, never underflows). Pure — unit-tested.
pub(crate) fn apply_spell_mod(base: u32, flat: i32, pct: i32) -> u32 {
    let v = base as i64 + flat as i64;
    let v = v * (100 + pct as i64) / 100;
    v.max(0) as u32
}

/// Sum a combat-stat bonus from active auras on `unit_guid`: every `A_MOD_COMBAT` aura whose frozen
/// `eff_p0 == field` contributes `amount × stacks` — a typed, data-driven combat-field bonus with no
/// self-aura/basis-sign decoding. The combat module calls this (e.g. `combat_field_bonus(ctx, guid,
/// COMBAT_ATTACK_POWER)`) reading runtime aura rows directly, never decoding a spell id. [entity]
pub(crate) fn combat_field_bonus(ctx: &ReducerContext, unit_guid: u64, field: u8) -> i32 {
    sum_active_auras(ctx, unit_guid, |a| {
        a.eff_kind == A_MOD_COMBAT && a.eff_p0 == field as i32
    })
}

/// Sum the in-combat health regen percent for `unit_guid`: every `A_COMBAT_HEALTH_REGEN_PCT` aura
/// on the unit contributes `amount × stacks`. 0 = no aura (today's behaviour — zero combat regen).
/// Positive only in practice (a passive racial/talent), but the signed return matches the rest of
/// the aura-sum family so it can compose cleanly. Read by the cycle's regeneration phase to decide
/// whether and how much health to tick during a combat frame. [entity]
pub(crate) fn combat_health_regen_pct(ctx: &ReducerContext, unit_guid: u64) -> i32 {
    sum_active_auras(ctx, unit_guid, |a| a.eff_kind == A_COMBAT_HEALTH_REGEN_PCT)
}

/// Sum a unit's DETECT-RANGE modifier (`A_MOD_DETECT_RANGE`, Priest Mind Soothe): the SIGNED number of
/// YARDS by which its proximity aggro / detection radius is modified while active (`amount × stacks`, summed
/// as f32). Vanilla Mind Soothe carries a NEGATIVE amount (-10), so the sum is negative and SHRINKS the
/// radius. The behavior cycle's aggro phase ADDS this to the creature's aggro radius,
/// clamped ≥ 0, so a soothed mob notices the player only from closer (or, if the reduction exceeds the base
/// radius, not at all). 0 with no such aura → the full radius (baseline-safe — every un-soothed creature).
/// Read on the SOOTHED unit (the creature). [entity]
pub(crate) fn detect_range_mod(ctx: &ReducerContext, unit_guid: u64) -> f32 {
    sum_active_auras(ctx, unit_guid, |a| a.eff_kind == A_MOD_DETECT_RANGE) as f32
}

/// Sum a unit's INCOMING-DAMAGE modifier (signed PERCENT) from active auras: every `A_MOD_DAMAGE_TAKEN`
/// aura on `target_guid` contributes `amount × stacks`. Negative = damage REDUCTION (a defensive cooldown
/// like Shield Wall, −75 → takes 25% damage); positive = a vulnerability debuff. All-school in v1 (the
/// frozen `eff_p0` school mask is captured by the importer but not yet filtered on). 0 with no such aura →
/// `apply_damage_pct` is a no-op (baseline-safe). Read by BOTH damage paths (spell + melee). [entity]
pub(crate) fn damage_taken_bonus(ctx: &ReducerContext, target_guid: u64) -> i32 {
    let aura_pct = sum_active_auras(ctx, target_guid, |a| a.eff_kind == A_MOD_DAMAGE_TAKEN);
    // Defensive Stance's −10% damage taken folds in HERE (Option B — keyed on the target's `stance` field,
    // not an aura) so BOTH damage paths (spell `apply_target_damage` + the melee swing in resolve_swing,
    // which both call this single chokepoint) mitigate identically and a stance switch clears it for free.
    // 0 for a non-Defensive / non-warrior target (stance 0/2), so it's additive to the aura term and
    // baseline-safe. Sums signed with the aura term (a Defensive warrior under Shield Wall stacks both).
    let stance_pct = ctx
        .db
        .game_world_entity()
        .guid()
        .find(target_guid)
        .map(|t| stance_damage_taken_pct(t.stance))
        .unwrap_or(0);
    aura_pct + stance_pct
}

/// Apply a signed percent to a damage value: `dmg * (100 + pct) / 100`. `pct == 0` → `dmg` unchanged
/// (baseline-safe). The denominator is floored at 0 so a ≥100% reduction is full immunity (0), never
/// negative; `i64` math avoids overflow on a large vulnerability stack. Pure — unit-tested. [pure]
///
/// DIRECTION-NEUTRAL despite its callers' framing: `fold_incoming_damage` (combat/death.rs) applies this
/// TWICE per hit — once for the ATTACKER's OUTGOING-damage percent, once for the TARGET's INCOMING-damage
/// percent (`damage_taken_bonus`, below) — because the formula is identical either way (a signed percent
/// scale, floored at 0). 388: previously named `apply_damage_taken`, which asserted a direction the
/// outgoing call site didn't have.
pub(crate) fn apply_damage_pct(dmg: u32, pct: i32) -> u32 {
    ((dmg as i64 * (100 + pct).max(0) as i64) / 100) as u32
}

/// Pure: does a Spell.dbc `Stances` usability `mask` permit casting while in `stance`? Bit `1 << stance`
/// must be set (the importer translates the vanilla form-bit mask onto our 0-based stance bits, so Battle=0
/// is bit 0). A 0 mask permits ANY stance (no requirement — every stance-agnostic spell and every
/// non-warrior cast). `stance >= 8` (out of the byte's bit range) only matters under a non-zero mask, where
/// the shift is bounded so it can't overflow; such a stance is simply disallowed. [pure]
pub(crate) fn stance_allows(mask: u8, stance: u8) -> bool {
    mask == 0 || (stance < 8 && (mask & (1u8 << stance)) != 0)
}

/// Pure: the vanilla ShapeshiftForm id the 5875 client expects in UNIT_FIELD_BYTES_1[2] for our 0-based
/// `stance` — the inverse of the importer's `form_to_stance` (see the STANCE_* convention block in
/// taxonomy.rs, the definition site): Battle 0→17 / Defensive 1→18 / Berserker 2→19 / Bear 3→5 /
/// Cat 4→1 / Dire Bear 5→8. An UNASSIGNED stance id (6, 7, …) falls back to the pre-156 warrior formula
/// (`stance + 17`) so the three warrior stances' byte is BIT-IDENTICAL to what the old inline
/// `(new_stance + 17)` computed and out-of-range ids behave exactly as before the widening. [pure]
pub(crate) fn client_form_for_stance(stance: u8) -> u32 {
    match stance {
        STANCE_BEAR => 5,
        STANCE_CAT => 1,
        STANCE_DIRE_BEAR => 8,
        _ => stance as u32 + 17, // Battle/Defensive/Berserker (0/1/2 → 17/18/19) + the legacy fallback
    }
}

/// Pure: should an E_SET_STANCE cast zero the caster's power? Vanilla 1.12 clears RAGE on a stance switch
/// (the "stance dance" cost). True only when the stance is ACTUALLY changing (`old != new`) AND the
/// caster's power type is RAGE — mana/energy are spared by design, and re-casting the CURRENT stance never
/// drains anything. [pure]
pub(crate) fn stance_switch_clears_power(old_stance: u8, new_stance: u8, power_type: u8) -> bool {
    old_stance != new_stance && power_type == lyracore_shared::packing::power_type::RAGE
}

/// Pure: does recasting the CURRENT stance/form leave it (back to caster form 0)? True only for the
/// druid form id range (>= STANCE_BEAR) — the 5875 client's shapeshift toggle-off IS a recast, and
/// forms are not auras so there is nothing else to cancel (156 review). A warrior recasting his
/// active stance stays a no-op: warriors are never formless in vanilla. Callers must write a ZERO
/// form byte on toggle-off, not `client_form_for_stance(0)` (that is warrior Battle, 17). [pure]
pub(crate) fn form_recast_toggles_off(current: u8, recast: u8) -> bool {
    current == recast && recast >= STANCE_BEAR
}

/// Pure: the signed INCOMING-DAMAGE percent contributed by the unit's `stance` — Defensive Stance's −10%
/// damage taken (`STANCE_DEFENSIVE_DR_PCT`). 0 for every other stance (Battle/Berserker) and every
/// non-warrior (stance 0), so it folds additively into `damage_taken_bonus` with no effect on the existing
/// baseline. A pure function of the field → a stance switch clears it for free (no aura). [pure]
pub(crate) fn stance_damage_taken_pct(stance: u8) -> i32 {
    if stance == STANCE_DEFENSIVE {
        STANCE_DEFENSIVE_DR_PCT
    } else {
        0
    }
}

/// Pure: the signed OUTGOING-DAMAGE percent contributed by the attacker's `stance` — Defensive Stance's
/// −10% damage dealt (`STANCE_DEFENSIVE_DMG_DONE_PCT`). 0 otherwise. Folded at the two outgoing-damage
/// sites (the melee swing's `rolled`, the spell path's basis) via `apply_damage_pct` (which applies a
/// signed percent, floored at 0). [pure]
pub(crate) fn stance_damage_done_pct(stance: u8) -> i32 {
    if stance == STANCE_DEFENSIVE {
        STANCE_DEFENSIVE_DMG_DONE_PCT
    } else {
        0
    }
}

/// Pure: the signed THREAT percent contributed by the source's `stance` — Defensive Stance's +30% threat
/// (`STANCE_DEFENSIVE_THREAT_PCT`). 0 otherwise. Summed alongside the `A_MOD_COMBAT(COMBAT_THREAT)` aura
/// term inside `threat::add_threat` (the single threat chokepoint, read on the threat SOURCE). [pure]
pub(crate) fn stance_threat_pct(stance: u8) -> i32 {
    if stance == STANCE_DEFENSIVE {
        STANCE_DEFENSIVE_THREAT_PCT
    } else {
        0
    }
}

/// Sum a SPEED bonus (signed PERCENT) from active auras on `unit_guid`: every `A_MOD_SPEED` aura whose
/// frozen `eff_p0` names this `speed_kind` (SWING / MOVE / …) contributes `amount × stacks`. Positive =
/// faster, negative = slower (a snare / attack-speed slow). The speed twin of `combat_field_bonus` —
/// `effective_swing_time` folds `SPEED_SWING` (Thunder Clap's slow, the migrated Quickening haste) and
/// `effective_move_speed` folds `SPEED_MOVE` (Hamstring's snare). 0 for an un-affected unit. [entity]
pub(crate) fn speed_bonus(ctx: &ReducerContext, unit_guid: u64, speed_kind: u8) -> i32 {
    sum_active_auras(ctx, unit_guid, |a| {
        a.eff_kind == A_MOD_SPEED && a.eff_p0 == speed_kind as i32
    })
}

/// The owner's active auras as an iterator — the READ twin of `sum_active_auras`, scanning the IDENTICAL
/// `game_aura().by_target().filter(&unit_guid)` index path. The single shared aura-read pipeline: the
/// WRITE side (`sum_active_auras` and the folds built on it) maps+sums these rows; the crowd-control READ
/// side (`has_control_mechanic` / `fear_source` / `is_immune_to_mechanic`) filters them by predicate. A
/// unit with no auras yields an empty iterator. [entity]
pub(crate) fn auras_on(ctx: &ReducerContext, unit_guid: u64) -> impl Iterator<Item = Aura> {
    ctx.db.game_aura().by_target().filter(unit_guid)
}

/// One aura's contribution to a combat fold: `amount × stacks`, with `stacks` floored at 1 so a 0-stack
/// legacy/non-stacking row still counts once. This is where a STACKING debuff/buff compounds — e.g.
/// Sunder Armor frozen at `amount == -90`, `stacks == 5` → `-450` armor. A non-stacking aura is always
/// `stacks == 1`, so this is exactly `amount` for every existing aura. Pure → unit-tested. [pure]
fn stacked_amount(a: &Aura) -> i32 {
    a.amount * (a.stacks.max(1) as i32)
}

/// Sum `amount × stacks` over every active aura on `unit_guid` matching `pred` — the shared pipeline behind
/// `combat_field_bonus` / `stat_bonus` / `resistance_bonus`, which differ ONLY in their predicate. `stacks`
/// is floored at 1 so a 0-stack row still counts once, matching the per-fn behavior before extraction.
fn sum_active_auras(ctx: &ReducerContext, unit_guid: u64, pred: impl Fn(&Aura) -> bool) -> i32 {
    auras_on(ctx, unit_guid)
        .filter(|a| pred(a))
        .map(|a| stacked_amount(&a))
        .sum()
}

/// The caster's **spell power** (a.k.a. healing power) — the caster-side scaling number folded into
/// E_DAMAGE / E_HEAL magnitudes via `compose_magnitude`. Two additive sources:
///   1. **INT ramp** — `int_spell_power(effective_int)`, where effective INT = the stored base
///      (`caster.intellect`) + every `A_MOD_STAT(INT)` aura (`stat_bonus(.., STAT_INT)`) + the INT summed
///      across EQUIPPED gear (`items::equipped_stat_bonus(.., Intellect)`). The ramp is 0 at/below the
///      starter floor (`INT_SPELL_POWER_BASE`), so the L2 player and every creature contribute 0.
///   2. **Spell-power auras** — every `A_MOD_COMBAT(COMBAT_SPELL_POWER)` aura (`combat_field_bonus(..,
///      COMBAT_SPELL_POWER)`), e.g. a seeded "Spell Power" buff. None present → 0.
///
/// A caster that is not in the world returns 0. `school_mask` is RESERVED for later school-specific power
/// (fire vs frost vs holy) — accepted now, school-agnostic for the slice, so the signature is stable when
/// that lands. A caster with the starter INT and no spell-power aura sums to 0 → magnitudes are
/// unchanged from the baseline (the explicit baseline gate). [entity]
pub(crate) fn spell_power(ctx: &ReducerContext, caster_guid: u64, school_mask: u8) -> i32 {
    let _ = school_mask; // reserved: school-agnostic for the slice (later: per-school power)
    int_spell_power(effective_intellect(ctx, caster_guid))
        + combat_field_bonus(ctx, caster_guid, COMBAT_SPELL_POWER)
}

/// The caster's EFFECTIVE Intellect: stored base (`caster.intellect`) + every `A_MOD_STAT(INT)` aura
/// (Arcane Intellect) + the INT summed across EQUIPPED gear. The INT twin of `combat::effective_strength`,
/// shared by `spell_power` (INT ramp) and `spell_crit_bp` (INT-derived crit) so they read one number. A
/// caster not in the world → 0. [entity]
pub(crate) fn effective_intellect(ctx: &ReducerContext, caster_guid: u64) -> i32 {
    let base_int = ctx
        .db
        .game_world_entity()
        .guid()
        .find(caster_guid)
        .map(|c| c.intellect as i32)
        .unwrap_or(0);
    base_int
        + stat_bonus(ctx, caster_guid, STAT_INT)
        + crate::items::equipped_stat_bonus(ctx, caster_guid, crate::items::EquipStat::Intellect)
}

/// Sum a base-attribute bonus from active auras on `unit_guid`: every `A_MOD_STAT` aura whose frozen
/// `eff_p0` names this `stat` (or is `STAT_ALL`, an all-attribute buff like Mark of the Wild)
/// contributes `amount × stacks`. The stat-effect twin of `combat_field_bonus` — the combat module folds this
/// into the unit's EFFECTIVE attribute (e.g. effective Strength = base + `stat_bonus(.., STAT_STR)`)
/// before deriving combat numbers, so a +stat buff is mechanically real (it raises the swing), not just
/// a stored aura row. Returns 0 for an un-buffed unit, so an aura-free derivation is unchanged. [entity]
pub(crate) fn stat_bonus(ctx: &ReducerContext, unit_guid: u64, stat: u8) -> i32 {
    sum_active_auras(ctx, unit_guid, |a| {
        a.eff_kind == A_MOD_STAT && (a.eff_p0 == stat as i32 || a.eff_p0 == STAT_ALL as i32)
    })
}

/// Sum the PERCENT stat modifier for `stat` from active `A_MOD_STAT_PCT` auras (The Human Spirit = +5%
/// Spirit). Returns the total percent (e.g. 5). `recompute_vitals` folds it as a MULTIPLIER on the resolved
/// stat — `(base + flat) * (100 + pct) / 100` — distinct from the flat `stat_bonus` add. 0 for an un-buffed
/// unit, so an aura-free derivation is unchanged.
pub(crate) fn stat_pct_bonus(ctx: &ReducerContext, unit_guid: u64, stat: u8) -> i32 {
    sum_active_auras(ctx, unit_guid, |a| {
        a.eff_kind == A_MOD_STAT_PCT && (a.eff_p0 == stat as i32 || a.eff_p0 == STAT_ALL as i32)
    })
}

/// Sum a resistance/armor bonus from active auras on `unit_guid`: every `A_MOD_RESISTANCE` aura whose
/// frozen `eff_p0` school MASK overlaps `school_mask` (e.g. `RESIST_ARMOR` bit 0) contributes
/// `amount × stacks`. The resistance twin of `stat_bonus` — the combat module folds this into a unit's
/// EFFECTIVE armor before computing damage mitigation, so an armor buff actually softens incoming hits,
/// not just a stored aura. Returns 0 for an un-buffed unit, so mitigation is unchanged without it. [entity]
pub(crate) fn resistance_bonus(ctx: &ReducerContext, unit_guid: u64, school_mask: u8) -> i32 {
    sum_active_auras(ctx, unit_guid, |a| {
        a.eff_kind == A_MOD_RESISTANCE && (a.eff_p0 as u32 & school_mask as u32) != 0
    })
}

// ===========================================================================================
//  Vitals re-derivation (STA → max_health, INT → max_power) on aura apply/expire
// ===========================================================================================

/// Apply a base-attribute DELTA to a `login_max` pool via the vanilla derived-stat curve, RE-USING the
/// SAME curve the login path used: `new_max = login_max + (curve(base + bonus) - curve(base))`. The
/// `login_max` already includes `curve(base)` (login computed it from the same `base`), so we add only
/// the marginal contribution of the aura `bonus` points — and we add it through the IDENTICAL `curve`
/// function (`stats::hp_from_stamina` / `mana_from_intellect`), so the <20 breakpoint is honored exactly
/// and a `bonus == 0` is a provable no-op (`curve(base) - curve(base) == 0` ⇒ `new_max == login_max`).
/// A negative `bonus` (a stat-debuff aura) lowers the pool but never below the curve's base-only value
/// (we never subtract more than the bonus contributed). Pure (no ctx) → unit-tested in isolation.
pub(crate) fn rederive_pool(
    login_max: u32,
    base_attr: u32,
    bonus: i32,
    per_point: fn(u32) -> u32,
) -> u32 {
    // The effective attribute, floored at 0 (a debuff bigger than the base attribute can't go negative).
    let effective = (base_attr as i64 + bonus as i64).max(0) as u32;
    let from_base = per_point(base_attr);
    let from_eff = per_point(effective);
    // Swap the base-attribute contribution for the effective one via SIGNED arithmetic so the result is a
    // TRUE no-op at bonus == 0 (from_eff == from_base) for ALL inputs — even a synthetic login_max smaller
    // than from_base (which a saturating_sub would wrongly floor to 0 and then inflate). Floored at 0.
    (login_max as i64 - from_base as i64 + from_eff as i64).max(0) as u32
}

/// True iff `effect` is an `A_MOD_STAT` aura that touches STAMINA or INTELLECT — the only stat changes
/// that move a max-health / max-mana pool, so the recompute is gated to these (a +STR/+AGI/+SPI buff,
/// or any non-stat aura, skips the vitals re-derive entirely → no work, baseline-safe). `STAT_ALL`
/// (Mark of the Wild's all-attribute form) counts (it includes STA and INT). Pure → unit-tested.
pub(crate) fn aura_moves_vitals(kind: u8, p0: i32) -> bool {
    kind == A_MOD_STAT && (p0 == STAT_STA as i32 || p0 == STAT_INT as i32 || p0 == STAT_ALL as i32)
}

/// True iff `effect` is an aura that moves a character-sheet number `recompute_sheet` derives: any
/// `A_MOD_STAT` (all five attributes, including `STAT_ALL`), an `A_MOD_COMBAT(COMBAT_ATTACK_POWER)`
/// aura (Battle Shout), or an `A_MOD_COMBAT(COMBAT_CRIT)` aura (#532 — `sheet_crit_bp`, the
/// `PLAYER_CRIT_PERCENTAGE` source). Strictly wider than [`aura_moves_vitals`] (which only cares about
/// the two stats that move a pool) — a +STR/+AGI/+SPI buff, an AP buff, or a crit-rating buff moves the
/// sheet even though none of them move a pool. Pure → unit-tested (mirrors `aura_moves_vitals`'s test
/// shape).
pub(crate) fn aura_moves_sheet(kind: u8, p0: i32) -> bool {
    (kind == A_MOD_STAT
        && (p0 == STAT_STR as i32
            || p0 == STAT_AGI as i32
            || p0 == STAT_STA as i32
            || p0 == STAT_INT as i32
            || p0 == STAT_SPI as i32
            || p0 == STAT_ALL as i32))
        || (kind == A_MOD_COMBAT
            && (p0 == COMBAT_ATTACK_POWER as i32 || p0 == COMBAT_CRIT as i32))
}

/// One shield's draw against `incoming` damage from a pool of `remaining`: returns
/// `(absorbed, pool_left, leftover)`. The shield soaks up to its pool — `absorbed = min(remaining,
/// incoming)`; `pool_left = remaining - absorbed` (0 ⇒ the shield is spent and the caller deletes it);
/// `leftover = incoming - absorbed` (passes to the next shield, or out to the health path). Pure — the
/// pool-draw arithmetic (partial soak / soak-and-deplete-with-overflow) is unit-tested in isolation.
pub(crate) fn absorb_draw(remaining: i32, incoming: u32) -> (u32, i32, u32) {
    let pool = remaining.max(0) as u32;
    let absorbed = pool.min(incoming);
    let pool_left = (pool - absorbed) as i32;
    let leftover = incoming - absorbed;
    (absorbed, pool_left, leftover)
}

/// Pure mirror of `effects::absorb_incoming`'s multi-shield drain loop: given `shields` already filtered to
/// `A_ABSORB` and SORTED oldest-first by aura id (the same order `absorb_incoming` sorts into), drains them
/// against `incoming` damage in that exact order and classifies each visited shield as either surviving
/// (partial soak — its `amount_remaining` mutated, needs a table `update`) or fully spent (needs a `delete`).
/// STOPS EARLY the instant the incoming is fully absorbed — any shield past that point is left in neither
/// list (untouched, exactly mirroring the live loop's `if remaining_damage == 0 { break; }`). Returns
/// `(updated, deleted_ids, remaining_damage)`. Pure over in-memory rows (no ctx) — `effects::absorb_incoming`
/// calls this so the multi-shield order/early-stop logic lives in exactly one place, unit-tested here in
/// isolation.
pub(crate) fn drain_shields(shields: Vec<Aura>, incoming: u32) -> (Vec<Aura>, Vec<u64>, u32) {
    let mut remaining_damage = incoming;
    let mut updated = Vec::new();
    let mut deleted = Vec::new();
    for mut shield in shields {
        if remaining_damage == 0 {
            break;
        }
        let (_absorbed, pool_left, leftover) =
            absorb_draw(shield.amount_remaining, remaining_damage);
        remaining_damage = leftover;
        if pool_left <= 0 {
            deleted.push(shield.id);
        } else {
            shield.amount_remaining = pool_left;
            updated.push(shield);
        }
    }
    (updated, deleted, remaining_damage)
}

#[cfg(test)]
mod tests {
    use super::*;
    use spacetimedb::Timestamp;

    /// Minimal `Aura` with the fields `stacked_amount` reads; the rest are inert defaults.
    fn aura(amount: i32, stacks: u8) -> Aura {
        Aura {
            id: 0,
            target_guid: 0,
            caster_guid: 0,
            spell_id: 0,
            slot: 0,
            level: 0,
            flags: 0,
            applied_at: Timestamp::UNIX_EPOCH,
            expires_at: Timestamp::UNIX_EPOCH,
            effect_id: 0,
            eff_kind: A_MOD_RESISTANCE,
            amount,
            eff_p0: RESIST_ARMOR as i32,
            eff_p0_kind: P_SCHOOL_MASK,
            eff_p1: 0,
            period_ms: 0,
            amount_remaining: 0,
            stacks,
            next_tick_micros: 0,
            channel_target: 0,
            enters_combat: false, // synthetic (resistance) aura — not a combat-entering energize
            proc_flags: 0,
            proc_chance: 0,
            proc_ppm: 0.0,
            proc_ex: 0,
            proc_school_mask: 0,
            proc_family_name: 0,
            proc_family_flags: 0,
            proc_charges: 0,
            proc_icd_ms: 0,
            proc_ready_micros: 0,
        }
    }

    /// ENGAGE-ON-DAMAGE gate: `should_arm_spell_retaliation` is the exact predicate `aggro_pass`
    /// applies, lifted pure. Arm the reciprocal melee row ONLY for a player→creature hit on an un-engaged
    /// creature.
    #[test]
    fn should_arm_spell_retaliation_gates_player_vs_unengaged_creature() {
        // The one TRUE case: player caster, creature target, creature not yet engaged → pull it.
        assert!(should_arm_spell_retaliation(true, false, false));
        // Already-engaged creature → don't yank it off its current target / double-insert on the PK.
        assert!(!should_arm_spell_retaliation(true, false, true));
        // Player target (PvP) → never auto-retaliate the victim.
        assert!(!should_arm_spell_retaliation(true, true, false));
        // Creature/NPC caster → no player-driven pull (creatures keep no threat/engagement this way).
        assert!(!should_arm_spell_retaliation(false, false, false));
    }

    /// The one mask→index rule every damage-log row converts through. Values are vanilla's
    /// `SpellSchools` order, read off the 1.12 client's own enumeration.
    #[test]
    fn school_index_names_the_lowest_school_in_the_mask() {
        use super::school_index;
        assert_eq!(school_index(0), 0); // unset reads as physical
        assert_eq!(school_index(0x01), 0); // physical
        assert_eq!(school_index(0x02), 1); // holy
        assert_eq!(school_index(0x04), 2); // fire
        assert_eq!(school_index(0x08), 3); // nature
        assert_eq!(school_index(0x10), 4); // frost
        assert_eq!(school_index(0x20), 5); // shadow
        assert_eq!(school_index(0x40), 6); // arcane
                                           // A multi-school mask names its lowest school: a damage log carries one school, not a set.
        assert_eq!(school_index(0x14), 2);
    }

    #[test]
    fn stacked_amount_compounds_with_stacks() {
        // Sunder Armor: amount frozen at -90 (debuff, signed by the importer); 5 stacks → -450 armor.
        assert_eq!(stacked_amount(&aura(-90, 5)), -450);
        assert_eq!(stacked_amount(&aura(-90, 1)), -90); // a single application
                                                        // Non-stacking / legacy-0 rows count exactly once (the read-side floor at 1).
        assert_eq!(stacked_amount(&aura(50, 1)), 50);
        assert_eq!(stacked_amount(&aura(50, 0)), 50);
    }

    #[test]
    fn apply_spell_mod_folds_flat_then_pct_and_floors_at_zero() {
        use super::apply_spell_mod;
        assert_eq!(apply_spell_mod(3000, 0, 0), 3000); // no modifier -> unchanged
        assert_eq!(apply_spell_mod(3000, -200, 0), 2800); // Improved Fireball r2 on a 3.0s cast
        assert_eq!(apply_spell_mod(3000, -500, 0), 2500);
        assert_eq!(apply_spell_mod(100, -200, 0), 0); // over-reduction clamps to instant, no underflow
        assert_eq!(apply_spell_mod(1000, 0, -10), 900); // percent path
        assert_eq!(apply_spell_mod(1000, -100, -10), 810); // flat first, then percent
    }

    #[test]
    fn projectile_travel_ms_scales_distance_over_speed() {
        // Shadow Bolt (~21 yd/s) at 21 yd -> 1000ms; at 10.5yd -> 500ms.
        assert_eq!(projectile_travel_ms(21.0, 21.0), 1000);
        assert_eq!(projectile_travel_ms(10.5, 21.0), 500);
        // 0 distance (a self/adjacent target) -> no delay even with a real speed.
        assert_eq!(projectile_travel_ms(0.0, 21.0), 0);
        // 0 (or negative) speed -> an instant/melee effect that never sets a missile speed -> no delay,
        // regardless of distance (so callers can add this unconditionally with no is-projectile branch).
        assert_eq!(projectile_travel_ms(30.0, 0.0), 0);
        assert_eq!(projectile_travel_ms(30.0, -1.0), 0);
    }

    /// `apply_resist_pct`: the floor-at-1 mitigation math `resist_magic_damage` applies once it has
    /// escaped the mask-skip (`magic_mask == 0`) and zero-resistance-skip branches — those branches never
    /// call this at all, but a `pct == 0` here reproduces their identity effect (`dmg` unchanged). A
    /// partial pct reduces proportionally; ANY pct (even a theoretical 100%, past the real 75% mitigation
    /// cap from `resist_mitigation_pct`) FLOORS at 1 — resistance alone never fully negates a hit.
    #[test]
    fn apply_resist_pct_scales_and_floors_at_one() {
        assert_eq!(apply_resist_pct(100, 0), 100); // no mitigation → unchanged (the skip-branch identity)
        assert_eq!(apply_resist_pct(100, 50), 50); // half resisted
        assert_eq!(apply_resist_pct(100, 75), 25); // the real 75%-capped mitigation
        assert_eq!(apply_resist_pct(4, 75), 1); // 4 - 3 = 1, exact (no clamp needed)
        assert_eq!(apply_resist_pct(100, 100), 1); // a theoretical 100% pct still floors at 1, never 0
        assert_eq!(apply_resist_pct(1, 75), 1); // a 1-damage hit can't go below 1 either
    }

    /// Minimal `A_ABSORB` shield `Aura` for `drain_shields`: only `id`/`amount_remaining` vary, the rest
    /// reuse `aura`'s inert defaults.
    fn shield(id: u64, amount_remaining: i32) -> Aura {
        Aura {
            id,
            amount_remaining,
            eff_kind: A_ABSORB,
            eff_p0: 0,
            eff_p0_kind: P_NONE,
            ..aura(0, 1)
        }
    }

    /// `Aura` carries neither `PartialEq` nor `Debug` (a live table row), so `drain_shields`'s `updated`
    /// list is compared by projecting each survivor to its `(id, amount_remaining)` pair.
    fn ids_and_pools(shields: &[Aura]) -> Vec<(u64, i32)> {
        shields.iter().map(|a| (a.id, a.amount_remaining)).collect()
    }

    /// `drain_shields` on a SINGLE shield: partial soak leaves it in `updated` with the reduced pool;
    /// an exact deplete puts its id in `deleted` instead (never both).
    #[test]
    fn drain_shields_single_shield_partial_and_exact_deplete() {
        // Partial soak: a 100-pool shield eats a 20-hit — survives with 80 left, no delete.
        let (updated, deleted, remaining) = drain_shields(vec![shield(5, 100)], 20);
        assert_eq!(ids_and_pools(&updated), vec![(5, 80)]);
        assert!(deleted.is_empty());
        assert_eq!(remaining, 0);
        // Exact deplete: a 20-pool eats a 20-hit — the shield breaks (deleted), nothing left to update.
        let (updated, deleted, remaining) = drain_shields(vec![shield(7, 20)], 20);
        assert!(updated.is_empty());
        assert_eq!(deleted, vec![7]);
        assert_eq!(remaining, 0);
        // A spent pool (5) vs a bigger hit (20): absorbs 5, breaks, and 15 spills through untouched (no
        // further shields to catch it).
        let (updated, deleted, remaining) = drain_shields(vec![shield(9, 5)], 20);
        assert!(updated.is_empty());
        assert_eq!(deleted, vec![9]);
        assert_eq!(remaining, 15);
    }

    /// `drain_shields` order + early-stop across MULTIPLE shields: drains OLDEST-first (the input order,
    /// which `absorb_incoming` sorts by aura id before calling this), and STOPS the instant the incoming is
    /// fully soaked — any shield past that point is visited by NEITHER list (untouched, not even read).
    #[test]
    fn drain_shields_oldest_first_with_early_stop() {
        // Two stacked shields (30 then 50 pool) vs a 60-hit: the first (oldest) breaks spilling 30 into the
        // second, which absorbs 30 of its 50 (20 left) — fully absorbed, nothing spills further.
        let (updated, deleted, remaining) = drain_shields(vec![shield(1, 30), shield(2, 50)], 60);
        assert_eq!(ids_and_pools(&updated), vec![(2, 20)]);
        assert_eq!(deleted, vec![1]);
        assert_eq!(remaining, 0);
        // Three 50-pool shields vs a 40-hit: the FIRST alone absorbs it all (10 left) — the second and
        // third are never touched (absent from BOTH updated and deleted), proving the early `break`.
        let (updated, deleted, remaining) =
            drain_shields(vec![shield(1, 50), shield(2, 50), shield(3, 50)], 40);
        assert_eq!(ids_and_pools(&updated), vec![(1, 10)]);
        assert!(deleted.is_empty());
        assert_eq!(remaining, 0);
    }

    /// `drain_shields` on an empty shield list is a no-op — the whole `incoming` passes through unchanged
    /// (mirrors `absorb_incoming`'s own `shields.is_empty()` early return, exercised here at the pure layer).
    #[test]
    fn drain_shields_empty_list_passes_incoming_through() {
        let (updated, deleted, remaining) = drain_shields(vec![], 42);
        assert!(updated.is_empty());
        assert!(deleted.is_empty());
        assert_eq!(remaining, 42);
    }
}

#[cfg(test)]
mod facing_tests {
    use super::is_facing;
    use std::f32::consts::PI;

    /// The swing gate's cone (testing-hardening §3.5): every player melee swing routes through
    /// this — a wrong seam silently `continue`s the swing tick forever (the fight-stall class the
    /// 2026-07-16 suite archaeology kept hitting), so the boundary behavior is pinned here.
    #[test]
    fn front_and_behind_at_the_cardinal_orientations() {
        // Facing +x (orientation 0): east is front, west is behind.
        assert!(is_facing(0.0, 0.0, 0.0, 5.0, 0.0));
        assert!(!is_facing(0.0, 0.0, 0.0, -5.0, 0.0));
        // Facing -x (orientation π): mirrored.
        assert!(is_facing(0.0, 0.0, PI, -5.0, 0.0));
        assert!(!is_facing(0.0, 0.0, PI, 5.0, 0.0));
        // Facing +y (orientation π/2): north front, south behind.
        assert!(is_facing(0.0, 0.0, PI / 2.0, 0.0, 5.0));
        assert!(!is_facing(0.0, 0.0, PI / 2.0, 0.0, -5.0));
    }

    #[test]
    fn the_90_degree_seam_is_exclusive_and_diagonals_resolve() {
        // Exactly perpendicular (dot == 0) is NOT facing — the gate is strict `> 0`, so a target
        // precisely at your shoulder is refused (documented: "exact at the ±90° seam").
        assert!(!is_facing(0.0, 0.0, 0.0, 0.0, 5.0));
        assert!(!is_facing(0.0, 0.0, 0.0, 0.0, -5.0));
        // A hair forward of the seam faces; a hair back doesn't.
        assert!(is_facing(0.0, 0.0, 0.0, 0.1, 5.0));
        assert!(!is_facing(0.0, 0.0, 0.0, -0.1, 5.0));
    }

    #[test]
    fn wrapped_and_negative_orientations_behave() {
        // The 5875 client streams orientations in [0, 2π) but nothing guarantees it — the gate
        // must be pure trig, not range-dependent. 2π ≡ 0 and -π/2 ≡ 3π/2 (facing -y).
        assert!(is_facing(0.0, 0.0, 2.0 * PI, 5.0, 0.001));
        assert!(is_facing(0.0, 0.0, -PI / 2.0, 0.0, -5.0));
        assert!(!is_facing(0.0, 0.0, -PI / 2.0, 0.0, 5.0));
    }

    #[test]
    fn coincident_points_always_face() {
        // You can always hit something you're standing on (the spawn-at-feet fixture case).
        assert!(is_facing(3.0, -4.0, 1.234, 3.0, -4.0));
    }
}
